version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "In Install"
      - pip install semantic_version
      - pip install boto3
  pre_build:
    commands:
      - echo "In Pre_build"
      - python semantic-version.py m
  build:
    commands:
      - echo "VFAP Repo Build"
      - find $CODEBUILD_SRC_DIR/ -name build.sh -type f -exec sh {} \;
  post_build:
    commands:
      - echo "Post Build Actions"
      - rm -rf $CODEBUILD_SRC_DIR/current.txt
      - aws s3 cp $CODEBUILD_SRC_DIR/main.json s3://vf-artifacts-bucket/vfap/main.json
artifacts:
  files:
    - main.json
    