version: 0.2
env:
  secrets-manager:
    v: versioning:version:AWSCURRENT:AWSCURRENT
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "In Install"
      - pip install semantic_version
  pre_build:
    commands:
      - echo "In Pre_build"
      - python --version
      - echo $v
      - python $CODEBUILD_SRC_DIR/sem.py
  build:
    commands:
      - echo "VFAP repo Build"
  post_build:
    commands:
      - echo "Post Build Actions"
artifacts:
  files:
    - main.json
    