version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "In Install"
      - pip install semantic_version
      - pip install boto3
  pre_build:
    commands:
      - echo "In Pre_build"
      - python sem.py m
  build:
    commands:
      - echo "VFAP Repo Build"
      - echo "version: $VERSION"
  post_build:
    commands:
      - echo "Post Build Actions"
artifacts:
  files:
    - main.json
    