version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "In Install"
      - apt-get install jq -y
  pre_build:
    commands:
      - echo "In Pre_build"
      - aws s3 cp s3://vf-artifacts-bucket/vfap/semantic-versioning/src/versioning.sh $CODEBUILD_SRC_DIR/
      - sh $CODEBUILD_SRC_DIR/versioning.sh -m
  build:
    commands:
      - echo "VFAP repo Build"
  post_build:
    commands:
      - echo "Post Build Actions"
      - aws s3 cp $CODEBUILD_SRC_DIR/main.json s3://vf-artifacts-bucket/vfap/main.json
artifacts:
  files:
    - main.json
    