version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "In Install"
      - pip install semantic_version
  pre_build:
    commands:
      - echo "In Pre_build"
  build:
    commands:
      - echo "VFAP Build"
      - cat build-init.sh
      - sh build-init.sh
artifacts:
  files:
    - main.json
    