version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "In Install"
  pre_build:
    commands:
      - sam --version
  build:
    commands:
      - echo "Ingestion Routine Build"
      - find $CODEBUILD_SRC_DIR/ingest_routine -name build.sh -type f -exec sh {} \;
  post_build:
    commands:
      - echo "Post Build Actions"
artifacts:
  files:
    - main.json
