INSERT INTO vfap_retail.address (select 
  customer_id,
  customer_no,
  address_id,
  country_code,
  address_match_key,
  telephone_no,
  address_type_code,
  address_1,
  address_2,
  address_3,
  address_4,
  post_code,
  date_last_modified,
  mail_opt_in_flag,
  mail_opt_in_date,
  phone_opt_in_flag,
  phone_opt_in_date,
  sas_brand_id,
  fs_sk,
  current_timestamp as process_dtm,
  ''::varchar(200) as file_name
 from whousep.address);
 
INSERT INTO vfap_retail.adobe_prodview_xref_final_ss (
select visitor_id,
customer_id,
sas_brand_id
from whousep.adobe_prodview_xref_final_ss);

INSERT INTO vfap_retail.brand (
select brand_id_desc,
sas_brand_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.brand);
 
INSERT INTO vfap_retail.class (select 
class_code,
department_code,
class_description,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.class);
 
INSERT INTO vfap_retail.cm_abandon (select  session_id,
cookie_id,
ts,
product_id,
product_name,
product_category,
product_category_id,
product_category_top,
product_category_bottom,
base_price,
qy,
order_id,
site_id,
abandonment_attribute_1,
abandonment_attribute_2,
abandonment_attribute_3,
abandonment_attribute_4,
abandonment_attribute_5,
abandonment_attribute_6,
abandonment_attribute_7,
abandonment_attribute_8,
abandonment_attribute_9,
abandonment_attribute_10,
abandonment_attribute_11,
abandonment_attribute_12,
abandonment_attribute_13,
abandonment_attribute_14,
abandonment_attribute_15,
abandonment_attribute_16,
abandonment_attribute_17,
abandonment_attribute_18,
abandonment_attribute_19,
abandonment_attribute_20,
abandonment_attribute_21,
abandonment_attribute_22,
abandonment_attribute_23,
abandonment_attribute_24,
abandonment_attribute_25,
abandonment_attribute_26,
abandonment_attribute_27,
abandonment_attribute_28,
abandonment_attribute_29,
abandonment_attribute_30,
abandonment_attribute_31,
abandonment_attribute_32,
abandonment_attribute_33,
abandonment_attribute_34,
abandonment_attribute_35,
abandonment_attribute_36,
abandonment_attribute_37,
abandonment_attribute_38,
abandonment_attribute_39,
abandonment_attribute_40,
abandonment_attribute_41,
abandonment_attribute_42,
abandonment_attribute_43,
abandonment_attribute_44,
abandonment_attribute_45,
abandonment_attribute_46,
abandonment_attribute_47,
abandonment_attribute_48,
abandonment_attribute_49,
abandonment_attribute_50,
sas_brand_id,
fs_sk,
customer_id,
sas_product_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cm_abandon);
 
 
INSERT INTO vfap_retail.cm_conversion (select  session_id,
cookie_id,
ts,
event_name,
event_category,
event_action_type,
event_points,
site_id,
conversion_event_attribute_1,
conversion_event_attribute_2,
conversion_event_attribute_3,
conversion_event_attribute_4,
conversion_event_attribute_5,
conversion_event_attribute_6,
conversion_event_attribute_7,
conversion_event_attribute_8,
conversion_event_attribute_9,
conversion_event_attribute_10,
conversion_event_attribute_11,
conversion_event_attribute_12,
conversion_event_attribute_13,
conversion_event_attribute_14,
conversion_event_attribute_15,
conversion_event_attribute_16,
conversion_event_attribute_17,
conversion_event_attribute_18,
conversion_event_attribute_19,
conversion_event_attribute_20,
conversion_event_attribute_21,
conversion_event_attribute_22,
conversion_event_attribute_23,
conversion_event_attribute_24,
conversion_event_attribute_25,
conversion_event_attribute_26,
conversion_event_attribute_27,
conversion_event_attribute_28,
conversion_event_attribute_29,
conversion_event_attribute_30,
conversion_event_attribute_31,
conversion_event_attribute_32,
conversion_event_attribute_33,
conversion_event_attribute_34,
conversion_event_attribute_35,
conversion_event_attribute_36,
conversion_event_attribute_37,
conversion_event_attribute_38,
conversion_event_attribute_39,
conversion_event_attribute_40,
conversion_event_attribute_41,
conversion_event_attribute_42,
conversion_event_attribute_43,
conversion_event_attribute_44,
conversion_event_attribute_45,
conversion_event_attribute_46,
conversion_event_attribute_47,
conversion_event_attribute_48,
conversion_event_attribute_49,
conversion_event_attribute_50,
sas_brand_id,
fs_sk,
customer_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cm_conversion);
 
 
INSERT INTO vfap_retail.cm_mmcclick (select  session_id,
cookie_id,
ts,
marketing_vendor,
marketing_category,
marketing_placement,
marketing_item,
site_id,
mmc_click_attribute_1,
mmc_click_attribute_2,
mmc_click_attribute_3,
mmc_click_attribute_4,
mmc_click_attribute_5,
mmc_click_attribute_6,
mmc_click_attribute_7,
mmc_click_attribute_8,
mmc_click_attribute_9,
mmc_click_attribute_10,
mmc_click_attribute_11,
mmc_click_attribute_12,
mmc_click_attribute_13,
mmc_click_attribute_14,
mmc_click_attribute_15,
mmc_click_attribute_16,
mmc_click_attribute_17,
mmc_click_attribute_18,
mmc_click_attribute_19,
mmc_click_attribute_20,
mmc_click_attribute_21,
mmc_click_attribute_22,
mmc_click_attribute_23,
mmc_click_attribute_24,
mmc_click_attribute_25,
mmc_click_attribute_26,
mmc_click_attribute_27,
mmc_click_attribute_28,
mmc_click_attribute_29,
mmc_click_attribute_30,
mmc_click_attribute_31,
mmc_click_attribute_32,
mmc_click_attribute_33,
mmc_click_attribute_34,
mmc_click_attribute_35,
mmc_click_attribute_36,
mmc_click_attribute_37,
mmc_click_attribute_38,
mmc_click_attribute_39,
mmc_click_attribute_40,
mmc_click_attribute_41,
mmc_click_attribute_42,
mmc_click_attribute_43,
mmc_click_attribute_44,
mmc_click_attribute_45,
mmc_click_attribute_46,
mmc_click_attribute_47,
mmc_click_attribute_48,
mmc_click_attribute_49,
mmc_click_attribute_50,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cm_mmcclick);
 
 
INSERT INTO vfap_retail.cm_pageview (select 
session_id,
cookie_id,
ts,
page,
page_id,
content_category,
content_category_id,
content_category_top,
content_category_bottom,
on_site_search_term,
page_url,
page_referral_url,
site_id,
page_view_attribute_1,
page_view_attribute_2,
page_view_attribute_3,
page_view_attribute_4,
page_view_attribute_5,
page_view_attribute_6,
page_view_attribute_7,
page_view_attribute_8,
page_view_attribute_9,
page_view_attribute_10,
page_view_attribute_11,
page_view_attribute_12,
page_view_attribute_13,
page_view_attribute_14,
page_view_attribute_15,
page_view_attribute_16,
page_view_attribute_17,
page_view_attribute_18,
page_view_attribute_19,
page_view_attribute_20,
page_view_attribute_21,
page_view_attribute_22,
page_view_attribute_23,
page_view_attribute_24,
page_view_attribute_25,
page_view_attribute_26,
page_view_attribute_27,
page_view_attribute_28,
page_view_attribute_29,
page_view_attribute_30,
page_view_attribute_31,
page_view_attribute_32,
page_view_attribute_33,
page_view_attribute_34,
page_view_attribute_35,
page_view_attribute_36,
page_view_attribute_37,
page_view_attribute_38,
page_view_attribute_39,
page_view_attribute_40,
page_view_attribute_41,
page_view_attribute_42,
page_view_attribute_43,
page_view_attribute_44,
page_view_attribute_45,
page_view_attribute_46,
page_view_attribute_47,
page_view_attribute_48,
page_view_attribute_49,
page_view_attribute_50,
search_results_count,
sas_brand_id,
fs_sk,
customer_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cm_pageview);
 
 
INSERT INTO vfap_retail.cm_productview (select session_id,
cookie_id,
ts,
product_name,
product_id,
page_id,
product_category_id,
product_category,
product_category_top,
product_category_bottom,
site_id,
product_view_attribute_1,
product_view_attribute_2,
product_view_attribute_3,
product_view_attribute_4,
product_view_attribute_5,
product_view_attribute_6,
product_view_attribute_7,
product_view_attribute_8,
product_view_attribute_9,
product_view_attribute_10,
product_view_attribute_11,
product_view_attribute_12,
product_view_attribute_13,
product_view_attribute_14,
product_view_attribute_15,
product_view_attribute_16,
product_view_attribute_17,
product_view_attribute_18,
product_view_attribute_19,
product_view_attribute_20,
product_view_attribute_21,
product_view_attribute_22,
product_view_attribute_23,
product_view_attribute_24,
product_view_attribute_25,
product_view_attribute_26,
product_view_attribute_27,
product_view_attribute_28,
product_view_attribute_29,
product_view_attribute_30,
product_view_attribute_31,
product_view_attribute_32,
product_view_attribute_33,
product_view_attribute_34,
product_view_attribute_35,
product_view_attribute_36,
product_view_attribute_37,
product_view_attribute_38,
product_view_attribute_39,
product_view_attribute_40,
product_view_attribute_41,
product_view_attribute_42,
product_view_attribute_43,
product_view_attribute_44,
product_view_attribute_45,
product_view_attribute_46,
product_view_attribute_47,
product_view_attribute_48,
product_view_attribute_49,
product_view_attribute_50,
sas_brand_id,
fs_sk,
customer_id,
sas_product_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cm_productview);
 
 
INSERT INTO vfap_retail.cm_registration (select  session_id,
cookie_id,
registration_id,
new_repeat_buyer,
new_repeat_visitor,
visitor_customer_flag,
registered_city,
registered_state,
registered_country,
registered_zip_code,
gndr,
email_address,
age,
registration_attribute_1,
registration_attribute_2,
registration_attribute_3,
registration_attribute_4,
registration_attribute_5,
registration_attribute_6,
registration_attribute_7,
registration_attribute_8,
registration_attribute_9,
registration_attribute_10,
registration_attribute_11,
registration_attribute_12,
registration_attribute_13,
registration_attribute_14,
registration_attribute_15,
registration_attribute_16,
registration_attribute_17,
registration_attribute_18,
registration_attribute_19,
registration_attribute_20,
registration_attribute_21,
registration_attribute_22,
registration_attribute_23,
registration_attribute_24,
registration_attribute_25,
registration_attribute_26,
registration_attribute_27,
registration_attribute_28,
registration_attribute_29,
registration_attribute_30,
registration_attribute_31,
registration_attribute_32,
registration_attribute_33,
registration_attribute_34,
registration_attribute_35,
registration_attribute_36,
registration_attribute_37,
registration_attribute_38,
registration_attribute_39,
registration_attribute_40,
registration_attribute_41,
registration_attribute_42,
registration_attribute_43,
registration_attribute_44,
registration_attribute_45,
registration_attribute_46,
registration_attribute_47,
registration_attribute_48,
registration_attribute_49,
registration_attribute_50,
last_update_date,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cm_registration);
 
INSERT into vfap_retail.cm_session_first_page_view (select session_id,
cookie_id,
first_ts,
first_referral_url,
first_destination_url,
first_referral_type,
ip_address,
ts,
referral_name,
referral_url,
referral_type,
natural_search_term,
destination_url,
user_agent,
search_engine,
marketing_vendor,
marketing_category,
marketing_placement,
marketing_item,
visitor_ad_impression_id,
sas_brand_id,
fs_sk,
customer_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cm_session_first_page_view);
 
INSERT INTO vfap_retail.cm_session_xref (select 
session_id,
customer_id,
sas_brand_id,
current_timestamp as process_dtm
 from whousep.cm_session_xref);
 
 
INSERT INTO vfap_retail.cmpgn_xref (select  
seq,
offer_category,
email_campaign_category,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cmpgn_xref);
 
INSERT INTO vfap_retail.color (select 
color_code,
color_description,
fs_sk,
sas_brand_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.color);
 
INSERT into vfap_retail.csv_cold_styles_all_2019 
select   style_id,
department_description,
class_description,
sas_style_description,
tnf_sas_product_category,
tot_stores,
total_quantity,
total_revenue,
total_buyer
 from whousep.csv_cold_styles_all_2019;
 
INSERT into vfap_retail.csv_cold_styles_jacket_2019 
select   style_id,
department_description,
class_description,
sas_style_description,
tnf_sas_product_category,
tot_stores,
total_quantity,
total_revenue,
total_buyer
 from whousep.csv_cold_styles_jacket_2019;
 
INSERT into vfap_retail.csv_mw_styles_all_2019 
select   style_id,
department_description,
class_description,
sas_style_description,
tnf_sas_product_category,
tot_stores,
total_quantity,
total_revenue,
total_buyer from whousep.csv_mw_styles_all_2019;


insert into vfap_retail.csv_mw_styles_jacket_2019 
select   style_id,
department_description,
class_description,
sas_style_description,
tnf_sas_product_category,
tot_stores,
total_quantity,
total_revenue,
total_buyer
 from whousep.csv_mw_styles_jacket_2019;
 
insert into vfap_retail.csv_only_mw_styles_all_2019 
select   style_id,
department_description,
class_description,
sas_style_description,
tnf_sas_product_category,
tot_stores,
total_quantity,
total_revenue,
total_buyer
from whousep.csv_only_mw_styles_all_2019;


insert into vfap_retail.csv_only_mw_styles_jacket_2019 
select   style_id,
department_description,
class_description,
sas_style_description,
tnf_sas_product_category,
tot_stores,
total_quantity,
total_revenue,
total_buyer
 from whousep.csv_only_mw_styles_jacket_2019;
 
INSERT INTO vfap_retail.csv_tnf_email_inputs (select 
customer_id,
ssn_md2o_b,
ssn_md2o_p,
ssn_md2o_h,
ssn_md2o_ss,
ssn_md2o_w,
ssn_md2o_ws,
ssn_md2o_f,
ssn_md2c_b,
ssn_md2c_h,
ssn_md2c_ss,
ssn_md2c_w,
ssn_md2c_p,
ssn_md2c_f,
ssn_md2c_ws,
ssn_dsince_o_b,
ssn_dsince_o_p,
ssn_dsince_o_w,
ssn_dsince_o_f,
ssn_dsince_o_h,
ssn_dsince_o_ss,
ssn_dsince_o_ws,
ssn_freq_s_b,
ssn_freq_s_h,
ssn_freq_s_p,
ssn_freq_s_w,
ssn_freq_s_ss,
ssn_freq_s_ws,
ssn_freq_s_f,
ssn_freq_o_b,
ssn_freq_o_p,
ssn_freq_o_h,
ssn_freq_o_f,
ssn_freq_o_ss,
ssn_freq_o_w,
ssn_freq_o_ws,
ssn_freq_c_b,
ssn_freq_c_w,
ssn_freq_c_p,
ssn_freq_c_h,
ssn_freq_c_ss,
ssn_freq_c_f,
ssn_freq_c_ws,
ssn_pct_o_p,
ssn_pct_o_w,
ssn_pct_o_ss,
ssn_pct_o_f,
ssn_pct_o_h,
ssn_pct_o_b,
ssn_pct_o_ws,
ssn_pct_c_h,
ssn_pct_c_b,
ssn_pct_c_w,
ssn_pct_c_p,
ssn_pct_c_ws,
ssn_pct_c_f,
ssn_pct_c_ss,
gen_md2o_f,
gen_md2o_m,
gen_md2c_f,
gen_md2c_m,
gen_dsince_o_f,
gen_dsince_o_m,
gen_freq_s_f,
gen_freq_s_m,
gen_freq_o_f,
gen_freq_o_m,
gen_freq_c_f,
gen_freq_c_m,
gen_pct_o_f,
gen_pct_o_m,
gen_pct_c_f,
gen_pct_c_m,
act_md2o_run,
act_md2o_water,
act_md2o_mtnclm,
act_md2o_bcpkcamp,
act_md2o_trn,
act_md2o_ski,
act_md2o_boxing,
act_md2o_surf,
act_md2o_hik,
act_md2o_snwb,
act_md2o_travel,
act_md2o_yoga,
act_md2c_run,
act_md2c_ski,
act_md2c_water,
act_md2c_trn,
act_md2c_mtnclm,
act_md2c_bcpkcamp,
act_md2c_travel,
act_md2c_hik,
act_md2c_boxing,
act_md2c_yoga,
act_md2c_snwb,
act_md2c_surf,
act_dsince_o_run,
act_dsince_o_ski,
act_dsince_o_trn,
act_dsince_o_mtnclm,
act_dsince_o_bcpkcamp,
act_dsince_o_yoga,
act_dsince_o_boxing,
act_dsince_o_surf,
act_dsince_o_snwb,
act_dsince_o_hik,
act_dsince_o_travel,
act_freq_s_ski,
act_freq_s_run,
act_freq_s_bcpkcamp,
act_freq_s_mtnclm,
act_freq_s_trn,
act_freq_s_water,
act_freq_s_boxing,
act_freq_s_surf,
act_freq_s_snwb,
act_freq_s_hik,
act_freq_s_yoga,
act_freq_s_travel,
act_freq_o_run,
act_freq_o_mtnclm,
act_freq_o_bcpkcamp,
act_freq_o_ski,
act_freq_o_water,
act_freq_o_trn,
act_freq_o_surf,
act_freq_o_yoga,
act_freq_o_travel,
act_freq_o_boxing,
act_freq_o_hik,
act_freq_o_snwb,
act_freq_c_run,
act_freq_c_ski,
act_freq_c_trn,
act_freq_c_bcpkcamp,
act_freq_c_surf,
act_freq_c_boxing,
act_freq_c_mtnclm,
act_freq_c_travel,
act_freq_c_yoga,
act_freq_c_water,
act_freq_c_snwb,
act_freq_c_hik,
act_pct_o_bcpkcamp,
act_pct_o_run,
act_pct_o_ski,
act_pct_o_mtnclm,
act_pct_o_trn,
act_pct_o_boxing,
act_pct_o_surf,
act_pct_o_yoga,
act_pct_o_hik,
act_pct_o_snwb,
act_pct_o_travel,
act_pct_c_ski,
act_pct_c_bcpkcamp,
act_pct_c_mtnclm,
act_pct_c_trn,
act_pct_c_water,
act_pct_c_run,
act_pct_c_travel,
act_pct_c_surf,
act_pct_c_yoga,
act_pct_c_boxing,
act_pct_c_snwb,
act_pct_c_hik,
prs_md2o_new_vipk,
prs_md2o_ma,
prs_md2o_family,
prs_md2o_survey,
prs_md2o_outdoor,
prs_md2o_pe,
prs_md2o_new_cust,
prs_md2o_wishlist,
prs_md2o_rep_cust,
prs_md2o_abncart,
prs_md2o_viprwrd,
prs_md2o_nl,
prs_md2c_ma,
prs_md2c_new_vipk,
prs_md2c_family,
prs_md2c_viprwrd,
prs_md2c_survey,
prs_md2c_wishlist,
prs_md2c_pe,
prs_md2c_nl,
prs_md2c_rep_cust,
prs_md2c_abncart,
prs_md2c_outdoor,
prs_md2c_new_cust,
prs_dsince_o_ma,
prs_dsince_o_new_vipk,
prs_dsince_o_pe,
prs_dsince_o_new_cust,
prs_dsince_o_survey,
prs_dsince_o_outdoor,
prs_dsince_o_family,
prs_dsince_o_wishlist,
prs_dsince_o_rep_cust,
prs_dsince_o_abncart,
prs_dsince_o_viprwrd,
prs_dsince_o_nl,
prs_freq_s_ma,
prs_freq_s_new_vipk,
prs_freq_s_pe,
prs_freq_s_family,
prs_freq_s_new_cust,
prs_freq_s_outdoor,
prs_freq_s_wishlist,
prs_freq_s_survey,
prs_freq_s_viprwrd,
prs_freq_s_nl,
prs_freq_s_rep_cust,
prs_freq_s_abncart,
prs_freq_o_new_vipk,
prs_freq_o_wishlist,
prs_freq_o_new_cust,
prs_freq_o_ma,
prs_freq_o_pe,
prs_freq_o_family,
prs_freq_o_outdoor,
prs_freq_o_viprwrd,
prs_freq_o_rep_cust,
prs_freq_o_abncart,
prs_freq_o_survey,
prs_freq_o_nl,
prs_freq_c_new_vipk,
prs_freq_c_wishlist,
prs_freq_c_ma,
prs_freq_c_family,
prs_freq_c_outdoor,
prs_freq_c_nl,
prs_freq_c_rep_cust,
prs_freq_c_abncart,
prs_freq_c_pe,
prs_freq_c_viprwrd,
prs_freq_c_new_cust,
prs_freq_c_survey,
prs_pct_o_ma,
prs_pct_o_new_vipk,
prs_pct_o_new_cust,
prs_pct_o_nl,
prs_pct_o_family,
prs_pct_o_survey,
prs_pct_o_pe,
prs_pct_o_wishlist,
prs_pct_o_outdoor,
prs_pct_o_rep_cust,
prs_pct_o_abncart,
prs_pct_o_viprwrd,
prs_pct_c_ma,
prs_pct_c_pe,
prs_pct_c_rep_cust,
prs_pct_c_abncart,
prs_pct_c_family,
prs_pct_c_nl,
prs_pct_c_wishlist,
prs_pct_c_new_cust,
prs_pct_c_new_vipk,
prs_pct_c_survey,
prs_pct_c_viprwrd,
prs_pct_c_outdoor,
chnl_md2o_outlet,
chnl_md2o_retail,
chnl_md2o_ecom,
chnl_md2c_outlet,
chnl_md2c_retail,
chnl_md2c_ecom,
chnl_dsince_o_outlet,
chnl_dsince_o_retail,
chnl_dsince_o_ecom,
chnl_freq_s_outlet,
chnl_freq_s_retail,
chnl_freq_s_ecom,
chnl_freq_o_outlet,
chnl_freq_o_retail,
chnl_freq_o_ecom,
chnl_freq_c_outlet,
chnl_freq_c_retail,
chnl_freq_c_ecom,
chnl_pct_o_retail,
chnl_pct_o_outlet,
chnl_pct_o_ecom,
chnl_pct_c_outlet,
chnl_pct_c_retail,
chnl_pct_c_ecom,
pcat_md2o_bcpk,
pcat_md2o_accsr,
pcat_md2o_fw,
pcat_md2o_ins,
pcat_md2o_equip,
pcat_md2o_jkt,
pcat_md2o_mildjkt,
pcat_md2o_rain_wr,
pcat_md2c_jkt,
pcat_md2c_rain_wr,
pcat_md2c_ins,
pcat_md2c_bcpk,
pcat_md2c_equip,
pcat_md2c_accsr,
pcat_md2c_fw,
pcat_md2c_mildjkt,
pcat_dsince_o_bcpk,
pcat_dsince_o_accsr,
pcat_dsince_o_fw,
pcat_dsince_o_ins,
pcat_dsince_o_jkt,
pcat_dsince_o_rain_wr,
pcat_dsince_o_equip,
pcat_dsince_o_mildjkt,
pcat_freq_s_fw,
pcat_freq_s_accsr,
pcat_freq_s_ins,
pcat_freq_s_jkt,
pcat_freq_s_bcpk,
pcat_freq_s_equip,
pcat_freq_s_rain_wr,
pcat_freq_s_mildjkt,
pcat_freq_o_rain_wr,
pcat_freq_o_ins,
pcat_freq_o_jkt,
pcat_freq_o_equip,
pcat_freq_o_accsr,
pcat_freq_o_fw,
pcat_freq_o_mildjkt,
pcat_freq_o_bcpk,
pcat_freq_c_accsr,
pcat_freq_c_fw,
pcat_freq_c_jkt,
pcat_freq_c_rain_wr,
pcat_freq_c_equip,
pcat_freq_c_mildjkt,
pcat_freq_c_ins,
pcat_freq_c_bcpk,
pcat_pct_o_ins,
pcat_pct_o_fw,
pcat_pct_o_accsr,
pcat_pct_o_jkt,
pcat_pct_o_rain_wr,
pcat_pct_o_bcpk,
pcat_pct_o_equip,
pcat_pct_o_mildjkt,
pcat_pct_c_ins,
pcat_pct_c_bcpk,
pcat_pct_c_accsr,
pcat_pct_c_fw,
pcat_pct_c_jkt,
pcat_pct_c_rain_wr,
pcat_pct_c_equip,
pcat_pct_c_mildjkt,
act_dsince_o_water,
act_pct_o_water
from whousep.csv_tnf_email_inputs);

INSERT INTO vfap_retail.csv_vans_zeta_inputs (select  customer_id,
ssn_md2o_bts,
ssn_md2o_fco,
ssn_md2o_hco,
ssn_md2o_hol,
ssn_md2o_spr,
ssn_md2o_sum,
ssn_md2c_bts,
ssn_md2c_fco,
ssn_md2c_hco,
ssn_md2c_hol,
ssn_md2c_spr,
ssn_md2c_sum,
ssn_dsinco_bts,
ssn_dsinco_fco,
ssn_dsinco_hco,
ssn_dsinco_hol,
ssn_dsinco_spr,
ssn_dsinco_sum,
ssn_freq_s_bts,
ssn_freq_s_fco,
ssn_freq_s_hco,
ssn_freq_s_hol,
ssn_freq_s_spr,
ssn_freq_s_sum,
ssn_freq_o_bts,
ssn_freq_o_fco,
ssn_freq_o_hco,
ssn_freq_o_hol,
ssn_freq_o_spr,
ssn_freq_o_sum,
ssn_freq_c_bts,
ssn_freq_c_fco,
ssn_freq_c_hco,
ssn_freq_c_hol,
ssn_freq_c_spr,
ssn_freq_c_sum,
ssn_pct_o_bts,
ssn_pct_o_fco,
ssn_pct_o_hco,
ssn_pct_o_hol,
ssn_pct_o_spr,
ssn_pct_o_sum,
ssn_pct_c_bts,
ssn_pct_c_fco,
ssn_pct_c_hco,
ssn_pct_c_hol,
ssn_pct_c_spr,
ssn_pct_c_sum,
genage_md2o_a,
genage_md2o_k,
genage_md2o_m,
genage_md2o_w,
genage_md2c_a,
genage_md2c_k,
genage_md2c_m,
genage_md2c_w,
genage_dsinco_a,
genage_dsinco_k,
genage_dsinco_m,
genage_dsinco_w,
genage_freq_s_a,
genage_freq_s_k,
genage_freq_s_m,
genage_freq_s_w,
genage_freq_o_a,
genage_freq_o_k,
genage_freq_o_m,
genage_freq_o_w,
genage_freq_c_a,
genage_freq_c_k,
genage_freq_c_m,
genage_freq_c_w,
genage_pct_o_a,
genage_pct_o_k,
genage_pct_o_m,
genage_pct_o_w,
genage_pct_c_a,
genage_pct_c_k,
genage_pct_c_m,
genage_pct_c_w,
act_md2o_skate,
act_md2o_snwb,
act_md2o_surf,
act_md2c_skate,
act_md2c_snwb,
act_md2c_surf,
act_dsinco_skate,
act_dsinco_snwb,
act_dsinco_surf,
act_freq_s_skate,
act_freq_s_snwb,
act_freq_s_surf,
act_freq_o_skate,
act_freq_o_snwb,
act_freq_o_surf,
act_freq_c_skate,
act_freq_c_snwb,
act_freq_c_surf,
act_pct_o_skate,
act_pct_o_snwb,
act_pct_o_surf,
act_pct_c_skate,
act_pct_c_snwb,
act_pct_c_surf,
prs_md2o_artcollab,
prs_md2o_collab,
prs_md2o_event,
prs_md2o_new_arri,
prs_md2o_new_cust,
prs_md2o_reward,
prs_md2o_reengage,
prs_md2o_survey,
prs_md2o_abdn_cart,
prs_md2o_rtn_cust,
prs_md2c_artcollab,
prs_md2c_collab,
prs_md2c_event,
prs_md2c_new_arri,
prs_md2c_new_cust,
prs_md2c_reward,
prs_md2c_reengage,
prs_md2c_survey,
prs_md2c_abdn_cart,
prs_md2c_rtn_cust,
prs_dsinco_artcollab,
prs_dsinco_collab,
prs_dsinco_event,
prs_dsinco_new_arri,
prs_dsinco_new_cust,
prs_dsinco_reward,
prs_dsinco_reengage,
prs_dsinco_survey,
prs_dsinco_abdn_cart,
prs_dsinco_rtn_cust,
prs_freq_s_artcollab,
prs_freq_s_collab,
prs_freq_s_event,
prs_freq_s_new_arri,
prs_freq_s_new_cust,
prs_freq_s_reward,
prs_freq_s_reengage,
prs_freq_s_survey,
prs_freq_s_abdn_cart,
prs_freq_s_rtn_cust,
prs_freq_o_artcollab,
prs_freq_o_collab,
prs_freq_o_event,
prs_freq_o_new_arri,
prs_freq_o_new_cust,
prs_freq_o_reward,
prs_freq_o_reengage,
prs_freq_o_survey,
prs_freq_o_abdn_cart,
prs_freq_o_rtn_cust,
prs_freq_c_artcollab,
prs_freq_c_collab,
prs_freq_c_event,
prs_freq_c_new_arri,
prs_freq_c_new_cust,
prs_freq_c_reward,
prs_freq_c_reengage,
prs_freq_c_survey,
prs_freq_c_abdn_cart,
prs_freq_c_rtn_cust,
prs_pct_o_artcollab,
prs_pct_o_collab,
prs_pct_o_event,
prs_pct_o_new_arri,
prs_pct_o_new_cust,
prs_pct_o_reward,
prs_pct_o_reengage,
prs_pct_o_survey,
prs_pct_o_abdn_cart,
prs_pct_o_rtn_cust,
prs_pct_c_artcollab,
prs_pct_c_collab,
prs_pct_c_event,
prs_pct_c_new_arri,
prs_pct_c_new_cust,
prs_pct_c_reward,
prs_pct_c_reengage,
prs_pct_c_survey,
prs_pct_c_abdn_cart,
prs_pct_c_rtn_cust,
chnl_md2o_retail,
chnl_md2o_ecom,
chnl_md2c_retail,
chnl_md2c_ecom,
chnl_dsinco_retail,
chnl_dsinco_ecom,
chnl_freq_s_retail,
chnl_freq_s_ecom,
chnl_freq_o_retail,
chnl_freq_o_ecom,
chnl_freq_c_retail,
chnl_freq_c_ecom,
chnl_pct_o_retail,
chnl_pct_o_ecom,
chnl_pct_c_retail,
chnl_pct_c_ecom,
pcat_md2o_custom,
pcat_md2o_mte,
pcat_md2o_pnut,
pcat_md2c_custom,
pcat_md2c_mte,
pcat_md2c_pnut,
pcat_dsinco_custom,
pcat_dsinco_mte,
pcat_dsinco_pnut,
pcat_freq_s_custom,
pcat_freq_s_mte,
pcat_freq_s_pnut,
pcat_freq_o_custom,
pcat_freq_o_mte,
pcat_freq_o_pnut,
pcat_freq_c_custom,
pcat_freq_c_mte,
pcat_freq_c_pnut,
pcat_pct_o_custom,
pcat_pct_o_mte,
pcat_pct_o_pnut,
pcat_pct_c_custom,
pcat_pct_c_mte,
pcat_pct_c_pnut,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.csv_vans_zeta_inputs);
 
INSERT INTO vfap_retail.cust (select 
sas_brand_id,
customer_id,
customer_no,
first_name,
last_name,
email_address,
opt_in_flag,
store_no,
language_code,
alpha_key,
gender,
create_source,
landmark_date_a,
create_date,
last_update_date,
sales_associate_no,
head_of_household_flag,
opt_in_date,
segmentation_flag_a,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cust);


INSERT INTO vfap_retail.cust_alt_key (select 
sas_brand_id,
customer_id,
alternate_key,
alternate_key_code,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name 
from whousep.cust_alt_key);


INSERT INTO vfap_retail.cust_attribute (select 
sas_brand_id,
customer_id,
attribute_grouping_code,
attribute_code,
attribute_comment,
attribute_value,
attribute_date,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cust_attribute);
 
 
INSERT INTO vfap_retail.cust_xref (select  sas_brand_id,
old_customer_no,
new_customer_no,
last_update_date,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.cust_xref);
 
INSERT INTO vfap_retail.cust_xref_final (select 
sas_brand_id,
customer_no,
customer_id,
current_timestamp as process_dtm
 from whousep.cust_xref_final);
 
 
INSERT INTO vfap_retail.dept (select 
department_code,
department_short_description,
department_description,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as  from whousep.dept);

INSERT INTO vfap_retail.dim_period (select 
date,
day_of_week,
fiscalweek,
fiscalmonth,
fiscalqtr,
fiscalyear,
prev_date,
prev_day_of_week,
prev_fiscalweek,
prev_fiscalmonth,
prev_fiscalqtr,
prev_fiscalyear,
month_abbr,
week_abbr,
day_type,
day_num
from whousep.dim_period);

INSERT INTO vfap_retail.dq_check (select  program_name,
input_tbl,
date_time,
dq_severity_level,
dq_description,
counts,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.dq_check);
 
 
INSERT INTO vfap_retail.email_xref (select 
email_address,
customer_id,
sas_brand_id,
current_timestamp as process_dtm
 from whousep.email_xref);
 
INSERT INTO vfap_retail.etl_file_received (select 
origination,
received_folder_name,
file_name,
file_ts,
event,chng_ts
 from whousep.etl_file_received);
 
INSERT INTO vfap_retail.etl_file_sent (select
destination,
sent_folder_name,
file_name,
chng_ts 
from whousep.etl_file_sent);

INSERT INTO vfap_retail.etl_file_status (select 
file_name,
event,
event_status,
chng_ts,
folder_path,
sas_dataset_nm,
fs_sk
from whousep.etl_file_status);

INSERT INTO vfap_retail.etl_parm (select 
key1,
key2,
num_value,
char_value,
description,
decimal_val,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.etl_parm);
 
INSERT INTO vfap_retail.etl_rpt_min_max_date (select 
table_name,
column_checked,
min_dt,
max_dt,
total_missing_dates,
total_cnt,
sas_brand_id,
current_timestamp as process_dtm
 from whousep.etl_rpt_min_max_date);
 
 
INSERT INTO vfap_retail.etl_rpt_missing_date (select table_name,
sas_brand_id,
missing_date,
current_timestamp as process_dtm
 from whousep.etl_rpt_missing_date);
 
 
INSERT INTO vfap_retail.event_xref (select attribute_grouping_code,
attribute_code,
attribute_description,
"primary",
secondary1,
secondary2,
secondary3,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.event_xref);
 
 
INSERT INTO vfap_retail.experian_behavior (select  customer_no,
first_name,
last_name,
email_address,
mailresponder_indiv,
multicodmresp_hh,
multicategorybuyer,
dmcat_giftgadget,
dmcat_collspcfood,
dmcat_books,
dmcat_gardenfarm,
dmcat_craftshobbies,
dmcat_femaleorient,
dmcat_maleorient,
dmcat_upscale,
dmcat_general,
magbyrcat_healthfit,
magbyrcat_culinary,
magbyrcat_gardenfarm,
magbyrcat_religious,
magbyrcat_malesport,
magbyrcat_female,
magbyrcat_familygen,
contribcat_general,
contribcat_health,
contribcat_political,
contribcat_religious,
sweepstakes,
do_it_yourselfers,
news_financial,
photography,
mailrespond_oddsends,
mailrespond_misc,
political_affiliation,
firsttimehmebuyr_enh,
interest_in_golf,
contrib_to_charities,
pet_enthusiast,
z_culturalarts,
mail_order_buyer,
z_int_in_fitness,
z_int_in_outdoors,
z_int_in_travel,
z_investors,
presence_of_auto,
presence_creditcard,
z_int_gardening,
z_int_crafts,
z_collectors,
z_cruise_enthusiasts,
z_int_sports,
z_int_gourmet_cook,
z_sweepstakes_gambling,
z_int_politics,
z_int_music,
z_int_reading,
z_childparentingprod,
z_do_it_yourselfer,
z_self_improve,
z_int_religion,
z_grandparent,
z_int_clothing,
z_donate_environment,
z_investmutualfunds,
z_weight_conscious,
z_mailordermultibuyer,
z_pres_premiumcc,
z_dog_enthusiasts,
z_cat_enthusiasts,
z_healthy_living,
z_int_automobile,
z_int_skiing,
z_int_boating,
z_present_cellphone,
z_comm_connectivity,
z_comp_peripherals,
z_hi_tech_owner,
z_homedecor_furnish,
z_homeenter_tv_video,
z_kitchaidsmapplianc,
z_mailorder_musicvideo,
z_mailorder_booksmags,
z_mailorderclothshoe,
z_mailorder_insfin,
z_mailorder_gifts,
z_mailorder_garden,
z_mailorder_jewelcos,
z_music_classopera,
z_music_country,
z_music_christian,
z_music_rock,
z_interntonlne_subsc,
z_photography,
z_pur_via_online,
z_int_afflulifestyle,
z_domestic_traveler,
z_foreign_traveler,
z_contactlenswearer,
z_prescrip_druguser,
z_int_videodvd,
z_active_military,
z_inactive_military,
morbank_dedcathit,
morbank_nondedcathit,
political_affil_2,
political_affil_3,
political_affil_4,
political_affil_5,
political_affil_6,
political_affil_7,
political_affil_8,
through_the_mail,
other_collectibles,
art_antiques,
stamps_coins,
dolls,
figurines,
sports_memorabilia,
cooking,
baking,
cooking_weightcons,
wine_appreciation,
cooking_gourmet,
crafts,
knitting_needlework,
quilting,
sewing,
woodworking,
losing_weight,
vitamin_supplements,
health_naturalfoods,
hobby_photography,
hobby_gardening,
home_workshop_diy,
cars_auto_repair,
bird_watching,
self_improvement,
christian_gospel,
r_and_b,
jazz_newage,
classical,
rock_n_roll,
country,
music_general,
other_music,
best_selling_fiction,
bible_religious,
childrensreading,
computer,
cooking_culinary,
country_lifestyle,
entertainment_people,
fashion,
history,
interior_decorating,
medical_health,
military,
mystery,
naturalhlth_remedies,
romance,
science_fiction,
science_technology,
sports_reading,
worldnews_politics,
book_reader,
animal_welfare_socl,
environment_wildlife,
political_conserve,
political_liberal,
religious_socialconc,
children,
veterans,
health_social_conc,
other_social_conc,
sportsrec_baseball,
sportsrec_basketball,
sportsrec_hockey,
sportsrec_camp_hike,
sportsrec_hunting,
sportsrec_fishing,
sportsrec_nascar,
sportsrec_per_fitexr,
sportsrec_scuba_dive,
sportsrec_football,
sportsrec_golf,
sportsrec_snowskibrd,
sportsrec_boat_sail,
sportsrec_walking,
sportsrec_cycling,
sportsrec_motorcycle,
sportsrec_run_jog,
sportsrec_soccer,
sportsrec_swim,
playsports_general,
sweepstakes2,
lotteries,
casino_gambling,
cruise,
international,
domestic,
time_share,
recreational_vehicle,
enjoy_rv_travel,
business_travel,
personal_travel,
own_computer,
use_internet_service,
useinternetdsl_hspd,
plan_to_buy_computer,
cell_phone,
compact_disc_player,
dvd_player,
satellite_dish,
digital_camera,
hdtv,
int_electronics,
personal_data_asst,
video_camera,
video_game_system,
arts_int_culturlarts,
business_finance,
childrens_magazines,
computer_electronics,
crafts_games_hobbies,
fitness,
food_wine_cooking,
gardening_magazines,
hunting_fishing,
mens,
music,
parenting_babies,
sports_magazines,
subscription,
travel,
womens,
currentevents_news,
have_leased_vehicle,
havepurchasedvehicle,
book_club,
music_club,
amer_express_premium,
amer_express_regular,
discover_premium,
discover_regular,
othercard_premium,
othercard_regular,
store_retail_regular,
visa_regular,
mastercard_regular,
humanitarian,
buyprerecrded_videos,
watch_cable_tv,
watch_videos,
cds_moneymkt_current,
iras_current,
iras_future_interest,
life_insur_current,
mutual_funds_current,
mutualfunds_future,
otherinvestmt_curr,
otherinvestmt_future,
real_estate_current,
real_estate_future,
stocks_bonds_current,
stocks_bonds_future,
proud_grandparent,
purchase_via_internet,
active_military_mbr,
vetern,
own_a_cat,
own_a_dog,
own_a_pet,
shop_by_internet,
shop_by_mail,
shop_by_catalog,
apparel,
computerorelctronics,
books_music,
home_garden,
sports_related,
big_tall,
mailorder_books_mag,
mailorder_clothing,
mailorder_gardening,
mailorder_gift,
mailorder_jewel_cosm,
mailorder_music_vid,
mailorder_child_prod,
int_amuseparkvisit,
int_zoo_visit,
int_coffeeconnoisseu,
int_winelovers,
int_doityourselfers,
int_homeimprve_spndr,
hunting_enthusiasts,
buyer_laptopowner,
buyer_secursysowner,
buyer_tabletowner,
buyer_couponuser,
buyer_luxuryshopper,
buyer_yngadultcloth,
buyer_supercenter,
buyer_warehouseclub,
aarp_members,
life_insur_policy,
medical_policy,
medicare_policy,
digital_magnewspaper,
attnds_educationprog,
video_gamer,
mlb_enthusiast,
nascar_enthusiast,
nba_enthusiast,
nfl_enthusiast,
nhl_enthusiast,
pga_tour_enthusiast,
politicaltv_liberal,
politictv_libcomedy,
politicaltv_conserva,
eats_family_rest,
eats_fast_food,
canoeing_kayaking,
int_play_golf,
presence_automobile,
loyalty_card_user,
luxuryhomegood_shop,
union_member,
have_retirement_plan,
online_trading,
have_grandchildren,
nondept_store_makeup,
int_gourmet_cooking,
int_cat_owner,
int_dog_owner,
int_arts_crafts,
int_scrapbooking,
int_cultural_arts,
hobbies_gardening,
int_photography,
int_book_reader,
int_ebook_reader,
int_audiobk_listener,
int_pet_enthusiast,
int_music_download,
int_music_streaming,
int_avid_runners,
int_outdoor_enthusia,
int_fishing,
int_snowsports,
int_boating,
int_playshockey,
int_plays_soccer,
int_plays_tennis,
int_sportsenthusiast,
int_healthy_living,
int_fitnessenthusias,
int_on_a_diet,
int_weight_conscious,
buyer_highendspirits,
int_casinogambling,
int_swpstakeslottery,
hifreq_business_trvl,
hifreq_cruise_enthus,
hifreq_domestic_vac,
hifreq_foreign_vac,
freq_flyer_prg_mbr,
hotelguest_loyaprg,
contrib_charities,
contrib_artsculture,
contrib_education,
contrib_health,
contrib_political,
contrib_prvt_found,
contrib_volunteering,
debit_card_user,
corp_credit_crd_user,
maj_credit_crd_user,
prem_credit_crd_user,
credit_card_user,
store_creditcrd_user,
brokerage_acct_owner,
active_investor,
mutual_fund_investor,
deptstore_makeupuser,
int_christian_music,
int_classical_music,
int_country_music,
int_music,
int_oldies_music,
int_rock_music,
int_80s_music,
int_hiphopmusic,
int_alternativemusic,
int_jazz_music,
int_pop_music,
interest_in_religion,
military_active,
military_inactive,
working_couples,
poc_0_3_yrs_gender,
poc_4_6_yrs_gender,
poc_7_9_yrs_gender,
poc_10_12_yrs_gender,
poc_13_15_yrs_gender,
poc_16_18_yrs_gender,
discret_spend_level,
discret_spend_score,
p1_birthdt_indiv,
p1_combage_indiv,
p1_gender_indiv,
p1_marital_status,
recip_reliability_cd,
p1_pertype_indiv,
combined_homeowner,
dwelling_type,
length_of_residence,
dwellingunit_size_cd,
number_child_ltet18,
nbr_adults_in_hh,
p2_person_type,
p2_name_first,
p2_name_mid_init,
p2_name_last,
p2_name_title,
p2_name_surnamesffx,
p2_gender_cd,
p2_combined_age,
p2_birthdt_ccyymm,
p3_person_type,
p3_name_first,
p3_name_mid_init,
p3_name_last,
p3_name_title,
p3_name_surnamesffx,
p3_gender_cd,
p3_combined_age,
p3_birthdt_ccyymm,
p4_person_type,
p4_name_first,
p4_name_mid_init,
p4_name_last,
p4_name_title,
p4_name_surnamesffx,
p4_gender_cd,
p4_combined_age,
p4_birthdt_ccyymm,
p5_person_type,
p5_name_first,
p5_name_mid_init,
p5_name_last,
p5_name_title,
p5_name_surnamesffx,
p5_gender_cd,
p5_combined_age,
p5_birthdt_ccyymm,
p6_person_type,
p6_name_first,
p6_name_mid_init,
p6_name_last,
p6_name_title,
p6_name_surnamesffx,
p6_gender_cd,
p6_combined_age,
p6_birthdt_ccyymm,
p7_person_type,
p7_name_first,
p7_name_mid_init,
p7_name_last,
p7_name_title,
p7_name_surnamesffx,
p7_gender_cd,
p7_combined_age,
p7_birthdt_ccyymm,
p8_person_type,
p8_name_first,
p8_name_mid_init,
p8_name_last,
p8_name_title,
p8_name_surnamesffx,
p8_gender_cd,
p8_combined_age,
p8_birthdt_ccyymm,
p1_occupation,
p1_occupation_grp,
p1_education,
presofchild_age_0_3,
presofchild_age_4_6,
presofchild_age_7_9,
presofchild_age10_12,
presofchild_age13_15,
presofchild_age16_18,
presofchild_age_0_18,
home_business_ind,
p1_businessownerflg,
est_curr_home_value,
multiple_realty_prop,
mosaic_household,
est_household_income,
p1_retail_shoppers,
consumview_prfitscr,
cs_combined,
cs_clothing,
cs_entertainment,
cs_travel,
retail_demand_20200,
retail_demand_20220,
retail_demand_20240,
retail_demand_20260,
retail_demand_20530,
retail_demand_20580,
retail_demand_448,
retail_demand_4481,
retail_demand_44811,
retail_demand_44812,
retail_demand_44813,
retail_demand_44814,
retail_demand_44815,
retail_demand_44819,
retail_demand_451,
retail_demand_4511,
retail_demand_45111,
avg_scorex_plus,
median_scorex_plus,
badvsgood_credit_seg,
scps_avg_taps_spend,
scpsavg_taps_payrate,
online_apparel,
online_shoes,
online_outdrsftgoods,
online_outdrhrdgoods,
ltd_best_recency,
ltd_total_dollars,
ltd_avg_dollar_pur,
ltc_credit_pur,
ltd_purchase_freq,
month_24_credit_pur,
month_24_recency_cd,
month_24_freq_cd,
month_24_dollar_cd,
month_24_avgdollarcd,
w_hiend_apparelrecen,
w_hiend_apparelfreq,
w_hiend_appareldolla,
w_hiend_apparelscore,
w_mid_apparelrecen,
w_mid_apparelfreq,
w_mid_appareldolla,
w_mid_apparelscore,
w_low_apparelrecen,
w_low_apparelfreq,
w_low_appareldolla,
w_low_apparelscore,
w_cas_apparelrecen,
w_cas_apparelfreq,
w_cas_appareldolla,
w_cas_apparelscore,
w_plus_apparelrecen,
w_plus_apparelfreq,
w_plus_appareldolla,
w_plus_apparelscore,
w_athle_apparelrecen,
w_athle_apparelfreq,
w_athle_appareldolla,
w_athle_apparelscore,
m_cas_apparelrecen,
m_cas_apparelfreq,
m_cas_appareldolla,
m_cas_apparelscore,
child_apparelrecen,
child_apparelfreq,
child_appareldolla,
child_apparelscore,
active_outdoor_recen,
active_outdoor_freq,
active_outdoor_dolla,
active_outdoor_score,
x_snowsports_recen,
x_snowsports_freq,
x_snowsports_dolla,
x_snowsports_score,
mth_0_3_trans_freq,
mth_0_3_trans_dollar,
mth_4_6_trans_freq,
mth_4_6_trans_dollar,
mth_7_9_trans_freq,
mth_7_9_trans_dollar,
mth_10_12_trans_freq,
mth_10_12_trans_doll,
mth_13_18_trans_freq,
mth_13_18_trans_doll,
mth_19_24_trans_freq,
mth_19_24_trans_doll,
most_recent_ordr_chan,
tt_brick_mortar,
tt_online_midhigh,
tt_e_tailer,
tt_online_discount,
tt_onlinebid_mrktplc,
tt_emailengagement,
p1_tt_emailengagemnt,
p2_tt_emailengagemnt,
p3_tt_emailengagemnt,
p4_tt_emailengagemnt,
p5_tt_emailengagemnt,
p6_tt_emailengagemnt,
p7_tt_emailengagemnt,
p8_tt_emailengagemnt,
tt_broadcast_cabletv,
tt_directmail,
tt_internetradio,
tt_mobile_display,
tt_mobile_video,
tt_online_video,
tt_online_display,
tt_online_streamtv,
tt_satelliteradio,
tt_buyamerican,
tt_showmethemoney,
tt_gowiththeflow,
tt_notimelikepresent,
tt_nvrshowupemptyhan,
tt_ontheroadagain,
tt_lookatmenow,
tt_stopsmellroses,
tt_workhardplayhard,
tt_pennysavedearned,
tt_its_all_in_name,
ethnicinsight_flag,
ethnicity_detail,
language,
religion,
e_tech_group,
country_of_origin,
totalenhanmatchtype,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.experian_behavior);
 
 
INSERT INTO vfap_retail.experian_bronze (select 
cass_addresstypecode,
cass_addresstypestring,
cass_results,
email_address,
opt_in_flag,
mail_opt_in_flag,
personidnumber,
persontype,
fullname,
middleinitialv2,
surname,
namesuffix,
nameprefix,
gender,
combinedage,
educationmodel,
maritalstatus,
occupationgroupv2,
householdpersonnumber,
firstnamelastname,
addressid,
fipsstatecode,
stateabbreviation,
fipszipcode,
zip4,
deliverypointcode,
carrierroute,
shortcityname,
cityname,
housenumber,
predirection,
streetname,
streetsuffix,
postdirection,
unitdesignator,
unitdesignatornumber,
primaryaddress,
secondaryaddress,
fipscountycode,
countyname,
cvmm_lat,
cvmm_lon,
matchlevelforgeodata,
timezone,
livingunitid,
phone_specialusagephone,
phone_number2,
dwellingunitsize,
dwellingtype,
hmownercombinedhmownerrenter,
esthouseholdincomev5,
ncoamoveupdatecode,
ncoamoveupdatedate,
mailresponder,
lengthofresidence,
numberofpersonsinlivingunit,
numberofadultsinlivingunit,
ruralurbancountysizecode,
activitydate,
morbankupscalemerchandisebuyer,
morbankmalemerchandisebuyer,
morbankfemalemerchandisebuyer,
morbkcraftshobbymerch_isebuyer,
morbankgardeningfarmingbuyer,
morbankbookbuyer,
morbkcollectspecialfoodsbuyer,
morbankgiftsandgadgetsbuyer,
morbankgeneralmerchandisebuyer,
morbkfamily_generalmagazine,
morbankfemaleorientedmagazine,
morbankmalesportsmagazine,
morbankreligiousmagazine,
morbkgardeningfarmingmagazine,
morbkculinaryinterestsmagazine,
morbkhealth_fitnessmagazine,
morbankdoityourselfers,
morbanknewsandfinancial,
morbankphotography,
morbankopportunityseekersandce,
morbankreligiouscontributor,
morbankpoliticalcontributor,
morbkhealth_inscontributor,
morbankgeneralcontributor,
morbankmiscellaneous,
morbankoddsandends,
morbankdedupedcategoryhitcount,
morbknondedupedcategoryhitcnt,
mortgagehmpurhmpurprice,
mortgagehmpurhmpurdt,
propertyrealtyhomeyearbuilt,
householdcomposition,
corebasedstatisticalareascbsa,
corebasedstatisticalareatype,
childrenage018version3,
phone_activitydate,
census2010tractandblockgroup,
capeagepopmedianage,
capeagepop017,
capeagepop1899,
capeagepop6599,
capebuilthumedianhsngunitage,
capechildhhwithpersonslt18,
capechildhhmcfamwprsnslt18,
capechildhhmcfamwoprsnslt18,
capednstyprsnsperhhforpopinhh,
capeeducispsa,
capeeducispsadecile,
capeeducpop25medianeduattained,
capeethnicpopwhiteonly,
capeethnicpopblackonly,
capeethnicpopasianonly,
capeethnicpophispanic,
capehomvaloohumedianhomevalue,
capehhsizehhaveragehldsize,
capehustrhumobilehome,
capeincfamilyincstatedecile,
capeinchhmedianfamilyhldincome,
capelanghhspanishspeaking,
capetenancyocchuowneroccupied,
capetenancyocchurenteroccupied,
capetyphhmarriedcouplefamily,
mosaichousehold,
cvmacromatchgroup,
cvmacromatchlevel,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
from whousep.experian_bronze);
 
INSERT INTO vfap_retail.experian_gold (select customer_id,
customer_no,
first_name,
last_name,
i1mailresponderindiv,
multicodirectmailresphh,
multibuyermin551551,
giftgadgetdmmercbyrcat,
colspcfooddmmercbyrcat,
booksdmmercbyrcat,
gardenfarmdmmercbyrcat,
craftshobbiedmmercbyrcat,
femaleorientdmmercbyrcat,
maleorientdmmercbyrcat,
upscaledmmercbyrcat,
generaldmmercbyrcat,
healthfitnessmagbyrcat,
culinaryintmagbuyer,
gardenfarmingmagbyrcat,
religiousmagbyrcat,
malesportorienmagbyrcat,
femaleorientmagbyrcat,
familygeneralmagbyrcat,
generalcontribtrcat,
healthinstcontribtrcat,
politicalcontribtrcat,
religiouscontribtrcat,
sweepstakes,
doityourselfers,
newsfinancial,
photography,
oddsendsmailrespondr,
miscmailresp,
politicalaffiliation,
firsttimehomebuy,
interestingolf,
contributestocharities,
petenthusiast,
interestinculturalarts,
purchasedthroughthemail,
interestinfitness,
interestintheoutdoors,
interestintravel,
investors,
presenceofautomobile,
presenceofcreditcard,
interestingardening,
interestincrafts,
collectors,
cruiseenthusiasts,
interestinsports,
interestingourmetcooking,
sweepstakesgambling,
interestinpolitics,
interestinmusic,
interestinreading,
childrenparentingproducts,
doityourselfer,
selfimprovement,
interestinreligion,
grandparent,
interestinclothing,
donatesenvironmentalcauses,
investsmutualfundsannuities,
weightconscious,
mailordermultibuyer,
presenceofpremiumcreditcard,
dogenthusiasts,
catenthusiasts,
healthyliving,
interestinautomotive,
interestinskiing,
interestinboating,
presenceofcellphone,
communicationconnectivity,
computersperipherals,
hitechowner,
homedecoratingfurnishing,
homeentertainmenttvvideo,
kitchenaidssmallappliances,
mailorderbuyermusicvideo,
mailorderbuybooksmagazines,
mailorderbuyclothingshoes,
mailorderbuyinsfinance,
mailorderbuyergifts,
mailorderbuyergardening,
mailorderbuyerjewelrycosm,
classicaloperabigbandmusic,
countrymusic,
christianmusic,
rockmusic,
internetonlinesubscriber,
interestinphotography,
purchaseviaonline,
interestinaffluentlifestyle,
domestictraveler,
foreigntraveler,
contactlensewearer,
prescriptiondruguser,
interestinvideosdvd,
activemilitary,
inactivemilitary,
morbankdedcategoryhitcnt,
morbanknondedcategoryhit,
politicalaffiliation2,
politicalaffiliation3,
politicalaffiliation4,
politicalaffiliation5,
politicalaffiliation6,
politicalaffiliation7,
politicalaffiliation8,
throughthemail,
othercollectibles,
artantiques,
stampscoins,
dolls,
figurines,
sportsmemorabilia,
cooking,
baking,
cookingweightconscience,
wineappreciation,
cookinggourmet,
crafts,
knittingneedlework,
quilting,
sewing,
woodworking,
losingweight,
includevitaminsupplements,
healthandnaturalfoods,
photographyhobbies,
gardeninghobbies,
homeworkshopdiy,
carsandautorepair,
birdwatching,
self_improvement,
christiangospel,
randb,
jazznewage,
classical,
rocknroll,
country,
musicingeneral,
othermusic,
bestsellingfiction,
bibledevotionalreligious,
childrensreading,
computer,
cookingculinary,
countrylifestyle,
entertainmentpeople,
fashion,
history,
interiordecorating,
medicalhealth,
military,
mystery,
naturalhealthremedies,
romance,
sciencefiction,
sciencetechnology,
sportsreading,
worldnewspolitics,
bookreader,
animalwelfaresoclcauseconc,
environmentwildlife,
politicalconservative,
politicalliberal,
religioussocialcauseconc,
children,
veterans,
healthsocialcausesconcern,
othersocialcausesconcern,
baseball,
basketball,
hockey,
campinghiking,
hunting,
fishing,
nascar,
personalfitnessexercise,
scubadiving,
football,
golf,
snowskiingboarding,
boatingsailing,
walking,
cycling,
motorcycles,
runningjogging,
soccer,
swimming,
playsportsingeneral,
sweepstakes2,
lotteries,
casinogambling,
cruise,
international,
domestic,
timeshare,
recreationalvehicle,
wouldenjoyrvtravel,
businesstravel,
personaltravel,
owncomputer,
useinternetservice,
useinternetsvcdslhighspd,
plantobuycomputer,
cellphone,
compactdiscplayer,
dvdplayer,
satellitedish,
digitalcamera,
hdtv,
interestinelectronics,
pesonaldataassistantpda,
videocamera,
videogamesystem,
interestincultrualarts,
businessandfinance,
childrensmagazines,
computerelectronics,
craftsgamesandhobbies,
fitness,
foodwinecooking,
gardeningmagazines,
huntingandfishing,
mens,
music,
parentingbabies,
sportsmagazines,
subscription,
travel,
womens,
currenteventsnews,
haveleasedavehicle,
havepurchasedavehicle,
bookclub,
musicclub,
americanexpresspremium,
americanexpressregular,
discoverpremium,
discoverregular,
othercardpremium,
othercardregular,
storeorretailregular,
visaregular,
mastercardregular,
humanitarian,
buyprerecordedvideos,
watchcabletv,
watchvideos,
cdsmoneymarketcurrently,
irascurrently,
irasfutureinterest,
lifeinsurancecurrently,
mutualfundscurrently,
mutualfundsfutureinterest,
otherinvestmentscurrently,
otherinvestmtfutureinteres,
realestatecurrently,
realestatefutureinterest,
stocksbondscurrently,
stocksbondsfutureinterest,
proudgrandparent,
purchaseitemsviatheinterne,
activemilitarymember,
vetern,
ownacat,
ownadog,
ownapet,
byinternet,
bymail,
bycatalog,
apparel,
computerorelectronics,
booksandmusic,
homeandgarden,
sportsrelated,
bigtall,
mailorderbooksmag,
mailorderclothing,
mailordergardening,
mailordergift,
mailorderjewelrycosmetics,
mailordermusicvideos,
mailorderchildrensproducts,
actintamusementparkvisit,
actintzoovisit,
actintcoffeeconnoisseurs,
actintwinelovers,
actintdoityourselfers,
actinhomeimprov,
actinthuntingenthusiasts,
buyerlaptopowners,
buyersecuritysysowners,
buyertabletowners,
buyercouponusers,
buyerluxurystoreshop,
buyeryoungadultclothshop,
buyersupercentershop,
buywarehclubmember,
membershipsaarpmembers,
lifestylelifeinspolicy,
lifestylemedicalpolicy,
lifestylemedicarepolicy,
actindigimagnewspaper,
actinattendeduprog,
actintvideogamer,
actintmlbenthusiast,
actintnascarenthusiast,
actintnbaenthusiast,
actintnflenthusiast,
actintnhlenthusiast,
actintpgatourenthusiast,
actintpoliticaltvliberal,
actinpolitvlibcom,
actinpolitvcons,
actineatsfamrestrnt,
actinteatsfastfood,
actintcanoeingkayaking,
actintplaygolf,
buyautomobile,
buyerloyaltycarduser,
buyerluxhomegoodshop,
membershipsunionmember,
investhaveretirementplan,
investonlinetrading,
havegrandchild,
buyernondeptstoremakeup,
actintgourmetcooking,
actintcatowners,
actintdogowners,
actintartsandcrafts,
actintscrapbooking,
actintculturalarts,
hobbiesgardening,
actintphotography,
actintbookreader,
actintebookreader,
actintaudiobooklistener,
actintpetenthusiast,
actintmusicdownload,
actintmusicstreaming,
actintavidrunners,
actintoutdoorenthusiast,
actintfishing,
actintsnowsports,
actintboating,
actintplayshockey,
actintplayssoccer,
actintplaystennis,
actintsportsenthusiast,
actinthealthyliving,
actintfitnessenthusiast,
actintonadiet,
actintweightconscious,
buyhighendspiritdrink,
actintcasinogambling,
actintsweepstakeslottery,
stylehighfreqbusintrvl,
stylehighfreqcruise,
stylehighfreqdomesticvac,
stylehighfreqforeignvac,
stylefrequentflyerprgmbr,
stylehotelloyaltyprg,
donorcontribtocharities,
donorcontribarts,
donorcontribtoeducation,
donorcontribtohealth,
donorcontribtopolitical,
donorcontribtoprvtfound,
donorcontribvolunt,
findebitcarduser,
fincorpcreditcardusr,
finmajorcreditcarduser,
finpremiumcreditcarduser,
fincreditcarduser,
finstorecreditcarduser,
invbrokerageaccountowner,
invactiveinvor,
invmutualfundinvor,
buyerdeptstoremakeupuser,
actintchristianmusic,
actintclassicalmusic,
actintcountrymusic,
actintmusic,
actintoldiesmusic,
actintrockmusic,
actint80smusic,
actinthiphopmusic,
actintalternativemusic,
actintjazzmusic,
actintpopmusic,
lifestyleintinreligion,
lifestylemilitaryactive,
lifestylemilitaryinactive,
workingcouples,
poc03yrsoldgenderv3,
poc46yrsoldgenderv3,
poc79yrsoldgenderv3,
poc1012yrsoldgenderv3,
poc1315yrsoldgenderv3,
poc1618yrsoldgenderv3,
discretionaryspendestlevel,
discretspendestscore,
actinteatsfamilyrestaurant,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm
from whousep.experian_gold);
 
 
INSERT INTO vfap_retail.farnorthern_style (select department_code,
department_description,
class_code,
class_description,
style_id,
vendor_style,
style_description,
vendor_cd_4,
vendor_cd_6,
cnodeid,
short_name,
long_name,
style_description_short,
style_description_long,
product_line,
sbu,
series,
newconsumersegmentterritory,
newendusesport,
newproductcollectionfamily,
tnf___clm_description_for_sas
 from whousep.farnorthern_style);
 
 
INSERT INTO vfap_retail.first_name_gender_prob (select name,
prob_gender
 from whousep.first_name_gender_prob);
 
 
INSERT INTO vfap_retail.loyalty_xref (select 
customer_id,
loya_id,
current_timestamp as process_dtm
 from whousep.loyalty_xref);
 
 
INSERT INTO vfap_retail.productxref (select 
sas_brand_id,
product_code,
style_id,
color_code,
primary_size_label,
secondary_size_label,
primary_size_code,
secondary_size_code,
fs_sk,
current_timestamp as process_dtm
 from whousep.productxref);
 
 
INSERT INTO vfap_retail.rainwear_style (select  style_id,
style_description,
department_code,
department_description,
class_code,
class_description,
territory,
activity,
vendor_style,
vendor_cd_4,
vendor_cd_6,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from rainwear_style);
 

INSERT INTO vfap_retail.region (select 
region_code,
region_name,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.region);


INSERT INTO vfap_retail.score_stat_history (select 
model,
min_score,
max_score,
high_cutoff,
low_cutoff,
dt,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.score_stat_history);
 
 
INSERT INTO vfap_retail.sl_challenge_resp (select challenge_id,
member_id,
challenge_name,
challenge_label,
response,
challenge_status,
sl_activity_ts,
sl_type,
sl_subtype,
sl_context,
sl_metric,
sl_value,
sl_client,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.sl_challenge_resp);
 
 INSERT INTO vfap_retail.sl_members (select member_id,
email,
first_name,
last_name,
mailing_street,
mailing_city,
mailing_state,
mailing_postal_code,
mailing_country,
birthdate,
mobile_phone,
member_since,
receive_sms_offers,
receive_e_statements,
suspend_email,
suspend_email_date,
suspend_email_cause,
referrer_id,
last_active_at,
deactivated,
integration_id,
test_member,
visitor,
card_id,
created_at,
sl_contest,
sl_prize,
sl_referral,
point,
points_earned_total,
points_redeemed_total,
points_expired_total,
source,
sl_challenge,
sl_push,
crmnumber,
sl_login,
employee,
sl_cancel_earn,
tenure,
sl_adjust_redeem,
shoe_size,
sl_member_attribute,
sl_offer,
store_number,
sl_adjust_earn,
mailing_street2,
sl_cancel_redeem,
beta_allowed,
sl_survey,
sl_view,
has_device,
sl_reward,
sl_member_confirm,
confirmed_at,
sl_email,
sl_post,
interests,
receive_personalized_offers,
sl_member_preference,
sl_expire,
sl_purchase,
sl_visitor_sign_up,
employee_number,
shoe_gender,
source_campaign,
sl_sign_up,
test_group,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.sl_members);
 
INSERT INTO vfap_retail.sl_message_resp (select sl_member_id,
message_id,
label,
message_action,
sl_activity_ts,
sl_type,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.sl_message_resp);
 
INSERT INTO vfap_retail.sl_orders (select sl_activity_ts,
sl_type,
sl_member_id,
sl_context,
sl_subtype,
sl_parent_id,
sl_metric,
sl_value,
sl_integration_id,
sl_location,
earn_type,
sl_tz,
sl_order_status,
sl_transaction_id,
sl_employee_id,
sl_subtotal,
sl_overall_discount,
sl_item_count,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.sl_orders);
 
INSERT INTO vfap_retail.sl_reward_resp (select sl_activity_ts,
sl_type,
sl_member_id,
sl_context,
sl_subtype,
sl_label,
sl_parent_id,
sl_parent_name,
sl_metric,
sl_value,
sl_creator_type,
sl_client,
sl_status,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from sl_reward_resp);
 
INSERT INTO vfap_retail.snowsports_style (select  department_code,
department_description,
class_code,
class_description,
style_id,
vendor_style,
style_description,
vendor_cd_4,
vendor_cd_6,
cnodeid,
short_name,
long_name,
style_description_short,
style_description_long,
product_line,
sbu,
series,
newconsumersegmentterritory,
newendusesport,
newproductcollectionfamily,
tnf___clm_description_for_sas,
snowsports_flag,
snowsports_subsegment
 from whousep.snowsports_style);
 
 
INSERT INTO vfap_retail.store (select 
store_no,
store_name,
store_grouping_code_a,
store_address_1,
store_address_2,
store_address_3,
store_address_4,
store_post_code,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.store);
 
INSERT INTO vfap_retail.string_pos_xref (select 
group_code,
col_name,
string_pos,
pos_label,
pos_label_desc,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.string_pos_xref);
 
 INSERT INTO vfap_retail.style (select 
style_id,
vendor_code,
class_code,
subclass_code,
vendor_style,
style_aka,
style_description,
retail,
cost,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.style);
 
 INSERT INTO vfap_retail.style_xref_clean (select  department_code,
department_description,
class_code,
class_description,
style_id,
vendor_style,
style_description,
vendor_cd_4,
vendor_cd_6,
cnodeid,
short_name,
long_name,
style_description_short,
style_description_long,
product_line,
sbu,
series,
newconsumersegmentterritory,
newendusesport,
newproductcollectionfamily,
tnf___clm_description_for_sas,
tnf_sas_product_category,
product_gender,
product_age_group,
sas_style_description,
gender_age,
tb_flag,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.style_xref_clean);
 
 
INSERT INTO vfap_retail.summit_style_ids_new (select  department_code,
department_description,
class_code,
class_description,
style_id,
vendor_style,
style_description,
vendor_cd_4,
vendor_cd_6,
cnodeid,
short_name,
long_name,
style_description_short,
style_description_long,
product_line,
sbu,
series,
newconsumersegmentterritory,
newendusesport,
newproductcollectionfamily,
tnf___clm_description_for_sas
from whousep.summit_style_ids_new);

INSERT INTO vfap_retail.thermoball_style (select 
department_code,
department_description,
class_code,
class_description,
style_id,
vendor_style,
style_description,
vendor_cd_4,
vendor_cd_6,
cnodeid,
short_name,
long_name,
style_description_short,
style_description_long,
product_line,
sbu,
series,
newconsumersegmentterritory,
newendusesport,
newproductcollectionfamily,
tnf___clm_description_for_sas,
thermoball_flag
from whousep.thermoball_style);


INSERT INTO vfap_retail.tnf_adobe_cart_abandon (select  dt,
visitor_id,
webs_customer_id,
products,
cart_additions,
sas_brand_id,
fs_sk,
customer_id,
sas_product_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.tnf_adobe_cart_abandon);

INSERT INTO vfap_retail.tnf_adobe_cart_xref_final (select  visitor_id,
customer_id,
sas_brand_id,
current_timestamp as process_dtm
 from whousep.tnf_adobe_cart_xref_final);

INSERT INTO vfap_retail.tnf_adobe_productview_abandon (select  dt,
visitor_id,
webs_customer_id,
products,
product_views,
sas_brand_id,
fs_sk,
customer_id,
sas_product_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.tnf_adobe_productview_abandon);

INSERT INTO vfap_retail.tnf_adobe_prodview_xref_final (select  visitor_id,
customer_id,
sas_brand_id,
current_timestamp as process_dtm
 from whousep.tnf_adobe_prodview_xref_final);

INSERT INTO vfap_retail.tnf_email_click (select  sas_brand_id,
customer_id,
event_type_id,
account_id,
list_id,
riid,
customer_no,
event_captured_dt,
event_stored_dt,
campaign_id,
launch_id,
email_format,
offer_name,
offer_number,
offer_category,
offer_url,
store_id,
operating_system,
browser,
browser_type,
user_agent_string,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.tnf_email_click);


INSERT INTO vfap_retail.tnf_email_click_hist (select  id,
event_uuid,
event_type_id,
account_id,
list_id,
riid,
custom_properties,
campaign_id,
launch_id,
email_format,
offer_name,
offer_number,
offer_category,
offer_url,
event_captured_dt,
event_stored_dt,
customer_no,
customer_id,
sas_brand_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.tnf_email_click_hist);


INSERT INTO vfap_retail.tnf_email_convert (
select
customer_no,
event_type_id,
account_id,
list_id,
riid,
customer_id,
event_captured_dt,
event_stored_dt,
campaign_id,
launch_id,
source,
email_format,
offer_name,
offer_number,
offer_category,
offer_url,
order_id,
order_total,
order_quantity,
store_id,
user_agent_string,
operating_system,
browser,
browser_type,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.tnf_email_convert);


INSERT INTO vfap_retail.tnf_email_convert_hist (select 
id,
event_uuid,
event_type_id,
account_id,
list_id,
riid,
custom_properties,
campaign_id,
launch_id,
source,
email_format,
offer_name,
offer_number,
offer_category,
offer_url,
order_id,
order_total,
order_quantity,
operating_system,
browser,
browser_type,
user_agent_string,
enactment_id,
grp_enactment_id,
event_captured_dt,
event_stored_dt,
personalization_dt,
customer_no,
customer_id,
sas_brand_id,
current_timestamp as process_dtm
from whousep.tnf_email_convert_hist);

INSERT INTO vfap_retail.tnf_email_launch (
select 
account_id,
list_id,
event_captured_dt,
event_stored_dt,
campaign_id,
launch_id,
external_campaign_id,
sf_campaign_id,
campaign_name,
launch_name,
launch_status,
launch_type,
launch_charset,
purpose,
subject,
description,
product_category,
product_type,
marketing_strategy,
marketing_program,
launch_error_code,
launch_started_dt,
launch_completed_dt,
store_id,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::VARCHAR(200) file_name
from whousep.tnf_email_launch);

INSERT INTO vfap_retail.tnf_email_launch_hist (select 
id,
event_uuid,
account_id,
list_id,
custom_properties,
campaign_id,
launch_id,
external_campaign_id,
sf_campaign_id,
campaign_name,
launch_name,
launch_status,
launch_type,
launch_charset,
purpose,
subject,
description,
product_category,
product_type,
marketing_strategy,
marketing_program,
launch_error_code,
event_captured_dt,
event_stored_dt,
launch_completed_dt,
launch_started_dt,
sas_brand_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.tnf_email_launch_hist);

INSERT INTO vfap_retail.tnf_email_open (select sas_brand_id,
customer_id,
event_type_id,
account_id,
list_id,
riid,
customer_no,
event_captured_dt,
event_stored_dt,
campaign_id,
launch_id,
email_format,
store_id,
user_agent_string,
operating_system,
browser_type,
browser,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.tnf_email_open);

INSERT INTO vfap_retail.tnf_email_open_hist (select  account_id,
list_id,
riid,
custom_properties,
campaign_id,
launch_id,
email_format,
id,
event_uuid,
event_type_id,
event_captured_dt,
event_stored_dt,
customer_no,
customer_id,
sas_brand_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.tnf_email_open_hist);

INSERT INTO vfap_retail.tnf_email_sent (select  sas_brand_id,
customer_id,
event_typ_id,
account_id,
list_id,
riid,
customer_no,
event_captured_dt,
event_stored_dt,
campaign_id,
launch_id,
email,
email_isp,
email_format,
offer_signature,
dynamic_content_sig_id,
message_size,
segment_info,
contact_info,
store_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.tnf_email_sent);

INSERT INTO vfap_retail.tnf_email_sent_hist (select id,
event_uuid,
event_type_id,
account_id,
list_id,
riid,
custom_properties,
campaign_id,
launch_id,
email,
email_isp,
email_format,
offer_signature_id,
dynamic_content_signature_id,
message_size,
segment_info,
contact_info,
event_captured_dt,
event_stored_dt,
customer_no,
customer_id,
sas_brand_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.tnf_email_sent_hist);

INSERT INTO vfap_retail.tnf_footwear_style_id (select 
department_code,
department_description,
class_code,
class_description,
style_id,
vendor_style,
style_description,
vendor_cd_4,
vendor_cd_6,
cnodeid,
short_name,
long_name,
style_description_short,
style_description_long,
product_line,
sbu,
series,
newconsumersegmentterritory,
newendusesport,
newproductcollectionfamily,
tnf___clm_description_for_sas
 from whousep.tnf_footwear_style_id);

INSERT INTO vfap_retail.tnf_responsys_xref (select  list_id,
riid,
campaign_id,
launch_id,
customer_id
 from whousep.tnf_responsys_xref);

insert into vfap_retail.tnf_style_xref 
select  department_code,
department_description,
class_code,
class_description,
style_id,
vendor_style,
style_description,
vendor_cd_4,
vendor_cd_6,
cnodeid,
short_name,
long_name,
style_description_short,
style_description_long,
product_line,
sbu,
series,
newconsumersegmentterritory,
newendusesport,
newproductcollectionfamily,
tnf___clm_description_for_sas,
current_timestamp as process_dtm,
''::varchar(200) as file_name from whousep.tnf_style_xref;

insert into vfap_retail.tnf_style_xref_clean 
select   department_code,
department_description,
class_code,
class_description,
style_id,
vendor_style,
style_description,
vendor_cd_4,
vendor_cd_6,
cnodeid,
style_description_short,
style_description_long,
product_line,
sbu,
series,
newconsumersegmentterritory,
newendusesport,
newproductcollectionfamily,
tnf___clm_description_for_sas,
tnf_sas_product_category,
product_gender,
product_age_group,
sas_style_description,
trgt_ma_flag,
trgt_ms_flag,
trgt_ml_flag,
trgt_ue_flag,
gender_age,
tb_flag,
sm_flag,
fn_flag,
ss_flag,
rw_flag,
fw_flag,
bcpck_flag,
current_timestamp as process_dtm
 from whousep.tnf_style_xref_clean;

insert into vfap_retail.tnf_tibco select  loyaltylabrewardid,
rewardcompensation,
rewardtext,
rewardvalue,
retailershopperid,
instorecardshopperid,
firstname,
middlename,
lastname,
addressline1,
addressline2,
city,
state,
postalcode,
phonenumber,
email,
processdatetime,
pointbalance,
pointbalanceextractdate,
offerid,
offername,
loyaltyprogramid,
sku,
actualvalue,
valuetypecode,
code,
issuedate,
expirationtext,
expirationdate,
sas_brand_id,
fs_sk,
customer_id,
pointsawarded ,
current_timestamp as process_dtm,
''::varchar(200) as file_name 
from whousep.tnf_tibco;

insert into vfap_retail.tnf_wcs_abandoned_wish_cart 
select   customer_id,
sas_product_id,
email,
versioncode,
firstname,
lastname,
product_id,
cartlisturl,
giftbox,
cart_itm_dt,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name 
from whousep.tnf_wcs_abandoned_wish_cart;

insert into vfap_retail.tnf_wcs_returns_us 
select   customer_id,
sas_product_id,
productid,
orderid,
userid,
price,
currency,
dt,
rmaid,
returnreason,
firstname,
lastname,
emailid,
dim1,
dim2,
sas_brand_id,
fs_sk ,
current_timestamp as process_dtm,
''::varchar(200) as file_name
from whousep.tnf_wcs_returns_us;


insert into vfap_retail.trans_category 
select   transaction_category,
category_description,
sas_brand_id,
fs_sk, 
current_timestamp as process_dtm,
''::varchar(200) as file_name
from whousep.trans_category;	


insert into vfap_retail.trans_detail 
select   sas_brand_id,
transaction_id,
transaction_line_no,
sale_or_return_indicator,
sales_associate_no,
style_id,
color_code,
size_description,
quantity,
net_retail,
cost,
markdown_percent,
coupon_code,
class_code,
net_retail_central,
product_code,
fs_sk, 
current_timestamp as process_dtm,
''::varchar(200) as file_name
from whousep.trans_detail;

insert into vfap_retail.trans_header 
select   sas_brand_id,
customer_id,
customer_no,
transaction_id,
sales_module_transaction_id,
tender_type,
store_no,
sales_associate_no,
transaction_type,
transaction_date,
pos_transaction_no,
register_no,
segmentation_flag_a,
total_net_retail,
no_transaction_lines,
total_net_retail_central,
posted_date,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name from whousep.trans_header;

INSERT INTO vfap_retail.ur_sku
select 	material_trim,
ip_div,
ip_div_desc,
ip_dept,
ip_dept_desc,
ip_sub_dept,
ip_sub_dept_desc,
ip_cls,
ip_cls_desc,
ip_itm_desc,
ip_upc 
from whousep.ur_sku;

insert into vfap_retail.vans_coupon 
select   sas_brand_id,
detail_line_number,
pos_trans_no,
store,
register,
transaction_date,
deal_number,
event_number,
promotion_amount,
coupon_number,
fs_sk ,
current_timestamp as  process_dtm,
''::varchar(200) as file_name 
from whousep.vans_coupon;


insert into vfap_retail.vans_custom_shoes 
select   orders_id,
orderitems_id,
timeplaced,
totalproduct,
shipcharge,
totaladjustment,
name,
shipping_firstname,
shipping_lastname,
shipping_address1,
shipping_address2,
shipping_city,
shipping_state,
shipping_country,
shipping_zipcode,
email_address,
billing_lastname,
billing_firstname,
billing_address1,
billing_address2,
billing_city,
billing_state,
billing_country,
billing_zipcode,
payment_method,
sas_brand_id,
fs_sk,
customer_id ,
current_timestamp as  process_dtm,
''::varchar(200) as file_name
from whousep.vans_custom_shoes;


insert into vfap_retail.vans_item_master
select partnumber,
description,
upc,
attrname,
attrvalue,
sas_brand_id,
fs_sk
from whousep.vans_item_master;


insert into vfap_retail.vans_mte_style_id
select style_id,
vendor_code,
style_aka,
vendor_style,
style_description,
class_code,
subclass_code,
merchandising_style_code
from whousep.vans_mte_style_id;


insert into vfap_retail.vans_peanuts_style 
select   style_id,
vendor_code,
class_code,
product_code,
primary_size_code,
primary_size_label,
item_number,
gender,
category,
description,
color,
mtrl from whousep.vans_peanuts_style;

insert into vfap_reatail.vans_prod_seg_past_recom select 
category,
name,
color,
class,
vendor,
style,
color_1,
vendor__,
tab from vfap_reatail.vans_prod_seg_past_recom;

insert into vfap_retail.vans_progressive_upc select   ip_sku,
ip_upc,
ip_vndr_styl,
ip_div,
ip_div_desc,
ip_dept,
ip_dept_desc,
ip_cls,
ip_cls_desc,
ip_itm_desc,
current_timestamp as  process_dtm,
''::varchar(200) as file_name
from whousep.vans_progressive_upc;


insert into vfap_retail.vans_style_xref_clean (
SELECT 
department_code,
class_code,
class_description,
sas_brand_id,
style_id,
vendor_code,
subclass_code,
vendor_style,
style_aka,
style_description,
retail,
cost,
vans_prodcat,
mte_ind,
vans_sas_product_category,
product_family,
product_type,
product_gender,
product_age_group,
sas_style_description,
gen_age,
family_type,
skate_ind,
surf_ind,
snwb_ind,
nonsegment_ind,
trgt_peanuts_flag,
trgt_peanuts_like_flag,
peanuts_ind,
peanuts_like_ind,
trgt_ultrngls_flag,
trgt_ultrngpro_flag,
trgt_bts_flag,
trgt_new_ultrarange_flag,
current_timestamp as process_dtm,
fs_sk
from whousep.vans_style_xref_clean
);


insert into vfap_retail.vans_wcs_abandoned_cart 
select   customer_id,
sas_product_id,
email,
versioncode,
firstname,
lastname,
product_id,
cartlisturl,
giftbox,
cart_itm_dt,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name from whousep.vans_wcs_abandoned_cart;


insert into vfap_retail.vans_wcs_returns_us 
select   customer_id,
sas_product_id,
productid,
orderid,
userid,
price,
currency,
dt,
rmaid,
returnreason,
firstname,
lastname,
emailid,
dim1,
dim2,
sas_brand_id,
fs_sk ,
current_timestamp as process_dtm,
''::varchar(200) as file_name
from whousep.vans_wcs_returns_us;


insert into vfap_retail.vans_wcs_wishlist 
select   customer_id,
sas_product_id,
email,
versioncode,
firstname,
lastname,
product_id,
cartlisturl,
giftbox,
cart_itm_dt,
sas_brand_id,
fs_sk,
current_timestamp as process_dtm,
''::varchar(200) as file_name
from whousep.vans_wcs_wishlist;


insert into vfap_retail.vans_zeta_preference 
select   email,
int_skatebrd_flag,
int_surf_flag,
int_snowbrd_flag,
int_bmx_flag,
int_music_flag,
int_art_flag,
int_fashion_flag,
shppref_vansstore,
shppref_vansoutlet,
shppref_otherstore,
shppref_online,
add_date,
update_date,
sas_brand_id,
fs_sk,
customer_id ,
current_timestamp as process_dtm,
''::varchar(200) as file_name
from whousep.vans_zeta_preference;


insert into vfap_retail.vans_zeta_response 
select   campaign_id,
campaign_name,
mailing_id,
mailing_name,
cell_id,
cell_name,
mailing_udf1,
mailing_udf2,
mailing_udf3,
email_subject,
customer_no,
email_address,
event_date,
event_type,
conv_amount,
sas_brand_id,
fs_sk,
customer_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.vans_zeta_response;
 
 
insert into vfap_retail.vans_zeta_sent select   campaign_id,
campaign_name,
mailing_id,
mailing_name,
cell_id,
cell_name,
mailing_udf_1,
mailing_udf_2,
mailing_udf_3,
email_subject,
mailed_date,
mailed_count,
customer_no,
email_address,
sas_brand_id,
fs_sk,
customer_id ,
current_timestamp as process_dtm,
''::varchar(200) as file_name
from whousep.vans_zeta_sent;


insert into vfap_retail.weather_forecast 
select   location,
municipality,
state,
county,
dt,
mintempdegf,
maxtempdegf,
prcpin,
snowin,
wspdmph,
wdirdeg,
gustmph,
rhpct,
skycpct,
presmb,
poppct,
uvindex,
wxicon,
mintemplydegf,
maxtemplydegf,
mintempnormdegf,
maxtempnormdegf,
fs_sk,
sas_brand_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
 from whousep.weather_forecast;
 
 
insert into vfap_retail.weather_hist 
select   location,
municipality,
state,
county,
dt,
mintempdegf,
maxtempdegf,
prcpin,
snowin,
wspdmph,
wdirdeg,
gustmph,
rhpct,
skycpct,
presmb,
poppct,
uvindex,
wxicon,
mintemplydegf,
maxtemplydegf,
mintempnormdegf,
maxtempnormdegf,
fs_sk,
sas_brand_id,
sas_process_dt,
current_timestamp as process_dtm,
''::varchar(200) as file_name 
from whousep.weather_hist;


insert into vfap_retail.weather_hist_weekly 
select   dt,
location,
sas_brand_id,
mintemp_min,
mintemp_max,
mintemp_avg,
maxtemp_min,
maxtemp_max,
maxtemp_avg,
rngtemp_min,
rngtemp_max,
rngtemp_avg,
prcpin_min,
prcpin_max,
prcpin_avg,
snowin_min,
snowin_max,
snowin_avg,
wspdmph_min,
wspdmph_max,
wspdmph_avg,
gustmph_min,
gustmph_max,
gustmph_avg,
rhpct_min,
rhpct_max,
rhpct_avg,
skycpct_min,
skycpct_max,
skycpct_avg,
presmb_min,
presmb_max,
presmb_avg,
prcpin_ndays,
snowin_ndays,
n_dt,
mintemp_n,
maxtemp_n,
rngtemp_n,
prcpin_n,
snowin_n,
wspdmph_n,
gustmph_n,
rhpct_n,
skycpct_n,
presmb_n,
sas_process_dt,
current_timestamp as process_dtm,
''::varchar(200) as file_name
from whousep.weather_hist_weekly;


insert into vfap_retail.weather_longrange 
select   dt,
mintemp,
maxtemp,
avgtemp,
prcp,
location,
fs_sk,
sas_brand_id,
current_timestamp as process_dtm,
''::varchar(200) as file_name
from whousep.weather_longrange;


insert into vfap_retail.webs_xref 
select   sas_brand_id,
webs_customer_id,
customer_id ,
current_timestamp as process_dtm
from whousep.webs_xref;




 



 