AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Ingestion Routine Lambda cloud formation stack'
Parameters:
  EnvironmentType:
    Description: The environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - qa
    ConstraintDescription: 'must be a dev, test or prod'
  ResourceGroup:
    Description: The ResourceGroup Name
    Type: String
    Default: 'VFAP:SUPPORT'
  Application:
    Description: The Application Name
    Type: String
    Default: 'VFAP:INGEST'
  LambdaFunctionName:
    Description: The Application Name
    Type: String
    Default: 'ingestion-routine'   
Mappings:
  EnvironmentMap:
    dev:
      LambdaRole: ''
    qa:
      LambdaRole: ''
    prod:
      LambdaRole: ''
Resources:
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Join 
        - '-'
        - - vf
          - !Ref EnvironmentType
          - !Ref LambdaFunctionName
      Handler: main.lambda_handler
      Runtime: python3.7
      Description: !Join [ ' ', [ !Ref LambdaFunctionName, 'lambda' ] ]
      CodeUri: ./ingestion-routine/src/
      MemorySize: 2048
      Timeout: 900
      Role: !FindInMap 
        - EnvironmentMap
        - !Ref EnvironmentType
        - LambdaRole
      Tags:
        - Key: CostCenter
          Value: '118204800'
        - Key: TechOwnerEmail
          Value: DEEPAK_LAKSHMANAN1@VFC.COM
        - Key: Environment
          Value: !Ref EnvironmentType
        - Key: BusinessOwnerEmail
          Value: DEEPAK_LAKSHMANAN1@VFC.COM
        - Key: ResourceGroup
          Value: !Ref ResourceGroup
        - Key: Application
          Value: !Ref Application