DROP TABLE IF EXISTS vfap_retail.address;
CREATE TABLE IF NOT EXISTS vfap_retail.address(
customer_id INTEGER ,
customer_no BIGINT ,
address_id INTEGER ,
country_code VARCHAR(5) ,
address_match_key VARCHAR(40) ,
telephone_no VARCHAR(24) ,
address_type_code VARCHAR(7) ,
address_1 VARCHAR(58) ,
address_2 VARCHAR(41) ,
address_3 VARCHAR(44) ,
address_4 VARCHAR(4) ,
post_code VARCHAR(57) ,
date_last_modified TIMESTAMP WITHOUT TIME ZONE ,
mail_opt_in_flag INTEGER ,
mail_opt_in_date TIMESTAMP WITHOUT TIME ZONE ,
phone_opt_in_flag INTEGER ,
phone_opt_in_date TIMESTAMP WITHOUT TIME ZONE ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.address (select * from whousep.address);

DROP TABLE IF EXISTS vfap_retail.brand;
CREATE TABLE IF NOT EXISTS vfap_retail.brand(
brand_id_desc VARCHAR(30) ,
sas_brand_id INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.brand (select * from whousep.brand);

DROP TABLE  IF EXISTS vfap_retail.class;
CREATE TABLE IF NOT EXISTS vfap_retail.class(
class_code INTEGER ,
department_code INTEGER ,
class_description VARCHAR(27) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.class (select * from whousep.class);

DROP TABLE IF EXISTS vfap_retail.cm_abandon;
CREATE TABLE IF NOT EXISTS vfap_retail.cm_abandon(
session_id VARCHAR(20) ,
cookie_id VARCHAR(24) ,
ts TIMESTAMP WITHOUT TIME ZONE ,
product_id VARCHAR(256) ,
product_name VARCHAR(256) ,
product_category VARCHAR(256) ,
product_category_id VARCHAR(256) ,
product_category_top VARCHAR(256) ,
product_category_bottom VARCHAR(256) ,
base_price DOUBLE PRECISION ,
qy INTEGER ,
order_id VARCHAR(64) ,
site_id VARCHAR(100) ,
abandonment_attribute_1 VARCHAR(256) ,
abandonment_attribute_2 VARCHAR(256) ,
abandonment_attribute_3 VARCHAR(256) ,
abandonment_attribute_4 VARCHAR(256) ,
abandonment_attribute_5 VARCHAR(256) ,
abandonment_attribute_6 VARCHAR(256) ,
abandonment_attribute_7 VARCHAR(256) ,
abandonment_attribute_8 VARCHAR(256) ,
abandonment_attribute_9 VARCHAR(256) ,
abandonment_attribute_10 VARCHAR(256) ,
abandonment_attribute_11 VARCHAR(256) ,
abandonment_attribute_12 VARCHAR(256) ,
abandonment_attribute_13 VARCHAR(256) ,
abandonment_attribute_14 VARCHAR(256) ,
abandonment_attribute_15 VARCHAR(256) ,
abandonment_attribute_16 VARCHAR(256) ,
abandonment_attribute_17 VARCHAR(256) ,
abandonment_attribute_18 VARCHAR(256) ,
abandonment_attribute_19 VARCHAR(256) ,
abandonment_attribute_20 VARCHAR(256) ,
abandonment_attribute_21 VARCHAR(256) ,
abandonment_attribute_22 VARCHAR(256) ,
abandonment_attribute_23 VARCHAR(256) ,
abandonment_attribute_24 VARCHAR(256) ,
abandonment_attribute_25 VARCHAR(256) ,
abandonment_attribute_26 VARCHAR(256) ,
abandonment_attribute_27 VARCHAR(256) ,
abandonment_attribute_28 VARCHAR(256) ,
abandonment_attribute_29 VARCHAR(256) ,
abandonment_attribute_30 VARCHAR(256) ,
abandonment_attribute_31 VARCHAR(256) ,
abandonment_attribute_32 VARCHAR(256) ,
abandonment_attribute_33 VARCHAR(256) ,
abandonment_attribute_34 VARCHAR(256) ,
abandonment_attribute_35 VARCHAR(256) ,
abandonment_attribute_36 VARCHAR(256) ,
abandonment_attribute_37 VARCHAR(256) ,
abandonment_attribute_38 VARCHAR(256) ,
abandonment_attribute_39 VARCHAR(256) ,
abandonment_attribute_40 VARCHAR(256) ,
abandonment_attribute_41 VARCHAR(256) ,
abandonment_attribute_42 VARCHAR(256) ,
abandonment_attribute_43 VARCHAR(256) ,
abandonment_attribute_44 VARCHAR(256) ,
abandonment_attribute_45 VARCHAR(256) ,
abandonment_attribute_46 VARCHAR(256) ,
abandonment_attribute_47 VARCHAR(256) ,
abandonment_attribute_48 VARCHAR(256) ,
abandonment_attribute_49 VARCHAR(256) ,
abandonment_attribute_50 VARCHAR(256) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
customer_id INTEGER ,
sas_product_id VARCHAR(20) ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cm_abandon (select * from whousep.cm_abandon);

DROP TABLE  IF EXISTS vfap_retail.cm_conversion;
CREATE TABLE IF NOT EXISTS vfap_retail.cm_conversion(
session_id VARCHAR(20) ,
cookie_id VARCHAR(24) ,
ts TIMESTAMP WITHOUT TIME ZONE ,
event_name VARCHAR(256) ,
event_category VARCHAR(256) ,
event_action_type INTEGER ,
event_points INTEGER ,
site_id VARCHAR(100) ,
conversion_event_attribute_1 VARCHAR(256) ,
conversion_event_attribute_2 VARCHAR(256) ,
conversion_event_attribute_3 VARCHAR(256) ,
conversion_event_attribute_4 VARCHAR(256) ,
conversion_event_attribute_5 VARCHAR(256) ,
conversion_event_attribute_6 VARCHAR(256) ,
conversion_event_attribute_7 VARCHAR(256) ,
conversion_event_attribute_8 VARCHAR(256) ,
conversion_event_attribute_9 VARCHAR(256) ,
conversion_event_attribute_10 VARCHAR(256) ,
conversion_event_attribute_11 VARCHAR(256) ,
conversion_event_attribute_12 VARCHAR(256) ,
conversion_event_attribute_13 VARCHAR(256) ,
conversion_event_attribute_14 VARCHAR(256) ,
conversion_event_attribute_15 VARCHAR(256) ,
conversion_event_attribute_16 VARCHAR(256) ,
conversion_event_attribute_17 VARCHAR(256) ,
conversion_event_attribute_18 VARCHAR(256) ,
conversion_event_attribute_19 VARCHAR(256) ,
conversion_event_attribute_20 VARCHAR(256) ,
conversion_event_attribute_21 VARCHAR(256) ,
conversion_event_attribute_22 VARCHAR(256) ,
conversion_event_attribute_23 VARCHAR(256) ,
conversion_event_attribute_24 VARCHAR(256) ,
conversion_event_attribute_25 VARCHAR(256) ,
conversion_event_attribute_26 VARCHAR(256) ,
conversion_event_attribute_27 VARCHAR(256) ,
conversion_event_attribute_28 VARCHAR(256) ,
conversion_event_attribute_29 VARCHAR(256) ,
conversion_event_attribute_30 VARCHAR(256) ,
conversion_event_attribute_31 VARCHAR(256) ,
conversion_event_attribute_32 VARCHAR(256) ,
conversion_event_attribute_33 VARCHAR(256) ,
conversion_event_attribute_34 VARCHAR(256) ,
conversion_event_attribute_35 VARCHAR(256) ,
conversion_event_attribute_36 VARCHAR(256) ,
conversion_event_attribute_37 VARCHAR(256) ,
conversion_event_attribute_38 VARCHAR(256) ,
conversion_event_attribute_39 VARCHAR(256) ,
conversion_event_attribute_40 VARCHAR(256) ,
conversion_event_attribute_41 VARCHAR(256) ,
conversion_event_attribute_42 VARCHAR(256) ,
conversion_event_attribute_43 VARCHAR(256) ,
conversion_event_attribute_44 VARCHAR(256) ,
conversion_event_attribute_45 VARCHAR(256) ,
conversion_event_attribute_46 VARCHAR(256) ,
conversion_event_attribute_47 VARCHAR(256) ,
conversion_event_attribute_48 VARCHAR(256) ,
conversion_event_attribute_49 VARCHAR(256) ,
conversion_event_attribute_50 VARCHAR(256) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
customer_id INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cm_conversion (select * from whousep.cm_conversion);

DROP TABLE IF EXISTS vfap_retail.cm_mmcclick;
CREATE TABLE IF NOT EXISTS vfap_retail.cm_mmcclick(
session_id VARCHAR(20) ,
cookie_id VARCHAR(24) ,
ts TIMESTAMP WITHOUT TIME ZONE ,
marketing_vendor VARCHAR(256) ,
marketing_category VARCHAR(256) ,
marketing_placement VARCHAR(256) ,
marketing_item VARCHAR(256) ,
site_id VARCHAR(100) ,
mmc_click_attribute_1 VARCHAR(256) ,
mmc_click_attribute_2 VARCHAR(256) ,
mmc_click_attribute_3 VARCHAR(256) ,
mmc_click_attribute_4 VARCHAR(256) ,
mmc_click_attribute_5 VARCHAR(256) ,
mmc_click_attribute_6 VARCHAR(256) ,
mmc_click_attribute_7 VARCHAR(256) ,
mmc_click_attribute_8 VARCHAR(256) ,
mmc_click_attribute_9 VARCHAR(256) ,
mmc_click_attribute_10 VARCHAR(256) ,
mmc_click_attribute_11 VARCHAR(256) ,
mmc_click_attribute_12 VARCHAR(256) ,
mmc_click_attribute_13 VARCHAR(256) ,
mmc_click_attribute_14 VARCHAR(256) ,
mmc_click_attribute_15 VARCHAR(256) ,
mmc_click_attribute_16 VARCHAR(256) ,
mmc_click_attribute_17 VARCHAR(256) ,
mmc_click_attribute_18 VARCHAR(256) ,
mmc_click_attribute_19 VARCHAR(256) ,
mmc_click_attribute_20 VARCHAR(256) ,
mmc_click_attribute_21 VARCHAR(256) ,
mmc_click_attribute_22 VARCHAR(256) ,
mmc_click_attribute_23 VARCHAR(256) ,
mmc_click_attribute_24 VARCHAR(256) ,
mmc_click_attribute_25 VARCHAR(256) ,
mmc_click_attribute_26 VARCHAR(256) ,
mmc_click_attribute_27 VARCHAR(256) ,
mmc_click_attribute_28 VARCHAR(256) ,
mmc_click_attribute_29 VARCHAR(256) ,
mmc_click_attribute_30 VARCHAR(256) ,
mmc_click_attribute_31 VARCHAR(256) ,
mmc_click_attribute_32 VARCHAR(256) ,
mmc_click_attribute_33 VARCHAR(256) ,
mmc_click_attribute_34 VARCHAR(256) ,
mmc_click_attribute_35 VARCHAR(256) ,
mmc_click_attribute_36 VARCHAR(256) ,
mmc_click_attribute_37 VARCHAR(256) ,
mmc_click_attribute_38 VARCHAR(256) ,
mmc_click_attribute_39 VARCHAR(256) ,
mmc_click_attribute_40 VARCHAR(256) ,
mmc_click_attribute_41 VARCHAR(256) ,
mmc_click_attribute_42 VARCHAR(256) ,
mmc_click_attribute_43 VARCHAR(256) ,
mmc_click_attribute_44 VARCHAR(256) ,
mmc_click_attribute_45 VARCHAR(256) ,
mmc_click_attribute_46 VARCHAR(256) ,
mmc_click_attribute_47 VARCHAR(256) ,
mmc_click_attribute_48 VARCHAR(256) ,
mmc_click_attribute_49 VARCHAR(256) ,
mmc_click_attribute_50 VARCHAR(256) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cm_mmcclick (select * from whousep.cm_mmcclick);

DROP TABLE IF EXISTS vfap_retail.cm_pageview;
CREATE TABLE IF NOT EXISTS vfap_retail.cm_pageview(
session_id VARCHAR(34),
cookie_id VARCHAR(41),
ts TIMESTAMP WITHOUT TIME ZONE,
page VARCHAR(600),
page_id VARCHAR(600),
content_category VARCHAR(600),
content_category_id VARCHAR(600),
content_category_top VARCHAR(600),
content_category_bottom VARCHAR(600),
on_site_search_term VARCHAR(600),
page_url VARCHAR(3000),
page_referral_url VARCHAR(3000),
site_id VARCHAR(250),
page_view_attribute_1 VARCHAR(600),
page_view_attribute_2 VARCHAR(600),
page_view_attribute_3 VARCHAR(600),
page_view_attribute_4 VARCHAR(600),
page_view_attribute_5 VARCHAR(600),
page_view_attribute_6 VARCHAR(600),
page_view_attribute_7 VARCHAR(600),
page_view_attribute_8 VARCHAR(600),
page_view_attribute_9 VARCHAR(600),
page_view_attribute_10 VARCHAR(600),
page_view_attribute_11 VARCHAR(600),
page_view_attribute_12 VARCHAR(600),
page_view_attribute_13 VARCHAR(600),
page_view_attribute_14 VARCHAR(600),
page_view_attribute_15 VARCHAR(600),
page_view_attribute_16 VARCHAR(600),
page_view_attribute_17 VARCHAR(600),
page_view_attribute_18 VARCHAR(600),
page_view_attribute_19 VARCHAR(600),
page_view_attribute_20 VARCHAR(600),
page_view_attribute_21 VARCHAR(600),
page_view_attribute_22 VARCHAR(600),
page_view_attribute_23 VARCHAR(600),
page_view_attribute_24 VARCHAR(600),
page_view_attribute_25 VARCHAR(600),
page_view_attribute_26 VARCHAR(600),
page_view_attribute_27 VARCHAR(600),
page_view_attribute_28 VARCHAR(600),
page_view_attribute_29 VARCHAR(600),
page_view_attribute_30 VARCHAR(600),
page_view_attribute_31 VARCHAR(600),
page_view_attribute_32 VARCHAR(600),
page_view_attribute_33 VARCHAR(600),
page_view_attribute_34 VARCHAR(600),
page_view_attribute_35 VARCHAR(600),
page_view_attribute_36 VARCHAR(600),
page_view_attribute_37 VARCHAR(600),
page_view_attribute_38 VARCHAR(600),
page_view_attribute_39 VARCHAR(600),
page_view_attribute_40 VARCHAR(600),
page_view_attribute_41 VARCHAR(600),
page_view_attribute_42 VARCHAR(600),
page_view_attribute_43 VARCHAR(600),
page_view_attribute_44 VARCHAR(600),
page_view_attribute_45 VARCHAR(600),
page_view_attribute_46 VARCHAR(600),
page_view_attribute_47 VARCHAR(600),
page_view_attribute_48 VARCHAR(600),
page_view_attribute_49 VARCHAR(600),
page_view_attribute_50 VARCHAR(600),
search_results_count INTEGER,
sas_brand_id INTEGER,
fs_sk INTEGER,
customer_id INTEGER,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cm_pageview (select * from whousep.cm_pageview);

DROP TABLE IF EXISTS vfap_retail.cm_productview;
CREATE TABLE IF NOT EXISTS vfap_retail.cm_productview(
session_id VARCHAR(34),
cookie_id VARCHAR(41),
ts TIMESTAMP WITHOUT TIME ZONE,
product_name VARCHAR(435),
product_id VARCHAR(435),
page_id VARCHAR(530),
product_category_id VARCHAR(435),
product_category VARCHAR(435),
product_category_top VARCHAR(435),
product_category_bottom VARCHAR(435),
site_id VARCHAR(170),
product_view_attribute_1 VARCHAR(256),
product_view_attribute_2 VARCHAR(256),
product_view_attribute_3 VARCHAR(256),
product_view_attribute_4 VARCHAR(256),
product_view_attribute_5 VARCHAR(256),
product_view_attribute_6 VARCHAR(256),
product_view_attribute_7 VARCHAR(256),
product_view_attribute_8 VARCHAR(256),
product_view_attribute_9 VARCHAR(256),
product_view_attribute_10 VARCHAR(256),
product_view_attribute_11 VARCHAR(256),
product_view_attribute_12 VARCHAR(256),
product_view_attribute_13 VARCHAR(256),
product_view_attribute_14 VARCHAR(256),
product_view_attribute_15 VARCHAR(256),
product_view_attribute_16 VARCHAR(256),
product_view_attribute_17 VARCHAR(256),
product_view_attribute_18 VARCHAR(256),
product_view_attribute_19 VARCHAR(256),
product_view_attribute_20 VARCHAR(256),
product_view_attribute_21 VARCHAR(256),
product_view_attribute_22 VARCHAR(256),
product_view_attribute_23 VARCHAR(256),
product_view_attribute_24 VARCHAR(256),
product_view_attribute_25 VARCHAR(256),
product_view_attribute_26 VARCHAR(256),
product_view_attribute_27 VARCHAR(256),
product_view_attribute_28 VARCHAR(256),
product_view_attribute_29 VARCHAR(256),
product_view_attribute_30 VARCHAR(256),
product_view_attribute_31 VARCHAR(256),
product_view_attribute_32 VARCHAR(256),
product_view_attribute_33 VARCHAR(256),
product_view_attribute_34 VARCHAR(256),
product_view_attribute_35 VARCHAR(256),
product_view_attribute_36 VARCHAR(256),
product_view_attribute_37 VARCHAR(256),
product_view_attribute_38 VARCHAR(256),
product_view_attribute_39 VARCHAR(256),
product_view_attribute_40 VARCHAR(256),
product_view_attribute_41 VARCHAR(256),
product_view_attribute_42 VARCHAR(256),
product_view_attribute_43 VARCHAR(256),
product_view_attribute_44 VARCHAR(256),
product_view_attribute_45 VARCHAR(256),
product_view_attribute_46 VARCHAR(256),
product_view_attribute_47 VARCHAR(256),
product_view_attribute_48 VARCHAR(256),
product_view_attribute_49 VARCHAR(256),
product_view_attribute_50 VARCHAR(256),
sas_brand_id INTEGER,
fs_sk INTEGER,
customer_id INTEGER,
sas_product_id VARCHAR(20),
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cm_productview (select * from whousep.cm_productview);

DROP TABLE IF EXISTS vfap_retail.cm_registration;
CREATE TABLE IF NOT EXISTS vfap_retail.cm_registration(
session_id VARCHAR(34) ,
cookie_id VARCHAR(41) ,
registration_id VARCHAR(435) ,
new_repeat_buyer VARCHAR(2) ,
new_repeat_visitor VARCHAR(2) ,
visitor_customer_flag VARCHAR(2) ,
registered_city VARCHAR(435) ,
registered_state VARCHAR(435) ,
registered_country VARCHAR(435) ,
registered_zip_code VARCHAR(435) ,
gndr VARCHAR(2) ,
email_address VARCHAR(435) ,
age INTEGER ,
registration_attribute_1 VARCHAR(435) ,
registration_attribute_2 VARCHAR(435) ,
registration_attribute_3 VARCHAR(435) ,
registration_attribute_4 VARCHAR(435) ,
registration_attribute_5 VARCHAR(435) ,
registration_attribute_6 VARCHAR(435) ,
registration_attribute_7 VARCHAR(435) ,
registration_attribute_8 VARCHAR(435) ,
registration_attribute_9 VARCHAR(435) ,
registration_attribute_10 VARCHAR(435) ,
registration_attribute_11 VARCHAR(435) ,
registration_attribute_12 VARCHAR(435) ,
registration_attribute_13 VARCHAR(435) ,
registration_attribute_14 VARCHAR(435) ,
registration_attribute_15 VARCHAR(435) ,
registration_attribute_16 VARCHAR(435) ,
registration_attribute_17 VARCHAR(435) ,
registration_attribute_18 VARCHAR(435) ,
registration_attribute_19 VARCHAR(435) ,
registration_attribute_20 VARCHAR(435) ,
registration_attribute_21 VARCHAR(435) ,
registration_attribute_22 VARCHAR(435) ,
registration_attribute_23 VARCHAR(435) ,
registration_attribute_24 VARCHAR(435) ,
registration_attribute_25 VARCHAR(435) ,
registration_attribute_26 VARCHAR(435) ,
registration_attribute_27 VARCHAR(435) ,
registration_attribute_28 VARCHAR(435) ,
registration_attribute_29 VARCHAR(435) ,
registration_attribute_30 VARCHAR(435) ,
registration_attribute_31 VARCHAR(435) ,
registration_attribute_32 VARCHAR(435) ,
registration_attribute_33 VARCHAR(435) ,
registration_attribute_34 VARCHAR(435) ,
registration_attribute_35 VARCHAR(435) ,
registration_attribute_36 VARCHAR(435) ,
registration_attribute_37 VARCHAR(435) ,
registration_attribute_38 VARCHAR(435) ,
registration_attribute_39 VARCHAR(435) ,
registration_attribute_40 VARCHAR(435) ,
registration_attribute_41 VARCHAR(435) ,
registration_attribute_42 VARCHAR(435) ,
registration_attribute_43 VARCHAR(435) ,
registration_attribute_44 VARCHAR(435) ,
registration_attribute_45 VARCHAR(435) ,
registration_attribute_46 VARCHAR(435) ,
registration_attribute_47 VARCHAR(435) ,
registration_attribute_48 VARCHAR(435) ,
registration_attribute_49 VARCHAR(435) ,
registration_attribute_50 VARCHAR(435) ,
last_update_date TIMESTAMP WITHOUT TIME ZONE ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cm_registration (select * from whousep.cm_registration);

DROP TABLE IF EXISTS vfap_retail.cm_session_xref;
CREATE TABLE IF NOT EXISTS vfap_retail.cm_session_xref(
session_id VARCHAR(34) ,
customer_id INTEGER ,
sas_brand_id INTEGER ,
process_dtm TIMESTAMP default null
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cm_session_xref (select * from whousep.cm_session_xref);

DROP TABLE IF EXISTS vfap_retail.cmpgn_xref;
CREATE TABLE IF NOT EXISTS vfap_retail.cmpgn_xref(
seq INTEGER ,
offer_category VARCHAR(34) ,
email_campaign_category VARCHAR(16) ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cmpgn_xref (select * from whousep.cmpgn_xref);

DROP TABLE IF EXISTS vfap_retail.color;
CREATE TABLE IF NOT EXISTS vfap_retail.color(
color_code INTEGER ,
color_description VARCHAR(30) ,
fs_sk INTEGER ,
sas_brand_id INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.color (select * from whousep.color);

--csv_tnf_email_inputs schema is not there


DROP TABLE IF EXISTS vfap_retail.csv_vans_zeta_inputs;
CREATE TABLE IF NOT EXISTS vfap_retail.csv_vans_zeta_inputs(
customer_id INTEGER  ,
ssn_md2o_bts DOUBLE PRECISION ,
ssn_md2o_fco DOUBLE PRECISION ,
ssn_md2o_hco DOUBLE PRECISION ,
ssn_md2o_hol DOUBLE PRECISION ,
ssn_md2o_spr DOUBLE PRECISION ,
ssn_md2o_sum DOUBLE PRECISION ,
ssn_md2c_bts DOUBLE PRECISION ,
ssn_md2c_fco DOUBLE PRECISION ,
ssn_md2c_hco DOUBLE PRECISION ,
ssn_md2c_hol DOUBLE PRECISION ,
ssn_md2c_spr DOUBLE PRECISION ,
ssn_md2c_sum DOUBLE PRECISION ,
ssn_dsinco_bts DOUBLE PRECISION ,
ssn_dsinco_fco DOUBLE PRECISION ,
ssn_dsinco_hco DOUBLE PRECISION ,
ssn_dsinco_hol DOUBLE PRECISION ,
ssn_dsinco_spr DOUBLE PRECISION ,
ssn_dsinco_sum DOUBLE PRECISION ,
ssn_freq_s_bts DOUBLE PRECISION ,
ssn_freq_s_fco DOUBLE PRECISION ,
ssn_freq_s_hco DOUBLE PRECISION ,
ssn_freq_s_hol DOUBLE PRECISION ,
ssn_freq_s_spr DOUBLE PRECISION ,
ssn_freq_s_sum DOUBLE PRECISION ,
ssn_freq_o_bts DOUBLE PRECISION ,
ssn_freq_o_fco DOUBLE PRECISION ,
ssn_freq_o_hco DOUBLE PRECISION ,
ssn_freq_o_hol DOUBLE PRECISION ,
ssn_freq_o_spr DOUBLE PRECISION ,
ssn_freq_o_sum DOUBLE PRECISION ,
ssn_freq_c_bts DOUBLE PRECISION ,
ssn_freq_c_fco DOUBLE PRECISION ,
ssn_freq_c_hco DOUBLE PRECISION ,
ssn_freq_c_hol DOUBLE PRECISION ,
ssn_freq_c_spr DOUBLE PRECISION ,
ssn_freq_c_sum DOUBLE PRECISION ,
ssn_pct_o_bts DOUBLE PRECISION ,
ssn_pct_o_fco DOUBLE PRECISION ,
ssn_pct_o_hco DOUBLE PRECISION ,
ssn_pct_o_hol DOUBLE PRECISION ,
ssn_pct_o_spr DOUBLE PRECISION ,
ssn_pct_o_sum DOUBLE PRECISION ,
ssn_pct_c_bts DOUBLE PRECISION ,
ssn_pct_c_fco DOUBLE PRECISION ,
ssn_pct_c_hco DOUBLE PRECISION ,
ssn_pct_c_hol DOUBLE PRECISION ,
ssn_pct_c_spr DOUBLE PRECISION ,
ssn_pct_c_sum DOUBLE PRECISION ,
genage_md2o_a DOUBLE PRECISION ,
genage_md2o_k DOUBLE PRECISION ,
genage_md2o_m DOUBLE PRECISION ,
genage_md2o_w DOUBLE PRECISION ,
genage_md2c_a DOUBLE PRECISION ,
genage_md2c_k DOUBLE PRECISION ,
genage_md2c_m DOUBLE PRECISION ,
genage_md2c_w DOUBLE PRECISION ,
genage_dsinco_a DOUBLE PRECISION ,
genage_dsinco_k DOUBLE PRECISION ,
genage_dsinco_m DOUBLE PRECISION ,
genage_dsinco_w DOUBLE PRECISION ,
genage_freq_s_a DOUBLE PRECISION ,
genage_freq_s_k DOUBLE PRECISION ,
genage_freq_s_m DOUBLE PRECISION ,
genage_freq_s_w DOUBLE PRECISION ,
genage_freq_o_a DOUBLE PRECISION ,
genage_freq_o_k DOUBLE PRECISION ,
genage_freq_o_m DOUBLE PRECISION ,
genage_freq_o_w DOUBLE PRECISION ,
genage_freq_c_a DOUBLE PRECISION ,
genage_freq_c_k DOUBLE PRECISION ,
genage_freq_c_m DOUBLE PRECISION ,
genage_freq_c_w DOUBLE PRECISION ,
genage_pct_o_a DOUBLE PRECISION ,
genage_pct_o_k DOUBLE PRECISION ,
genage_pct_o_m DOUBLE PRECISION ,
genage_pct_o_w DOUBLE PRECISION ,
genage_pct_c_a DOUBLE PRECISION ,
genage_pct_c_k DOUBLE PRECISION ,
genage_pct_c_m DOUBLE PRECISION ,
genage_pct_c_w DOUBLE PRECISION ,
act_md2o_skate DOUBLE PRECISION ,
act_md2o_snwb DOUBLE PRECISION ,
act_md2o_surf DOUBLE PRECISION ,
act_md2c_skate DOUBLE PRECISION ,
act_md2c_snwb DOUBLE PRECISION ,
act_md2c_surf DOUBLE PRECISION ,
act_dsinco_skate DOUBLE PRECISION ,
act_dsinco_snwb DOUBLE PRECISION ,
act_dsinco_surf DOUBLE PRECISION ,
act_freq_s_skate DOUBLE PRECISION ,
act_freq_s_snwb DOUBLE PRECISION ,
act_freq_s_surf DOUBLE PRECISION ,
act_freq_o_skate DOUBLE PRECISION ,
act_freq_o_snwb DOUBLE PRECISION ,
act_freq_o_surf DOUBLE PRECISION ,
act_freq_c_skate DOUBLE PRECISION ,
act_freq_c_snwb DOUBLE PRECISION ,
act_freq_c_surf DOUBLE PRECISION ,
act_pct_o_skate DOUBLE PRECISION ,
act_pct_o_snwb DOUBLE PRECISION ,
act_pct_o_surf DOUBLE PRECISION ,
act_pct_c_skate DOUBLE PRECISION ,
act_pct_c_snwb DOUBLE PRECISION ,
act_pct_c_surf DOUBLE PRECISION ,
prs_md2o_artcollab DOUBLE PRECISION ,
prs_md2o_collab DOUBLE PRECISION ,
prs_md2o_event DOUBLE PRECISION ,
prs_md2o_new_arri DOUBLE PRECISION ,
prs_md2o_new_cust DOUBLE PRECISION ,
prs_md2o_reward DOUBLE PRECISION ,
prs_md2o_reengage DOUBLE PRECISION ,
prs_md2o_survey DOUBLE PRECISION ,
prs_md2o_abdn_cart DOUBLE PRECISION ,
prs_md2o_rtn_cust DOUBLE PRECISION ,
prs_md2c_artcollab DOUBLE PRECISION ,
prs_md2c_collab DOUBLE PRECISION ,
prs_md2c_event DOUBLE PRECISION ,
prs_md2c_new_arri DOUBLE PRECISION ,
prs_md2c_new_cust DOUBLE PRECISION ,
prs_md2c_reward DOUBLE PRECISION ,
prs_md2c_reengage DOUBLE PRECISION ,
prs_md2c_survey DOUBLE PRECISION ,
prs_md2c_abdn_cart DOUBLE PRECISION ,
prs_md2c_rtn_cust DOUBLE PRECISION ,
prs_dsinco_artcollab DOUBLE PRECISION ,
prs_dsinco_collab DOUBLE PRECISION ,
prs_dsinco_event DOUBLE PRECISION ,
prs_dsinco_new_arri DOUBLE PRECISION ,
prs_dsinco_new_cust DOUBLE PRECISION ,
prs_dsinco_reward DOUBLE PRECISION ,
prs_dsinco_reengage DOUBLE PRECISION ,
prs_dsinco_survey DOUBLE PRECISION ,
prs_dsinco_abdn_cart DOUBLE PRECISION ,
prs_dsinco_rtn_cust DOUBLE PRECISION ,
prs_freq_s_artcollab DOUBLE PRECISION ,
prs_freq_s_collab DOUBLE PRECISION ,
prs_freq_s_event DOUBLE PRECISION ,
prs_freq_s_new_arri DOUBLE PRECISION ,
prs_freq_s_new_cust DOUBLE PRECISION ,
prs_freq_s_reward DOUBLE PRECISION ,
prs_freq_s_reengage DOUBLE PRECISION ,
prs_freq_s_survey DOUBLE PRECISION ,
prs_freq_s_abdn_cart DOUBLE PRECISION ,
prs_freq_s_rtn_cust DOUBLE PRECISION ,
prs_freq_o_artcollab DOUBLE PRECISION ,
prs_freq_o_collab DOUBLE PRECISION ,
prs_freq_o_event DOUBLE PRECISION ,
prs_freq_o_new_arri DOUBLE PRECISION ,
prs_freq_o_new_cust DOUBLE PRECISION ,
prs_freq_o_reward DOUBLE PRECISION ,
prs_freq_o_reengage DOUBLE PRECISION ,
prs_freq_o_survey DOUBLE PRECISION ,
prs_freq_o_abdn_cart DOUBLE PRECISION ,
prs_freq_o_rtn_cust DOUBLE PRECISION ,
prs_freq_c_artcollab DOUBLE PRECISION ,
prs_freq_c_collab DOUBLE PRECISION ,
prs_freq_c_event DOUBLE PRECISION ,
prs_freq_c_new_arri DOUBLE PRECISION ,
prs_freq_c_new_cust DOUBLE PRECISION ,
prs_freq_c_reward DOUBLE PRECISION ,
prs_freq_c_reengage DOUBLE PRECISION ,
prs_freq_c_survey DOUBLE PRECISION ,
prs_freq_c_abdn_cart DOUBLE PRECISION ,
prs_freq_c_rtn_cust DOUBLE PRECISION ,
prs_pct_o_artcollab DOUBLE PRECISION ,
prs_pct_o_collab DOUBLE PRECISION ,
prs_pct_o_event DOUBLE PRECISION ,
prs_pct_o_new_arri DOUBLE PRECISION ,
prs_pct_o_new_cust DOUBLE PRECISION ,
prs_pct_o_reward DOUBLE PRECISION ,
prs_pct_o_reengage DOUBLE PRECISION ,
prs_pct_o_survey DOUBLE PRECISION ,
prs_pct_o_abdn_cart DOUBLE PRECISION ,
prs_pct_o_rtn_cust DOUBLE PRECISION ,
prs_pct_c_artcollab DOUBLE PRECISION ,
prs_pct_c_collab DOUBLE PRECISION ,
prs_pct_c_event DOUBLE PRECISION ,
prs_pct_c_new_arri DOUBLE PRECISION ,
prs_pct_c_new_cust DOUBLE PRECISION ,
prs_pct_c_reward DOUBLE PRECISION ,
prs_pct_c_reengage DOUBLE PRECISION ,
prs_pct_c_survey DOUBLE PRECISION ,
prs_pct_c_abdn_cart DOUBLE PRECISION ,
prs_pct_c_rtn_cust DOUBLE PRECISION ,
chnl_md2o_retail DOUBLE PRECISION ,
chnl_md2o_ecom DOUBLE PRECISION ,
chnl_md2c_retail DOUBLE PRECISION ,
chnl_md2c_ecom DOUBLE PRECISION ,
chnl_dsinco_retail DOUBLE PRECISION ,
chnl_dsinco_ecom DOUBLE PRECISION ,
chnl_freq_s_retail DOUBLE PRECISION ,
chnl_freq_s_ecom DOUBLE PRECISION ,
chnl_freq_o_retail DOUBLE PRECISION ,
chnl_freq_o_ecom DOUBLE PRECISION ,
chnl_freq_c_retail DOUBLE PRECISION ,
chnl_freq_c_ecom DOUBLE PRECISION ,
chnl_pct_o_retail DOUBLE PRECISION ,
chnl_pct_o_ecom DOUBLE PRECISION ,
chnl_pct_c_retail DOUBLE PRECISION ,
chnl_pct_c_ecom DOUBLE PRECISION ,
pcat_md2o_custom DOUBLE PRECISION ,
pcat_md2o_mte DOUBLE PRECISION ,
pcat_md2o_pnut DOUBLE PRECISION ,
pcat_md2c_custom DOUBLE PRECISION ,
pcat_md2c_mte DOUBLE PRECISION ,
pcat_md2c_pnut DOUBLE PRECISION ,
pcat_dsinco_custom DOUBLE PRECISION ,
pcat_dsinco_mte DOUBLE PRECISION ,
pcat_dsinco_pnut DOUBLE PRECISION ,
pcat_freq_s_custom DOUBLE PRECISION ,
pcat_freq_s_mte DOUBLE PRECISION ,
pcat_freq_s_pnut DOUBLE PRECISION ,
pcat_freq_o_custom DOUBLE PRECISION ,
pcat_freq_o_mte DOUBLE PRECISION ,
pcat_freq_o_pnut DOUBLE PRECISION ,
pcat_freq_c_custom DOUBLE PRECISION ,
pcat_freq_c_mte DOUBLE PRECISION ,
pcat_freq_c_pnut DOUBLE PRECISION ,
pcat_pct_o_custom DOUBLE PRECISION ,
pcat_pct_o_mte DOUBLE PRECISION ,
pcat_pct_o_pnut DOUBLE PRECISION ,
pcat_pct_c_custom DOUBLE PRECISION ,
pcat_pct_c_mte DOUBLE PRECISION ,
pcat_pct_c_pnut DOUBLE PRECISION ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.csv_vans_zeta_inputs (select * from whousep.csv_vans_zeta_inputs);

DROP TABLE IF EXISTS vfap_retail.cust;
CREATE TABLE IF NOT EXISTS vfap_retail.cust(
sas_brand_id INTEGER ,
customer_id INTEGER ,
customer_no BIGINT ,
first_name VARCHAR(34) ,
last_name VARCHAR(51) ,
email_address VARCHAR(111) ,
opt_in_flag INTEGER ,
store_no BIGINT ,
language_code VARCHAR(5) ,
alpha_key VARCHAR(24) ,
gender VARCHAR(2) ,
create_source VARCHAR(17) ,
landmark_date_a TIMESTAMP WITHOUT TIME ZONE ,
create_date TIMESTAMP WITHOUT TIME ZONE ,
last_update_date TIMESTAMP WITHOUT TIME ZONE ,
sales_associate_no INTEGER ,
head_of_household_flag VARCHAR(9) ,
opt_in_date TIMESTAMP WITHOUT TIME ZONE ,
segmentation_flag_a VARCHAR(9) ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cust (select * from whousep.cust);

DROP TABLE IF EXISTS vfap_retail.cust_alt_key;
CREATE TABLE IF NOT EXISTS vfap_retail.cust_alt_key(
sas_brand_id INTEGER ,
customer_id INTEGER ,
alternate_key VARCHAR(27) ,
alternate_key_code VARCHAR(4) ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cust_alt_key (select * from whousep.cust_alt_key);

DROP TABLE IF EXISTS vfap_retail.cust_attribute;
CREATE TABLE IF NOT EXISTS vfap_retail.cust_attribute(
sas_brand_id INTEGER ,
customer_id INTEGER ,
attribute_grouping_code VARCHAR(4) ,
attribute_code VARCHAR(5) ,
attribute_comment VARCHAR(61) ,
attribute_value DOUBLE PRECISION , --changed data type
attribute_date TIMESTAMP WITHOUT TIME ZONE ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cust_attribute (select * from whousep.cust_attribute);

DROP TABLE IF EXISTS vfap_retail.cust_xref;
CREATE TABLE IF NOT EXISTS vfap_retail.cust_xref(
sas_brand_id INTEGER ,
old_customer_no BIGINT ,
new_customer_no BIGINT ,
last_update_date TIMESTAMP WITHOUT TIME ZONE ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cust_xref (select * from whousep.cust_xref);

DROP TABLE IF EXISTS vfap_retail.cust_xref_final;
CREATE TABLE IF NOT EXISTS vfap_retail.cust_xref_final(
sas_brand_id INTEGER ,
customer_no BIGINT ,
customer_id INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.cust_xref_final (select * from whousep.cust_xref_final);

DROP TABLE IF EXISTS vfap_retail.dept;
CREATE TABLE IF NOT EXISTS vfap_retail.dept(
department_code INTEGER ,
department_short_description VARCHAR(14) ,
department_description VARCHAR(27) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.dept (select * from whousep.dept);


--dim_period is not in file

DROP TABLE IF EXISTS vfap_retail.dq_check;
CREATE TABLE IF NOT EXISTS vfap_retail.dq_check(
program_name VARCHAR(40) ,
input_tbl VARCHAR(60) ,
date_time TIMESTAMP WITHOUT TIME ZONE ,
dq_severity_level INTEGER ,
dq_description VARCHAR(60) ,
counts INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.dq_check (select * from whousep.dq_check);

DROP TABLE IF EXISTS vfap_retail.email_xref;
CREATE TABLE IF NOT EXISTS vfap_retail.email_xref(
email_address VARCHAR(111) ,
customer_id INTEGER ,
sas_brand_id INTEGER ,
process_dtm TIMESTAMP 
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.email_xref (select * from whousep.email_xref);

--etl_file_broker not required


CREATE TABLE IF NOT EXISTS vfap_retail.etl_file_received( 
origination VARCHAR(3) ,
received_folder_name VARCHAR(128) ,
file_name VARCHAR(128) ,
file_size BIGINT ,
file_ts TIMESTAMP WITHOUT TIME ZONE ,
event VARCHAR(32) ,
chng_ts TIMESTAMP WITHOUT TIME ZONE 
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.etl_file_received (select * from whousep.etl_file_received);

--vfap_retail.etl_file_sent schema is not present

--vf_retial.etl_file_status schema is not present

DROP TABLE IF EXISTS vfap_retail.etl_parm;
CREATE TABLE IF NOT EXISTS vfap_retail.etl_parm(
key1 VARCHAR(20) ,
key2 VARCHAR(20) ,
num_value INTEGER ,
char_value VARCHAR(100) ,
description VARCHAR(100) ,
decimal_val DOUBLE PRECISION ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.etl_parm (select * from whousep.etl_parm);

DROP table vfap_retail.etl_rpt_min_max_date;
CREATE TABLE IF NOT EXISTS vfap_retail.etl_rpt_min_max_date(
table_name VARCHAR(30) ,
column_checked VARCHAR(30) ,
sas_brand_id varchar(1) ,
min_dt TIMESTAMP WITHOUT TIME ZONE ,
max_dt TIMESTAMP WITHOUT TIME ZONE ,
total_missing_dates INTEGER ,
total_cnt BIGINT ,
process_dtm TIMESTAMP
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.etl_rpt_min_max_date (select * from whousep.etl_rpt_min_max_date);

DROP TABLE IF EXISTS vfap_retail.etl_rpt_missing_date;
CREATE TABLE IF NOT EXISTS vfap_retail.etl_rpt_missing_date(
table_name VARCHAR(30) ,
sas_brand_id VARCHAR(1) ,
missing_date TIMESTAMP WITHOUT TIME ZONE ,
process_dtm TIMESTAMP default null
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.etl_rpt_missing_date (select * from whousep.etl_rpt_missing_date);

DROP TABLE IF EXISTS vfap_retail.event_xref;
CREATE TABLE IF NOT EXISTS vfap_retail.event_xref(
attribute_grouping_code VARCHAR(4) ,
attribute_code VARCHAR(5) ,
attribute_description VARCHAR(30) ,
"primary" VARCHAR(28) ,
secondary1 VARCHAR(19) ,
secondary2 VARCHAR(19) ,
secondary3 VARCHAR(13) ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.event_xref (select * from whousep.event_xref);

DROP TABLE IF EXISTS whousep.experian_behavior;
CREATE TABLE IF NOT EXISTS whousep.experian_behavior(
customer_no BIGINT ,
first_name VARCHAR(57) ,
last_name VARCHAR(69) ,
email_address VARCHAR(144) ,
mailresponder_indiv VARCHAR(3) ,
multicodmresp_hh VARCHAR(3) ,
multicategorybuyer VARCHAR(3) ,
dmcat_giftgadget INTEGER ,
dmcat_collspcfood INTEGER ,
dmcat_books INTEGER ,
dmcat_gardenfarm INTEGER ,
dmcat_craftshobbies INTEGER ,
dmcat_femaleorient INTEGER ,
dmcat_maleorient INTEGER ,
dmcat_upscale INTEGER ,
dmcat_general INTEGER ,
magbyrcat_healthfit INTEGER ,
magbyrcat_culinary INTEGER ,
magbyrcat_gardenfarm INTEGER ,
magbyrcat_religious INTEGER ,
magbyrcat_malesport INTEGER ,
magbyrcat_female INTEGER ,
magbyrcat_familygen INTEGER ,
contribcat_general INTEGER ,
contribcat_health INTEGER ,
contribcat_political INTEGER ,
contribcat_religious INTEGER ,
sweepstakes INTEGER ,
do_it_yourselfers INTEGER ,
news_financial INTEGER ,
photography INTEGER ,
mailrespond_oddsends INTEGER ,
mailrespond_misc INTEGER ,
political_affiliation VARCHAR(6) ,
firsttimehmebuyr_enh INTEGER ,
interest_in_golf VARCHAR(3) ,
contrib_to_charities VARCHAR(3) ,
pet_enthusiast VARCHAR(3) ,
z_culturalarts VARCHAR(3) ,
mail_order_buyer VARCHAR(3) ,
z_int_in_fitness VARCHAR(3) ,
z_int_in_outdoors VARCHAR(3) ,
z_int_in_travel VARCHAR(3) ,
z_investors VARCHAR(3) ,
presence_of_auto VARCHAR(3) ,
presence_creditcard VARCHAR(3) ,
z_int_gardening VARCHAR(3) ,
z_int_crafts VARCHAR(3) ,
z_collectors VARCHAR(3) ,
z_cruise_enthusiasts VARCHAR(3) ,
z_int_sports VARCHAR(3) ,
z_int_gourmet_cook VARCHAR(3) ,
z_sweepstakes_gambling VARCHAR(3) ,
z_int_politics VARCHAR(3) ,
z_int_music VARCHAR(3) ,
z_int_reading VARCHAR(3) ,
z_childparentingprod VARCHAR(3) ,
z_do_it_yourselfer VARCHAR(3) ,
z_self_improve VARCHAR(3) ,
z_int_religion VARCHAR(3) ,
z_grandparent VARCHAR(3) ,
z_int_clothing VARCHAR(3) ,
z_donate_environment VARCHAR(3) ,
z_investmutualfunds VARCHAR(3) ,
z_weight_conscious VARCHAR(3) ,
z_mailordermultibuyer VARCHAR(3) ,
z_pres_premiumcc VARCHAR(3) ,
z_dog_enthusiasts VARCHAR(3) ,
z_cat_enthusiasts VARCHAR(3) ,
z_healthy_living VARCHAR(3) ,
z_int_automobile VARCHAR(3) ,
z_int_skiing VARCHAR(3) ,
z_int_boating VARCHAR(3) ,
z_present_cellphone VARCHAR(3) ,
z_comm_connectivity VARCHAR(3) ,
z_comp_peripherals VARCHAR(3) ,
z_hi_tech_owner VARCHAR(3) ,
z_homedecor_furnish VARCHAR(3) ,
z_homeenter_tv_video VARCHAR(3) ,
z_kitchaidsmapplianc VARCHAR(3) ,
z_mailorder_musicvideo VARCHAR(3) ,
z_mailorder_booksmags VARCHAR(3) ,
z_mailorderclothshoe VARCHAR(3) ,
z_mailorder_insfin VARCHAR(3) ,
z_mailorder_gifts VARCHAR(3) ,
z_mailorder_garden VARCHAR(3) ,
z_mailorder_jewelcos VARCHAR(3) ,
z_music_classopera VARCHAR(3) ,
z_music_country VARCHAR(3) ,
z_music_christian VARCHAR(3) ,
z_music_rock VARCHAR(3) ,
z_interntonlne_subsc VARCHAR(3) ,
z_photography VARCHAR(3) ,
z_pur_via_online VARCHAR(3) ,
z_int_afflulifestyle VARCHAR(3) ,
z_domestic_traveler VARCHAR(3) ,
z_foreign_traveler VARCHAR(3) ,
z_contactlenswearer VARCHAR(3) ,
z_prescrip_druguser VARCHAR(3) ,
z_int_videodvd VARCHAR(3) ,
z_active_military VARCHAR(3) ,
z_inactive_military VARCHAR(3) ,
morbank_dedcathit INTEGER ,
morbank_nondedcathit INTEGER ,
political_affil_2 VARCHAR(2) ,
political_affil_3 VARCHAR(2) ,
political_affil_4 VARCHAR(2) ,
political_affil_5 VARCHAR(2) ,
political_affil_6 VARCHAR(2) ,
political_affil_7 VARCHAR(2) ,
political_affil_8 VARCHAR(2) ,
through_the_mail VARCHAR(3) ,
other_collectibles VARCHAR(3) ,
art_antiques VARCHAR(3) ,
stamps_coins VARCHAR(3) ,
dolls VARCHAR(3) ,
figurines VARCHAR(3) ,
sports_memorabilia VARCHAR(3) ,
cooking VARCHAR(3) ,
baking VARCHAR(3) ,
cooking_weightcons VARCHAR(3) ,
wine_appreciation VARCHAR(3) ,
cooking_gourmet VARCHAR(3) ,
crafts VARCHAR(3) ,
knitting_needlework VARCHAR(3) ,
quilting VARCHAR(3) ,
sewing VARCHAR(3) ,
woodworking VARCHAR(3) ,
losing_weight VARCHAR(3) ,
vitamin_supplements VARCHAR(3) ,
health_naturalfoods VARCHAR(3) ,
hobby_photography VARCHAR(3) ,
hobby_gardening VARCHAR(3) ,
home_workshop_diy VARCHAR(3) ,
cars_auto_repair VARCHAR(3) ,
bird_watching VARCHAR(3) ,
self_improvement VARCHAR(3) ,
christian_gospel VARCHAR(3) ,
r_and_b VARCHAR(3) ,
jazz_newage VARCHAR(3) ,
classical VARCHAR(3) ,
rock_n_roll VARCHAR(3) ,
country VARCHAR(3) ,
music_general VARCHAR(3) ,
other_music VARCHAR(3) ,
best_selling_fiction VARCHAR(3) ,
bible_religious VARCHAR(3) ,
childrensreading VARCHAR(3) ,
computer VARCHAR(3) ,
cooking_culinary VARCHAR(3) ,
country_lifestyle VARCHAR(3) ,
entertainment_people VARCHAR(3) ,
fashion VARCHAR(3) ,
history VARCHAR(3) ,
interior_decorating VARCHAR(3) ,
medical_health VARCHAR(3) ,
military VARCHAR(3) ,
mystery VARCHAR(3) ,
naturalhlth_remedies VARCHAR(3) ,
romance VARCHAR(3) ,
science_fiction VARCHAR(3) ,
science_technology VARCHAR(3) ,
sports_reading VARCHAR(3) ,
worldnews_politics VARCHAR(3) ,
book_reader VARCHAR(3) ,
animal_welfare_socl VARCHAR(3) ,
environment_wildlife VARCHAR(3) ,
political_conserve VARCHAR(3) ,
political_liberal VARCHAR(3) ,
religious_socialconc VARCHAR(3) ,
children VARCHAR(3) ,
veterans VARCHAR(3) ,
health_social_conc VARCHAR(3) ,
other_social_conc VARCHAR(3) ,
sportsrec_baseball VARCHAR(3) ,
sportsrec_basketball VARCHAR(3) ,
sportsrec_hockey VARCHAR(3) ,
sportsrec_camp_hike VARCHAR(3) ,
sportsrec_hunting VARCHAR(3) ,
sportsrec_fishing VARCHAR(3) ,
sportsrec_nascar VARCHAR(3) ,
sportsrec_per_fitexr VARCHAR(3) ,
sportsrec_scuba_dive VARCHAR(3) ,
sportsrec_football VARCHAR(3) ,
sportsrec_golf VARCHAR(3) ,
sportsrec_snowskibrd VARCHAR(3) ,
sportsrec_boat_sail VARCHAR(3) ,
sportsrec_walking VARCHAR(3) ,
sportsrec_cycling VARCHAR(3) ,
sportsrec_motorcycle VARCHAR(3) ,
sportsrec_run_jog VARCHAR(3) ,
sportsrec_soccer VARCHAR(3) ,
sportsrec_swim VARCHAR(3) ,
playsports_general VARCHAR(3) ,
sweepstakes2 VARCHAR(3) ,
lotteries VARCHAR(3) ,
casino_gambling VARCHAR(3) ,
cruise VARCHAR(3) ,
international VARCHAR(3) ,
domestic VARCHAR(3) ,
time_share VARCHAR(3) ,
recreational_vehicle VARCHAR(3) ,
enjoy_rv_travel VARCHAR(3) ,
business_travel VARCHAR(3) ,
personal_travel VARCHAR(3) ,
own_computer VARCHAR(3) ,
use_internet_service VARCHAR(3) ,
useinternetdsl_hspd VARCHAR(3) ,
plan_to_buy_computer VARCHAR(3) ,
cell_phone VARCHAR(3) ,
compact_disc_player VARCHAR(3) ,
dvd_player VARCHAR(3) ,
satellite_dish VARCHAR(3) ,
digital_camera VARCHAR(3) ,
hdtv VARCHAR(3) ,
int_electronics VARCHAR(3) ,
personal_data_asst VARCHAR(3) ,
video_camera VARCHAR(3) ,
video_game_system VARCHAR(3) ,
arts_int_culturlarts VARCHAR(3) ,
business_finance VARCHAR(3) ,
childrens_magazines VARCHAR(3) ,
computer_electronics VARCHAR(3) ,
crafts_games_hobbies VARCHAR(3) ,
fitness VARCHAR(3) ,
food_wine_cooking VARCHAR(3) ,
gardening_magazines VARCHAR(3) ,
hunting_fishing VARCHAR(3) ,
mens VARCHAR(3) ,
music VARCHAR(3) ,
parenting_babies VARCHAR(3) ,
sports_magazines VARCHAR(3) ,
subscription VARCHAR(3) ,
travel VARCHAR(3) ,
womens VARCHAR(3) ,
currentevents_news VARCHAR(3) ,
have_leased_vehicle VARCHAR(3) ,
havepurchasedvehicle VARCHAR(3) ,
book_club VARCHAR(3) ,
music_club VARCHAR(3) ,
amer_express_premium VARCHAR(3) ,
amer_express_regular VARCHAR(3) ,
discover_premium VARCHAR(3) ,
discover_regular VARCHAR(3) ,
othercard_premium VARCHAR(3) ,
othercard_regular VARCHAR(3) ,
store_retail_regular VARCHAR(3) ,
visa_regular VARCHAR(3) ,
mastercard_regular VARCHAR(3) ,
humanitarian VARCHAR(3) ,
buyprerecrded_videos VARCHAR(3) ,
watch_cable_tv VARCHAR(3) ,
watch_videos VARCHAR(3) ,
cds_moneymkt_current VARCHAR(3) ,
iras_current VARCHAR(3) ,
iras_future_interest VARCHAR(3) ,
life_insur_current VARCHAR(3) ,
mutual_funds_current VARCHAR(3) ,
mutualfunds_future VARCHAR(3) ,
otherinvestmt_curr VARCHAR(3) ,
otherinvestmt_future VARCHAR(3) ,
real_estate_current VARCHAR(3) ,
real_estate_future VARCHAR(3) ,
stocks_bonds_current VARCHAR(3) ,
stocks_bonds_future VARCHAR(3) ,
proud_grandparent VARCHAR(3) ,
purchase_via_internet VARCHAR(3) ,
active_military_mbr VARCHAR(3) ,
vetern VARCHAR(3) ,
own_a_cat VARCHAR(3) ,
own_a_dog VARCHAR(3) ,
own_a_pet VARCHAR(3) ,
shop_by_internet VARCHAR(3) ,
shop_by_mail VARCHAR(3) ,
shop_by_catalog VARCHAR(3) ,
apparel VARCHAR(3) ,
computerorelctronics VARCHAR(3) ,
books_music VARCHAR(3) ,
home_garden VARCHAR(3) ,
sports_related VARCHAR(3) ,
big_tall VARCHAR(3) ,
mailorder_books_mag VARCHAR(3) ,
mailorder_clothing VARCHAR(3) ,
mailorder_gardening VARCHAR(3) ,
mailorder_gift VARCHAR(3) ,
mailorder_jewel_cosm VARCHAR(3) ,
mailorder_music_vid VARCHAR(3) ,
mailorder_child_prod VARCHAR(3) ,
int_amuseparkvisit INTEGER ,
int_zoo_visit INTEGER ,
int_coffeeconnoisseu INTEGER ,
int_winelovers INTEGER ,
int_doityourselfers INTEGER ,
int_homeimprve_spndr INTEGER ,
hunting_enthusiasts INTEGER ,
buyer_laptopowner INTEGER ,
buyer_secursysowner INTEGER ,
buyer_tabletowner INTEGER ,
buyer_couponuser INTEGER ,
buyer_luxuryshopper INTEGER ,
buyer_yngadultcloth INTEGER ,
buyer_supercenter INTEGER ,
buyer_warehouseclub INTEGER ,
aarp_members INTEGER ,
life_insur_policy INTEGER ,
medical_policy INTEGER ,
medicare_policy INTEGER ,
digital_magnewspaper INTEGER ,
attnds_educationprog INTEGER ,
video_gamer INTEGER ,
mlb_enthusiast INTEGER ,
nascar_enthusiast INTEGER ,
nba_enthusiast INTEGER ,
nfl_enthusiast INTEGER ,
nhl_enthusiast INTEGER ,
pga_tour_enthusiast INTEGER ,
politicaltv_liberal INTEGER ,
politictv_libcomedy INTEGER ,
politicaltv_conserva INTEGER ,
eats_family_rest INTEGER ,
eats_fast_food INTEGER ,
canoeing_kayaking INTEGER ,
int_play_golf INTEGER ,
presence_automobile INTEGER ,
loyalty_card_user INTEGER ,
luxuryhomegood_shop INTEGER ,
union_member INTEGER ,
have_retirement_plan INTEGER ,
online_trading INTEGER ,
have_grandchildren INTEGER ,
nondept_store_makeup INTEGER ,
int_gourmet_cooking INTEGER ,
int_cat_owner INTEGER ,
int_dog_owner INTEGER ,
int_arts_crafts INTEGER ,
int_scrapbooking INTEGER ,
int_cultural_arts INTEGER ,
hobbies_gardening INTEGER ,
int_photography INTEGER ,
int_book_reader INTEGER ,
int_ebook_reader INTEGER ,
int_audiobk_listener INTEGER ,
int_pet_enthusiast INTEGER ,
int_music_download INTEGER ,
int_music_streaming INTEGER ,
int_avid_runners INTEGER ,
int_outdoor_enthusia INTEGER ,
int_fishing INTEGER ,
int_snowsports INTEGER ,
int_boating INTEGER ,
int_playshockey INTEGER ,
int_plays_soccer INTEGER ,
int_plays_tennis INTEGER ,
int_sportsenthusiast INTEGER ,
int_healthy_living INTEGER ,
int_fitnessenthusias INTEGER ,
int_on_a_diet INTEGER ,
int_weight_conscious INTEGER ,
buyer_highendspirits INTEGER ,
int_casinogambling INTEGER ,
int_swpstakeslottery INTEGER ,
hifreq_business_trvl INTEGER ,
hifreq_cruise_enthus INTEGER ,
hifreq_domestic_vac INTEGER ,
hifreq_foreign_vac INTEGER ,
freq_flyer_prg_mbr INTEGER ,
hotelguest_loyaprg INTEGER ,
contrib_charities INTEGER ,
contrib_artsculture INTEGER ,
contrib_education INTEGER ,
contrib_health INTEGER ,
contrib_political INTEGER ,
contrib_prvt_found INTEGER ,
contrib_volunteering INTEGER ,
debit_card_user INTEGER ,
corp_credit_crd_user INTEGER ,
maj_credit_crd_user INTEGER ,
prem_credit_crd_user INTEGER ,
credit_card_user INTEGER ,
store_creditcrd_user INTEGER ,
brokerage_acct_owner INTEGER ,
active_investor INTEGER ,
mutual_fund_investor INTEGER ,
deptstore_makeupuser INTEGER ,
int_christian_music INTEGER ,
int_classical_music INTEGER ,
int_country_music INTEGER ,
int_music INTEGER ,
int_oldies_music INTEGER ,
int_rock_music INTEGER ,
int_80s_music INTEGER ,
int_hiphopmusic INTEGER ,
int_alternativemusic INTEGER ,
int_jazz_music INTEGER ,
int_pop_music INTEGER ,
interest_in_religion INTEGER ,
military_active INTEGER ,
military_inactive INTEGER ,
working_couples INTEGER ,
poc_0_3_yrs_gender VARCHAR(3) ,
poc_4_6_yrs_gender VARCHAR(3) ,
poc_7_9_yrs_gender VARCHAR(3) ,
poc_10_12_yrs_gender VARCHAR(3) ,
poc_13_15_yrs_gender VARCHAR(3) ,
poc_16_18_yrs_gender VARCHAR(3) ,
discret_spend_level VARCHAR(3) ,
discret_spend_score INTEGER ,
p1_birthdt_indiv INTEGER ,
p1_combage_indiv VARCHAR(9) ,
p1_gender_indiv VARCHAR(3) ,
p1_marital_status VARCHAR(6) ,
recip_reliability_cd INTEGER ,
p1_pertype_indiv VARCHAR(3) ,
combined_homeowner VARCHAR(3) ,
dwelling_type VARCHAR(3) ,
length_of_residence INTEGER ,
dwellingunit_size_cd VARCHAR(3) ,
number_child_ltet18 INTEGER ,
nbr_adults_in_hh INTEGER ,
p2_person_type VARCHAR(3) ,
p2_name_first VARCHAR(45) ,
p2_name_mid_init VARCHAR(45) ,
p2_name_last VARCHAR(60) ,
p2_name_title VARCHAR(18) ,
p2_name_surnamesffx VARCHAR(12) ,
p2_gender_cd VARCHAR(3) ,
p2_combined_age VARCHAR(9) ,
p2_birthdt_ccyymm INTEGER ,
p3_person_type VARCHAR(3) ,
p3_name_first VARCHAR(45) ,
p3_name_mid_init VARCHAR(45) ,
p3_name_last VARCHAR(60) ,
p3_name_title VARCHAR(18) ,
p3_name_surnamesffx VARCHAR(12) ,
p3_gender_cd VARCHAR(3) ,
p3_combined_age VARCHAR(9) ,
p3_birthdt_ccyymm INTEGER ,
p4_person_type VARCHAR(3) ,
p4_name_first VARCHAR(45) ,
p4_name_mid_init VARCHAR(45) ,
p4_name_last VARCHAR(60) ,
p4_name_title VARCHAR(18) ,
p4_name_surnamesffx VARCHAR(12) ,
p4_gender_cd VARCHAR(3) ,
p4_combined_age VARCHAR(9) ,
p4_birthdt_ccyymm INTEGER ,
p5_person_type VARCHAR(3) ,
p5_name_first VARCHAR(45) ,
p5_name_mid_init VARCHAR(45) ,
p5_name_last VARCHAR(60) ,
p5_name_title VARCHAR(18) ,
p5_name_surnamesffx VARCHAR(12) ,
p5_gender_cd VARCHAR(3) ,
p5_combined_age VARCHAR(9) ,
p5_birthdt_ccyymm INTEGER ,
p6_person_type VARCHAR(3) ,
p6_name_first VARCHAR(45) ,
p6_name_mid_init VARCHAR(36) ,
p6_name_last VARCHAR(60) ,
p6_name_title VARCHAR(18) ,
p6_name_surnamesffx VARCHAR(12) ,
p6_gender_cd VARCHAR(3) ,
p6_combined_age VARCHAR(9) ,
p6_birthdt_ccyymm INTEGER ,
p7_person_type VARCHAR(3) ,
p7_name_first VARCHAR(45) ,
p7_name_mid_init VARCHAR(33) ,
p7_name_last VARCHAR(57) ,
p7_name_title VARCHAR(12) ,
p7_name_surnamesffx VARCHAR(12) ,
p7_gender_cd VARCHAR(3) ,
p7_combined_age VARCHAR(9) ,
p7_birthdt_ccyymm INTEGER ,
p8_person_type VARCHAR(3) ,
p8_name_first VARCHAR(45) ,
p8_name_mid_init VARCHAR(30) ,
p8_name_last VARCHAR(60) ,
p8_name_title VARCHAR(12) ,
p8_name_surnamesffx VARCHAR(9) ,
p8_gender_cd VARCHAR(3) ,
p8_combined_age VARCHAR(9) ,
p8_birthdt_ccyymm INTEGER ,
p1_occupation VARCHAR(24) ,
p1_occupation_grp VARCHAR(6) ,
p1_education VARCHAR(24) ,
presofchild_age_0_3 VARCHAR(6) ,
presofchild_age_4_6 VARCHAR(6) ,
presofchild_age_7_9 VARCHAR(6) ,
presofchild_age10_12 VARCHAR(6) ,
presofchild_age13_15 VARCHAR(6) ,
presofchild_age16_18 VARCHAR(6) ,
presofchild_age_0_18 VARCHAR(6) ,
home_business_ind VARCHAR(3) ,
p1_businessownerflg VARCHAR(3) ,
est_curr_home_value VARCHAR(24) ,
multiple_realty_prop VARCHAR(3) ,
mosaic_household VARCHAR(9) ,
est_household_income VARCHAR(3) ,
p1_retail_shoppers VARCHAR(24) ,
consumview_prfitscr INTEGER ,
cs_combined VARCHAR(3) ,
cs_clothing VARCHAR(3) ,
cs_entertainment VARCHAR(3) ,
cs_travel VARCHAR(3) ,
retail_demand_20200 INTEGER ,
retail_demand_20220 INTEGER ,
retail_demand_20240 INTEGER ,
retail_demand_20260 INTEGER ,
retail_demand_20530 INTEGER ,
retail_demand_20580 INTEGER ,
retail_demand_448 INTEGER ,
retail_demand_4481 INTEGER ,
retail_demand_44811 INTEGER ,
retail_demand_44812 INTEGER ,
retail_demand_44813 INTEGER ,
retail_demand_44814 INTEGER ,
retail_demand_44815 INTEGER ,
retail_demand_44819 INTEGER ,
retail_demand_451 INTEGER ,
retail_demand_4511 INTEGER ,
retail_demand_45111 INTEGER ,
avg_scorex_plus INTEGER ,
median_scorex_plus INTEGER ,
badvsgood_credit_seg INTEGER ,
scps_avg_taps_spend INTEGER ,
scpsavg_taps_payrate INTEGER ,
online_apparel INTEGER ,
online_shoes INTEGER ,
online_outdrsftgoods INTEGER ,
online_outdrhrdgoods INTEGER ,
ltd_best_recency TIMESTAMP WITHOUT TIME ZONE ,
ltd_total_dollars INTEGER ,
ltd_avg_dollar_pur INTEGER ,
ltc_credit_pur INTEGER ,
ltd_purchase_freq INTEGER ,
month_24_credit_pur INTEGER ,
month_24_recency_cd INTEGER ,
month_24_freq_cd INTEGER ,
month_24_dollar_cd INTEGER ,
month_24_avgdollarcd INTEGER ,
w_hiend_apparelrecen TIMESTAMP WITHOUT TIME ZONE ,
w_hiend_apparelfreq VARCHAR(24) ,
w_hiend_appareldolla VARCHAR(24) ,
w_hiend_apparelscore VARCHAR(24) ,
w_mid_apparelrecen VARCHAR(24) ,
w_mid_apparelfreq INTEGER ,
w_mid_appareldolla INTEGER ,
w_mid_apparelscore INTEGER ,
w_low_apparelrecen TIMESTAMP WITHOUT TIME ZONE ,
w_low_apparelfreq INTEGER ,
w_low_appareldolla INTEGER ,
w_low_apparelscore INTEGER ,
w_cas_apparelrecen TIMESTAMP WITHOUT TIME ZONE ,
w_cas_apparelfreq INTEGER ,
w_cas_appareldolla INTEGER ,
w_cas_apparelscore INTEGER ,
w_plus_apparelrecen TIMESTAMP WITHOUT TIME ZONE ,
w_plus_apparelfreq INTEGER ,
w_plus_appareldolla INTEGER ,
w_plus_apparelscore INTEGER ,
w_athle_apparelrecen TIMESTAMP WITHOUT TIME ZONE ,
w_athle_apparelfreq INTEGER ,
w_athle_appareldolla INTEGER ,
w_athle_apparelscore INTEGER ,
m_cas_apparelrecen TIMESTAMP WITHOUT TIME ZONE ,
m_cas_apparelfreq INTEGER ,
m_cas_appareldolla INTEGER ,
m_cas_apparelscore INTEGER ,
child_apparelrecen TIMESTAMP WITHOUT TIME ZONE ,
child_apparelfreq INTEGER ,
child_appareldolla INTEGER ,
child_apparelscore INTEGER ,
active_outdoor_recen TIMESTAMP WITHOUT TIME ZONE ,
active_outdoor_freq INTEGER ,
active_outdoor_dolla INTEGER ,
active_outdoor_score INTEGER ,
x_snowsports_recen TIMESTAMP WITHOUT TIME ZONE ,
x_snowsports_freq INTEGER ,
x_snowsports_dolla INTEGER ,
x_snowsports_score INTEGER ,
mth_0_3_trans_freq INTEGER ,
mth_0_3_trans_dollar INTEGER ,
mth_4_6_trans_freq INTEGER ,
mth_4_6_trans_dollar INTEGER ,
mth_7_9_trans_freq INTEGER ,
mth_7_9_trans_dollar INTEGER ,
mth_10_12_trans_freq INTEGER ,
mth_10_12_trans_doll INTEGER ,
mth_13_18_trans_freq INTEGER ,
mth_13_18_trans_doll INTEGER ,
mth_19_24_trans_freq INTEGER ,
mth_19_24_trans_doll INTEGER ,
most_recent_ordr_chan VARCHAR(3) ,
tt_brick_mortar INTEGER ,
tt_online_midhigh INTEGER ,
tt_e_tailer INTEGER ,
tt_online_discount INTEGER ,
tt_onlinebid_mrktplc INTEGER ,
tt_emailengagement INTEGER ,
p1_tt_emailengagemnt INTEGER ,
p2_tt_emailengagemnt INTEGER ,
p3_tt_emailengagemnt INTEGER ,
p4_tt_emailengagemnt INTEGER ,
p5_tt_emailengagemnt INTEGER ,
p6_tt_emailengagemnt INTEGER ,
p7_tt_emailengagemnt INTEGER ,
p8_tt_emailengagemnt INTEGER ,
tt_broadcast_cabletv INTEGER ,
tt_directmail INTEGER ,
tt_internetradio INTEGER ,
tt_mobile_display INTEGER ,
tt_mobile_video INTEGER ,
tt_online_video INTEGER ,
tt_online_display INTEGER ,
tt_online_streamtv INTEGER ,
tt_satelliteradio INTEGER ,
tt_buyamerican INTEGER ,
tt_showmethemoney INTEGER ,
tt_gowiththeflow INTEGER ,
tt_notimelikepresent INTEGER ,
tt_nvrshowupemptyhan INTEGER ,
tt_ontheroadagain INTEGER ,
tt_lookatmenow INTEGER ,
tt_stopsmellroses INTEGER ,
tt_workhardplayhard INTEGER ,
tt_pennysavedearned INTEGER ,
tt_its_all_in_name INTEGER ,
ethnicinsight_flag VARCHAR(3) ,
ethnicity_detail VARCHAR(6) ,
language VARCHAR(6) ,
religion VARCHAR(3) ,
e_tech_group VARCHAR(3) ,
country_of_origin INTEGER ,
totalenhanmatchtype VARCHAR(3) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.experian_behavior (select * from whousep.experian_behavior);

DROP TABLE IF EXISTS vfap_retail.experian_bronze;
CREATE TABLE IF NOT EXISTS vfap_retail.experian_bronze(
customer_id integer ,
customer_no bigint ,
first_name varchar(20) ,
last_name varchar(26) ,
loyalty varchar(5) ,
cbsa_code integer ,
cbsa_name varchar(56) ,
dma_code integer ,
dma_name varchar(50) ,
nearestoutletstorenumber integer ,
nearestoutletstorename varchar(42) ,
nearestoutletdistancemiles double precision ENCODE raw,
address_1 varchar(40) ,
address_2 varchar(11) ,
city varchar(26) ,
state varchar(2) ,
zip varchar(10) ,
nearestretailstorenumber integer ,
nearestretailstorename varchar(41) ,
nearestretaildistancemiles double precision ENCODE raw,
cass_addresstypecode varchar(2) ,
cass_addresstypestring varchar(11) ,
cass_results varchar(29) ,
email_address varchar(43) ,
opt_in_flag integer ,
mail_opt_in_flag integer ,
personidnumber bigint ,
persontype varchar(1) ,
fullname varchar(30) ,
middleinitialv2 varchar(2) ,
surname varchar(20) ,
namesuffix varchar(4) ,
nameprefix varchar(5) ,
gender varchar(1) ,
combinedage varchar(3) ,
educationmodel integer ,
maritalstatus varchar(2) ,
occupationgroupv2 varchar(2) ,
householdpersonnumber integer ,
firstnamelastname varchar(30) ,
addressid varchar(12) ,
fipsstatecode integer ,
stateabbreviation varchar(2) ,
fipszipcode varchar(5) ,
zip4 varchar(4) ,
deliverypointcode integer ,
carrierroute varchar(4) ,
shortcityname varchar(13) ,
cityname varchar(25) ,
housenumber varchar(10) ,
predirection varchar(2) ,
streetname varchar(28) ,
streetsuffix varchar(4) ,
postdirection varchar(2) ,
unitdesignator varchar(6) ,
unitdesignatornumber varchar(7) ,
primaryaddress varchar(30) ,
secondaryaddress varchar(13) ,
fipscountycode integer ,
countyname varchar(21) ,
cvmm_lat double precision ENCODE raw,
cvmm_lon double precision ENCODE raw,
matchlevelforgeodata varchar(2) ,
timezone integer ,
livingunitid varchar(10) ,
phone_specialusagephone varchar(10) ,
phone_number2 varchar(10) ,
dwellingunitsize varchar(1) ,
dwellingtype varchar(2) ,
hmownercombinedhmownerrenter varchar(1) ,
esthouseholdincomev5 varchar(1) ,
ncoamoveupdatecode integer ,
ncoamoveupdatedate varchar(8) ,
mailresponder varchar(1) ,
lengthofresidence integer ,
numberofpersonsinlivingunit integer ,
numberofadultsinlivingunit integer ,
ruralurbancountysizecode integer ,
activitydate varchar(8) ,
morbankupscalemerchandisebuyer integer ,
morbankmalemerchandisebuyer integer ,
morbankfemalemerchandisebuyer integer ,
morbkcraftshobbymerch_isebuyer integer ,
morbankgardeningfarmingbuyer integer ,
morbankbookbuyer integer ,
morbkcollectspecialfoodsbuyer integer ,
morbankgiftsandgadgetsbuyer integer ,
morbankgeneralmerchandisebuyer integer ,
morbkfamily_generalmagazine integer ,
morbankfemaleorientedmagazine integer ,
morbankmalesportsmagazine integer ,
morbankreligiousmagazine integer ,
morbkgardeningfarmingmagazine integer ,
morbkculinaryinterestsmagazine integer ,
morbkhealth_fitnessmagazine integer ,
morbankdoityourselfers integer ,
morbanknewsandfinancial integer ,
morbankphotography integer ,
morbankopportunityseekersandce integer ,
morbankreligiouscontributor integer ,
morbankpoliticalcontributor integer ,
morbkhealth_inscontributor integer ,
morbankgeneralcontributor integer ,
morbankmiscellaneous integer ,
morbankoddsandends integer ,
morbankdedupedcategoryhitcount integer ,
morbknondedupedcategoryhitcnt integer ,
mortgagehmpurhmpurprice integer ,
mortgagehmpurhmpurdt varchar(8) ,
propertyrealtyhomeyearbuilt integer ,
householdcomposition varchar(1) ,
corebasedstatisticalareascbsa varchar(5) ,
corebasedstatisticalareatype varchar(1) ,
childrenage018version3 varchar(2) ,
phone_activitydate varchar(8) ,
census2010tractandblockgroup varchar(7) ,
capeagepopmedianage integer ,
capeagepop017 integer ,
capeagepop1899 integer ,
capeagepop6599 integer ,
capebuilthumedianhsngunitage integer ,
capechildhhwithpersonslt18 integer ,
capechildhhmcfamwprsnslt18 integer ,
capechildhhmcfamwoprsnslt18 integer ,
capednstyprsnsperhhforpopinhh integer ,
capeeducispsa integer ,
capeeducispsadecile integer ,
capeeducpop25medianeduattained integer ,
capeethnicpopwhiteonly integer ,
capeethnicpopblackonly integer ,
capeethnicpopasianonly integer ,
capeethnicpophispanic integer ,
capehomvaloohumedianhomevalue integer ,
capehhsizehhaveragehldsize integer ,
capehustrhumobilehome integer ,
capeincfamilyincstatedecile integer ,
capeinchhmedianfamilyhldincome integer ,
capelanghhspanishspeaking integer ,
capetenancyocchuowneroccupied integer ,
capetenancyocchurenteroccupied integer ,
capetyphhmarriedcouplefamily integer ,
mosaichousehold varchar(3) ,
cvmacromatchgroup varchar(16) ,
cvmacromatchlevel varchar(1) ,
sas_brand_id integer ,
fs_sk integer ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.experian_bronze (select * from whousep.experian_bronze);

CREATE TABLE IF NOT EXISTS vfap_retail.experian_gold(
customer_id integer ,
customer_no BIGINT ,
first_name varchar(60) ,
last_name varchar(84) ,
i1mailresponderindiv varchar(6) ,
multicodirectmailresphh varchar(6) ,
multibuyermin551551 varchar(6) ,
giftgadgetdmmercbyrcat integer ,
colspcfooddmmercbyrcat integer ,
booksdmmercbyrcat integer ,
gardenfarmdmmercbyrcat integer ,
craftshobbiedmmercbyrcat integer ,
femaleorientdmmercbyrcat integer ,
maleorientdmmercbyrcat integer ,
upscaledmmercbyrcat integer ,
generaldmmercbyrcat integer ,
healthfitnessmagbyrcat integer ,
culinaryintmagbuyer integer ,
gardenfarmingmagbyrcat integer ,
religiousmagbyrcat integer ,
malesportorienmagbyrcat integer ,
femaleorientmagbyrcat integer ,
familygeneralmagbyrcat integer ,
generalcontribtrcat integer ,
healthinstcontribtrcat integer ,
politicalcontribtrcat integer ,
religiouscontribtrcat integer ,
sweepstakes integer ,
doityourselfers integer ,
newsfinancial integer ,
photography integer ,
oddsendsmailrespondr integer ,
miscmailresp integer ,
politicalaffiliation varchar(9) ,
firsttimehomebuy integer ,
interestingolf varchar(6) ,
contributestocharities varchar(6) ,
petenthusiast varchar(6) ,
interestinculturalarts varchar(6) ,
purchasedthroughthemail varchar(6) ,
interestinfitness varchar(6) ,
interestintheoutdoors varchar(6) ,
interestintravel varchar(6) ,
investors varchar(6) ,
presenceofautomobile varchar(6) ,
presenceofcreditcard varchar(6) ,
interestingardening varchar(6) ,
interestincrafts varchar(6) ,
collectors varchar(6) ,
cruiseenthusiasts varchar(6) ,
interestinsports varchar(6) ,
interestingourmetcooking varchar(6) ,
sweepstakesgambling varchar(6) ,
interestinpolitics varchar(6) ,
interestinmusic varchar(6) ,
interestinreading varchar(6) ,
childrenparentingproducts varchar(6) ,
doityourselfer varchar(6) ,
selfimprovement varchar(6) ,
interestinreligion varchar(6) ,
grandparent varchar(6) ,
interestinclothing varchar(6) ,
donatesenvironmentalcauses varchar(6) ,
investsmutualfundsannuities varchar(6) ,
weightconscious varchar(6) ,
mailordermultibuyer varchar(6) ,
presenceofpremiumcreditcard varchar(6) ,
dogenthusiasts varchar(6) ,
catenthusiasts varchar(6) ,
healthyliving varchar(6) ,
interestinautomotive varchar(6) ,
interestinskiing varchar(6) ,
interestinboating varchar(6) ,
presenceofcellphone varchar(6) ,
communicationconnectivity varchar(6) ,
computersperipherals varchar(6) ,
hitechowner varchar(6) ,
homedecoratingfurnishing varchar(6) ,
homeentertainmenttvvideo varchar(6) ,
kitchenaidssmallappliances varchar(6) ,
mailorderbuyermusicvideo varchar(6) ,
mailorderbuybooksmagazines varchar(6) ,
mailorderbuyclothingshoes varchar(6) ,
mailorderbuyinsfinance varchar(6) ,
mailorderbuyergifts varchar(6) ,
mailorderbuyergardening varchar(6) ,
mailorderbuyerjewelrycosm varchar(6) ,
classicaloperabigbandmusic varchar(6) ,
countrymusic varchar(6) ,
christianmusic varchar(6) ,
rockmusic varchar(6) ,
internetonlinesubscriber varchar(6) ,
interestinphotography varchar(6) ,
purchaseviaonline varchar(6) ,
interestinaffluentlifestyle varchar(6) ,
domestictraveler varchar(6) ,
foreigntraveler varchar(6) ,
contactlensewearer varchar(6) ,
prescriptiondruguser varchar(6) ,
interestinvideosdvd varchar(6) ,
activemilitary varchar(6) ,
inactivemilitary varchar(6) ,
morbankdedcategoryhitcnt integer ,
morbanknondedcategoryhit integer ,
politicalaffiliation2 varchar(9) ,
politicalaffiliation3 varchar(9) ,
politicalaffiliation4 varchar(9) ,
politicalaffiliation5 varchar(9) ,
politicalaffiliation6 varchar(9) ,
politicalaffiliation7 varchar(9) ,
politicalaffiliation8 varchar(9) ,
throughthemail varchar(6) ,
othercollectibles varchar(6) ,
artantiques varchar(6) ,
stampscoins varchar(6) ,
dolls varchar(6) ,
figurines varchar(6) ,
sportsmemorabilia varchar(6) ,
cooking varchar(6) ,
baking varchar(6) ,
cookingweightconscience varchar(6) ,
wineappreciation varchar(6) ,
cookinggourmet varchar(6) ,
crafts varchar(6) ,
knittingneedlework varchar(6) ,
quilting varchar(6) ,
sewing varchar(6) ,
woodworking varchar(6) ,
losingweight varchar(6) ,
includevitaminsupplements varchar(6) ,
healthandnaturalfoods varchar(6) ,
photographyhobbies varchar(6) ,
gardeninghobbies varchar(6) ,
homeworkshopdiy varchar(6) ,
carsandautorepair varchar(6) ,
birdwatching varchar(6) ,
self_improvement varchar(6) ,
christiangospel varchar(6) ,
randb varchar(6) ,
jazznewage varchar(6) ,
classical varchar(6) ,
rocknroll varchar(6) ,
country varchar(6) ,
musicingeneral varchar(6) ,
othermusic varchar(6) ,
bestsellingfiction varchar(6) ,
bibledevotionalreligious varchar(6) ,
childrensreading varchar(6) ,
computer varchar(6) ,
cookingculinary varchar(6) ,
countrylifestyle varchar(6) ,
entertainmentpeople varchar(6) ,
fashion varchar(6) ,
history varchar(6) ,
interiordecorating varchar(6) ,
medicalhealth varchar(6) ,
military varchar(6) ,
mystery varchar(6) ,
naturalhealthremedies varchar(6) ,
romance varchar(6) ,
sciencefiction varchar(6) ,
sciencetechnology varchar(6) ,
sportsreading varchar(6) ,
worldnewspolitics varchar(6) ,
bookreader varchar(6) ,
animalwelfaresoclcauseconc varchar(6) ,
environmentwildlife varchar(6) ,
politicalconservative varchar(6) ,
politicalliberal varchar(6) ,
religioussocialcauseconc varchar(6) ,
children varchar(6) ,
veterans varchar(6) ,
healthsocialcausesconcern varchar(6) ,
othersocialcausesconcern varchar(6) ,
baseball varchar(6) ,
basketball varchar(6) ,
hockey varchar(6) ,
campinghiking varchar(6) ,
hunting varchar(6) ,
fishing varchar(6) ,
nascar varchar(6) ,
personalfitnessexercise varchar(6) ,
scubadiving varchar(6) ,
football varchar(6) ,
golf varchar(6) ,
snowskiingboarding varchar(6) ,
boatingsailing varchar(6) ,
walking varchar(6) ,
cycling varchar(6) ,
motorcycles varchar(6) ,
runningjogging varchar(6) ,
soccer varchar(6) ,
swimming varchar(6) ,
playsportsingeneral varchar(6) ,
sweepstakes2 varchar(6) ,
lotteries varchar(6) ,
casinogambling varchar(6) ,
cruise varchar(6) ,
international varchar(6) ,
domestic varchar(6) ,
timeshare varchar(6) ,
recreationalvehicle varchar(6) ,
wouldenjoyrvtravel varchar(6) ,
businesstravel varchar(6) ,
personaltravel varchar(6) ,
owncomputer varchar(6) ,
useinternetservice varchar(6) ,
useinternetsvcdslhighspd varchar(6) ,
plantobuycomputer varchar(6) ,
cellphone varchar(6) ,
compactdiscplayer varchar(6) ,
dvdplayer varchar(6) ,
satellitedish varchar(6) ,
digitalcamera varchar(6) ,
hdtv varchar(6) ,
interestinelectronics varchar(6) ,
pesonaldataassistantpda varchar(6) ,
videocamera varchar(6) ,
videogamesystem varchar(6) ,
interestincultrualarts varchar(6) ,
businessandfinance varchar(6) ,
childrensmagazines varchar(6) ,
computerelectronics varchar(6) ,
craftsgamesandhobbies varchar(6) ,
fitness varchar(6) ,
foodwinecooking varchar(6) ,
gardeningmagazines varchar(6) ,
huntingandfishing varchar(6) ,
mens varchar(6) ,
music varchar(6) ,
parentingbabies varchar(6) ,
sportsmagazines varchar(6) ,
subscription varchar(6) ,
travel varchar(6) ,
womens varchar(6) ,
currenteventsnews varchar(6) ,
haveleasedavehicle varchar(6) ,
havepurchasedavehicle varchar(6) ,
bookclub varchar(6) ,
musicclub varchar(6) ,
americanexpresspremium varchar(6) ,
americanexpressregular varchar(6) ,
discoverpremium varchar(6) ,
discoverregular varchar(6) ,
othercardpremium varchar(6) ,
othercardregular varchar(6) ,
storeorretailregular varchar(6) ,
visaregular varchar(6) ,
mastercardregular varchar(6) ,
humanitarian varchar(6) ,
buyprerecordedvideos varchar(6) ,
watchcabletv varchar(6) ,
watchvideos varchar(6) ,
cdsmoneymarketcurrently varchar(6) ,
irascurrently varchar(6) ,
irasfutureinterest varchar(6) ,
lifeinsurancecurrently varchar(6) ,
mutualfundscurrently varchar(6) ,
mutualfundsfutureinterest varchar(6) ,
otherinvestmentscurrently varchar(6) ,
otherinvestmtfutureinteres varchar(6) ,
realestatecurrently varchar(6) ,
realestatefutureinterest varchar(6) ,
stocksbondscurrently varchar(6) ,
stocksbondsfutureinterest varchar(6) ,
proudgrandparent varchar(6) ,
purchaseitemsviatheinterne varchar(6) ,
activemilitarymember varchar(6) ,
vetern varchar(6) ,
ownacat varchar(6) ,
ownadog varchar(6) ,
ownapet varchar(6) ,
byinternet varchar(6) ,
bymail varchar(6) ,
bycatalog varchar(6) ,
apparel varchar(6) ,
computerorelectronics varchar(6) ,
booksandmusic varchar(6) ,
homeandgarden varchar(6) ,
sportsrelated varchar(6) ,
bigtall varchar(6) ,
mailorderbooksmag varchar(6) ,
mailorderclothing varchar(6) ,
mailordergardening varchar(6) ,
mailordergift varchar(6) ,
mailorderjewelrycosmetics varchar(6) ,
mailordermusicvideos varchar(6) ,
mailorderchildrensproducts varchar(6) ,
actintamusementparkvisit integer ,
actintzoovisit integer ,
actintcoffeeconnoisseurs integer ,
actintwinelovers integer ,
actintdoityourselfers integer ,
actinhomeimprov integer ,
actinthuntingenthusiasts integer ,
buyerlaptopowners integer ,
buyersecuritysysowners integer ,
buyertabletowners integer ,
buyercouponusers integer ,
buyerluxurystoreshop integer ,
buyeryoungadultclothshop integer ,
buyersupercentershop integer ,
buywarehclubmember integer ,
membershipsaarpmembers integer ,
lifestylelifeinspolicy integer ,
lifestylemedicalpolicy integer ,
lifestylemedicarepolicy integer ,
actindigimagnewspaper integer ,
actinattendeduprog integer ,
actintvideogamer integer ,
actintmlbenthusiast integer ,
actintnascarenthusiast integer ,
actintnbaenthusiast integer ,
actintnflenthusiast integer ,
actintnhlenthusiast integer ,
actintpgatourenthusiast integer ,
actintpoliticaltvliberal integer ,
actinpolitvlibcom integer ,
actinpolitvcons integer ,
actineatsfamrestrnt integer ,
actinteatsfastfood integer ,
actintcanoeingkayaking integer ,
actintplaygolf integer ,
buyautomobile integer ,
buyerloyaltycarduser integer ,
buyerluxhomegoodshop integer ,
membershipsunionmember integer ,
investhaveretirementplan integer ,
investonlinetrading integer ,
havegrandchild integer ,
buyernondeptstoremakeup integer ,
actintgourmetcooking integer ,
actintcatowners integer ,
actintdogowners integer ,
actintartsandcrafts integer ,
actintscrapbooking integer ,
actintculturalarts integer ,
hobbiesgardening integer ,
actintphotography integer ,
actintbookreader integer ,
actintebookreader integer ,
actintaudiobooklistener integer ,
actintpetenthusiast integer ,
actintmusicdownload integer ,
actintmusicstreaming integer ,
actintavidrunners integer ,
actintoutdoorenthusiast integer ,
actintfishing integer ,
actintsnowsports integer ,
actintboating integer ,
actintplayshockey integer ,
actintplayssoccer integer ,
actintplaystennis integer ,
actintsportsenthusiast integer ,
actinthealthyliving integer ,
actintfitnessenthusiast integer ,
actintonadiet integer ,
actintweightconscious integer ,
buyhighendspiritdrink integer ,
actintcasinogambling integer ,
actintsweepstakeslottery integer ,
stylehighfreqbusintrvl integer ,
stylehighfreqcruise integer ,
stylehighfreqdomesticvac integer ,
stylehighfreqforeignvac integer ,
stylefrequentflyerprgmbr integer ,
stylehotelloyaltyprg integer ,
donorcontribtocharities integer ,
donorcontribarts integer ,
donorcontribtoeducation integer ,
donorcontribtohealth integer ,
donorcontribtopolitical integer ,
donorcontribtoprvtfound integer ,
donorcontribvolunt integer ,
findebitcarduser integer ,
fincorpcreditcardusr integer ,
finmajorcreditcarduser integer ,
finpremiumcreditcarduser integer ,
fincreditcarduser integer ,
finstorecreditcarduser integer ,
invbrokerageaccountowner integer ,
invactiveinvor integer ,
invmutualfundinvor integer ,
buyerdeptstoremakeupuser integer ,
actintchristianmusic integer ,
actintclassicalmusic integer ,
actintcountrymusic integer ,
actintmusic integer ,
actintoldiesmusic integer ,
actintrockmusic integer ,
actint80smusic integer ,
actinthiphopmusic integer ,
actintalternativemusic integer ,
actintjazzmusic integer ,
actintpopmusic integer ,
lifestyleintinreligion integer ,
lifestylemilitaryactive integer ,
lifestylemilitaryinactive integer ,
workingcouples integer ,
poc03yrsoldgenderv3 varchar(6) ,
poc46yrsoldgenderv3 varchar(6) ,
poc79yrsoldgenderv3 varchar(6) ,
poc1012yrsoldgenderv3 varchar(6) ,
poc1315yrsoldgenderv3 varchar(6) ,
poc1618yrsoldgenderv3 varchar(6) ,
discretionaryspendestlevel varchar(6) ,
discretspendestscore integer ,
actinteatsfamilyrestaurant integer ,
sas_brand_id integer ,
fs_sk integer ,
process_dtm TIMESTAMP default null
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.experian_gold (select * from whousep.experian_gold);

DROP TABLE IF EXISTS vfap_retail.farnorthern_style;
CREATE TABLE IF NOT EXISTS vfap_retail.farnorthern_style(
department_code integer ,
department_description varchar(45) ,
class_code integer ,
class_description varchar(33) ,
style_id integer ,
vendor_style varchar(18) ,
style_description varchar(75) ,
vendor_cd_4 varchar(12) ,
vendor_cd_6 varchar(18) ,
cnodeid integer ,
short_name varchar(24) ,
long_name varchar(24) ,
style_description_short varchar(60) ,
style_description_long varchar(108) ,
product_line varchar(66) ,
sbu varchar(39) ,
series varchar(39) ,
newconsumersegmentterritory varchar(51) ,
newendusesport varchar(51) ,
newproductcollectionfamily varchar(39) ,
tnf___clm_description_for_sas varchar(81) 
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.farnorthern_style (select * from whousep.farnorthern_style);

DROP TABLE IF EXISTS vfap_retail.first_name_gender_prob;
CREATE TABLE IF NOT EXISTS vfap_retail.first_name_gender_prob(
name VARCHAR(15) ,
prob_gender VARCHAR(1)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.first_name_gender_prob (select * from whousep.first_name_gender_prob);

DROP TABLE IF EXISTS vfap_retail.loyalty_xref;
CREATE TABLE IF NOT EXISTS vfap_retail.loyalty_xref(
customer_id INTEGER ,
loya_id VARCHAR(61) ,--65535 in vfap_retail
process_dtm TIMESTAMP default null
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.loyalty_xref (select * from whousep.loyalty_xref);

DROP TABLE IF EXISTS vfap_retail.productxref;
CREATE TABLE IF NOT EXISTS vfap_retail.productxref(
sas_brand_id INTEGER ,
product_code BIGINT ,
style_id INTEGER ,
color_code INTEGER ,
primary_size_label VARCHAR(5) ,
secondary_size_label VARCHAR(3) ,
primary_size_code INTEGER ,
secondary_size_code INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.productxref (select * from whousep.productxref);

DROP table IF EXISTS vfap_retail.rainwear_style;
CREATE TABLE IF NOT EXISTS vfap_retail.rainwear_style(
style_id integer,	
style_description varchar(75),	
department_code integer,	
department_description varchar(51),	
class_code integer,	
class_description varchar(63),	
territory varchar(54),	
activity varchar(69),	
vendor_style varchar(18),	
vendor_cd_4	varchar(12),	
vendor_cd_6 varchar(18),	
process_dtm	TIMESTAMP default sysdate,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.rainwear_style (select * from rainwear_style);

DROP table IF EXISTS vfap_retail.region;
CREATE TABLE IF NOT EXISTS vfap_retail.region(
region_code INTEGER ,
region_name VARCHAR(24) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.region (select * from whousep.region);

DROP table IF EXISTS vfap_retail.score_stat_history;
CREATE TABLE IF NOT EXISTS vfap_retail.score_stat_history(
model VARCHAR(80) ,
min_score INTEGER ,
max_score INTEGER ,
high_cutoff INTEGER ,
low_cutoff INTEGER ,
dt TIMESTAMP WITHOUT TIME ZONE ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.score_stat_history (select * from whousep.score_stat_history);

DROP table IF EXISTS vfap_retail.sl_challenge_resp;
CREATE TABLE IF NOT EXISTS vfap_retail.sl_challenge_resp(
challenge_id VARCHAR(30) ,
member_id VARCHAR(19) ,
challenge_name VARCHAR(88) ,
challenge_label VARCHAR(92) ,
response VARCHAR(150) , 
challenge_status VARCHAR(27) ,
sl_activity_ts TIMESTAMP WITHOUT TIME ZONE ,
sl_type VARCHAR(15) ,
sl_subtype VARCHAR(24) ,
sl_context VARCHAR(30) , 
sl_metric VARCHAR(15) ,
sl_value VARCHAR(8) ,
sl_client VARCHAR(17) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.sl_challenge_resp (select * from whousep.sl_challenge_resp);

DROP table IF EXISTS vfap_retail.sl_members;
CREATE TABLE IF NOT EXISTS vfap_retail.sl_members(
member_id VARCHAR(11) ,
email VARCHAR(53) ,
first_name VARCHAR(150) ,
last_name VARCHAR(150) ,
mailing_street VARCHAR(153) ,
mailing_city VARCHAR(116) ,
mailing_state VARCHAR(2) ,
mailing_postal_code VARCHAR(212) ,
mailing_country VARCHAR(2) ,
birthdate TIMESTAMP WITHOUT TIME ZONE ,
mobile_phone BIGINT ,
member_since TIMESTAMP WITHOUT TIME ZONE ,
receive_sms_offers VARCHAR(5) ,
receive_e_statements VARCHAR(5) ,
suspend_email VARCHAR(5) ,
suspend_email_date TIMESTAMP WITHOUT TIME ZONE ,
suspend_email_cause VARCHAR(2199) ,
referrer_id VARCHAR(11) ,
last_active_at TIMESTAMP WITHOUT TIME ZONE ,
deactivated VARCHAR(5) ,
integration_id BIGINT ,
test_member VARCHAR(5) ,
visitor VARCHAR(5) ,
card_id VARCHAR(20) ,
created_at TIMESTAMP WITHOUT TIME ZONE ,
sl_contest VARCHAR(1) ,
sl_prize VARCHAR(1) ,
sl_referral bigint ,
point VARCHAR(19) ,
points_earned_total BIGINT ,
points_redeemed_total BIGINT ,
points_expired_total BIGINT ,
source VARCHAR(8) ,
sl_challenge VARCHAR(1) ,
sl_push INTEGER ,
crmnumber BIGINT ,
sl_login DOUBLE PRECISION  ,
employee VARCHAR(5) ,
sl_cancel_earn INTEGER ,
tenure INTEGER ,
sl_adjust_redeem INTEGER ,
shoe_size DOUBLE PRECISION  ,
sl_member_attribute INTEGER ,
sl_offer INTEGER ,
store_number VARCHAR(37) ,
sl_adjust_earn INTEGER ,
mailing_street2 VARCHAR(252) ,
sl_cancel_redeem BIGINT  ,
beta_allowed VARCHAR(5) ,
sl_survey INTEGER ,
sl_view INTEGER ,
has_device VARCHAR(5) ,
sl_reward INTEGER ,
sl_member_confirm INTEGER ,
confirmed_at TIMESTAMP WITHOUT TIME ZONE ,
sl_email INTEGER ,
sl_post VARCHAR(1) ,
interests VARCHAR(57) ,
receive_personalized_offers VARCHAR(5) ,
sl_member_preference INTEGER ,
sl_expire VARCHAR(1) ,
sl_purchase INTEGER ,
sl_visitor_sign_up INTEGER ,
employee_number BIGINT  ,
shoe_gender VARCHAR(6) ,
source_campaign VARCHAR(75) ,
sl_sign_up INTEGER ,
test_group VARCHAR(7) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.sl_members (select * from whousep.sl_members);

DROP TABLE IF EXISTS vfap_retail.sl_message_resp;
CREATE TABLE IF NOT EXISTS vfap_retail.sl_message_resp(
sl_member_id VARCHAR(11) ,
message_id INTEGER ,
label VARCHAR(67) ,
message_action VARCHAR(7) ,
sl_activity_ts TIMESTAMP WITHOUT TIME ZONE ,
sl_type VARCHAR(8) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.sl_message_resp (select * from whousep.sl_message_resp);

DROP TABLE IF EXISTS vfap_retail.sl_orders;
CREATE TABLE IF NOT EXISTS vfap_retail.sl_orders(
sl_activity_ts TIMESTAMP WITHOUT TIME ZONE ,
sl_type VARCHAR(11) ,
sl_member_id VARCHAR(11) ,
sl_context VARCHAR(6) ,
sl_subtype VARCHAR(4) ,
sl_parent_id INTEGER ,
sl_metric VARCHAR(5) ,
sl_value DOUBLE PRECISION  ,
sl_integration_id VARCHAR(24) ,
sl_location VARCHAR(20), 
earn_type VARCHAR(4) ,
sl_tz VARCHAR(19) ,
sl_order_status VARCHAR(9) ,
sl_transaction_id BIGINT ,
sl_employee_id INTEGER ,
sl_subtotal DOUBLE PRECISION  ,
sl_overall_discount INTEGER ,
sl_item_count INTEGER ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.sl_orders (select * from whousep.sl_orders);

DROP TABLE IF EXISTS vfap_retail.sl_reward_resp;
CREATE TABLE IF NOT EXISTS vfap_retail.sl_reward_resp(
sl_activity_ts TIMESTAMP WITHOUT TIME ZONE ,
sl_type VARCHAR(9) ,
sl_member_id VARCHAR(11) ,
sl_context VARCHAR(9) ,
sl_subtype VARCHAR(7) ,
sl_label VARCHAR(57) ,
sl_parent_id INTEGER ,
sl_parent_name VARCHAR(54) ,
sl_metric VARCHAR(5) ,
sl_value INTEGER ,
sl_creator_type VARCHAR(6) ,
sl_client VARCHAR(10) ,
sl_status VARCHAR(9) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.sl_reward_resp (select * from sl_reward_resp);

DROP TABLE IF EXISTS vfap_retail.snowsports_style;
CREATE TABLE IF NOT EXISTS vfap_retail.snowsports_style(
department_code integer ,
department_description varchar(72) ,
class_code integer ,
class_description varchar(75) ,
style_id integer ,
vendor_style varchar(18) ,
style_description varchar(75) ,
vendor_cd_4 varchar(12) ,
vendor_cd_6 varchar(18) ,
cnodeid integer ,
short_name varchar(24) ,
long_name varchar(24) ,
style_description_short varchar(60) ,
style_description_long varchar(120) ,
product_line varchar(72) ,
sbu varchar(39) ,
series varchar(36) ,
newconsumersegmentterritory varchar(45) ,
newendusesport varchar(30) ,
newproductcollectionfamily varchar(36) ,
tnf___clm_description_for_sas varchar(120) ,
snowsports_flag varchar(30) ,
snowsports_subsegment varchar(36) 
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.snowsports_style (select * from whousep.snowsports_style);

DROP TABLE IF EXISTS vfap_retail.store;
CREATE TABLE IF NOT EXISTS vfap_retail.store(
store_no INTEGER ,
store_name VARCHAR(25) ,
store_grouping_code_a VARCHAR(3) ,
store_address_1 VARCHAR(40) ,
store_address_2 VARCHAR(25) ,
store_address_3 VARCHAR(19) ,
store_address_4 VARCHAR(3) ,
store_post_code VARCHAR(10) ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.store (select * from whousep.store);

DROP TABLE IF EXISTS vfap_retail.string_pos_xref;
CREATE TABLE IF NOT EXISTS vfap_retail.string_pos_xref(
group_code VARCHAR(50) ,
col_name VARCHAR(50) ,
string_pos INTEGER ,
pos_label VARCHAR(100) ,
pos_label_desc VARCHAR(100) ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.string_pos_xref (select * from whousep.string_pos_xref);

DROP TABLE IF EXISTS vfap_retail.style;
CREATE TABLE IF NOT EXISTS vfap_retail.style(
style_id INTEGER ,
vendor_code INTEGER ,
class_code INTEGER ,
subclass_code INTEGER ,
vendor_style VARCHAR(8) ,
style_aka VARCHAR(20) ,
style_description VARCHAR(29) ,
retail DOUBLE PRECISION ,
cost DOUBLE PRECISION ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.style (select * from whousep.style);

DROP TABLE IF EXISTS vfap_retail.style_xref_clean;
CREATE TABLE IF NOT EXISTS vfap_retail.style_xref_clean(
department_code INTEGER ,
department_description VARCHAR(25) ,
class_code INTEGER ,
class_description VARCHAR(25) ,
style_id INTEGER ,
vendor_style VARCHAR(6) ,
style_description VARCHAR(25) ,
vendor_cd_4 VARCHAR(8) ,
vendor_cd_6 VARCHAR(6) ,
cnodeid INTEGER ,
short_name VARCHAR(8) ,
long_name VARCHAR(8) ,
style_description_short VARCHAR(25) ,
style_description_long VARCHAR(40) ,
product_line VARCHAR(39) ,
sbu VARCHAR(22) ,
series VARCHAR(13) ,
newconsumersegmentterritory VARCHAR(18) ,
newendusesport VARCHAR(23) ,
newproductcollectionfamily VARCHAR(18) ,
tnf___clm_description_for_sas VARCHAR(41) ,
tnf_sas_product_category VARCHAR(50) ,
product_gender VARCHAR(1) ,
product_age_group VARCHAR(5) ,
sas_style_description VARCHAR(100) ,
gender_age VARCHAR(7) ,
tb_flag INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.style_xref_clean (select * from whousep.style_xref_clean);

DROP TABLE IF EXISTS vfap_retail.summit_style_ids_new;
CREATE TABLE IF NOT EXISTS vfap_retail.summit_style_ids_new(
department_code integer ,
department_description varchar(75) ,
class_code integer ,
class_description varchar(75) ,
style_id integer ,
vendor_style varchar(18) ,
style_description varchar(75) ,
vendor_cd_4 varchar(12) ,
vendor_cd_6 varchar(18) ,
cnodeid integer ,
short_name varchar(24) ,
long_name varchar(24) ,
style_description_short varchar(63) ,
style_description_long varchar(117) ,
product_line varchar(108) ,
sbu varchar(45) ,
series varchar(39) ,
newconsumersegmentterritory varchar(45) ,
newendusesport varchar(69) ,
newproductcollectionfamily varchar(39) ,
tnf___clm_description_for_sas varchar(99) 
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.summit_style_ids_new (select * from whousep.summit_style_ids_new);

DROP TABLE IF EXISTS vfap_retail.thermoball_style;
CREATE TABLE IF NOT EXISTS vfap_retail.thermoball_style(
department_code integer ,
department_description varchar(66) ,
class_code integer ,
class_description varchar(72) ,
style_id integer ,
vendor_style varchar(18) ,
style_description varchar(75) ,
vendor_cd_4 varchar(12) ,
vendor_cd_6 varchar(18) ,
cnodeid integer ,
short_name varchar(24) ,
long_name varchar(24) ,
style_description_short varchar(60) ,
style_description_long varchar(117) ,
product_line varchar(105) ,
sbu varchar(45) ,
series varchar(39) ,
newconsumersegmentterritory varchar(54) ,
newendusesport varchar(51) ,
newproductcollectionfamily varchar(39) ,
tnf___clm_description_for_sas varchar(84) ,
thermoball_flag varchar(30) 
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.thermoball_style (select * from whousep.thermoball_style);

DROP TABLE IF EXISTS vfap_retail.tnf_adobe_cart_abandon;
CREATE TABLE IF NOT EXISTS vfap_retail.tnf_adobe_cart_abandon(
dt TIMESTAMP WITHOUT TIME ZONE,
visitor_id VARCHAR(41),
webs_customer_id VARCHAR(11),
products VARCHAR(13),
cart_additions INTEGER,
sas_brand_id INTEGER,
fs_sk INTEGER,
customer_id VARCHAR(11),
sas_product_id VARCHAR(20),
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.tnf_adobe_cart_abandon (select * from whousep.tnf_adobe_cart_abandon);

DROP TABLE IF EXISTS vfap_retail.tnf_adobe_cart_xref_final;
CREATE TABLE IF NOT EXISTS vfap_retail.tnf_adobe_cart_xref_final(
visitor_id VARCHAR(41) ,
customer_id VARCHAR(11) ,
sas_brand_id INTEGER ,
process_dtm TIMESTAMP default null
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.tnf_adobe_cart_xref_final (select * from whousep.tnf_adobe_cart_xref_final);

DROP TABLE IF EXISTS vfap_retail.tnf_adobe_productview_abandon;
CREATE TABLE IF NOT EXISTS vfap_retail.tnf_adobe_productview_abandon(
dt TIMESTAMP WITHOUT TIME ZONE ,
visitor_id VARCHAR(41) ,
webs_customer_id VARCHAR(11) ,
products VARCHAR(13) ,
product_views INTEGER ,
sas_brand_id INTEGER ,
fs_sk INTEGER ,
customer_id VARCHAR(11) ,
sas_product_id VARCHAR(20) ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.tnf_adobe_productview_abandon (select * from whousep.tnf_adobe_productview_abandon);

DROP TABLE IF EXISTS vfap_retail.tnf_adobe_prodview_xref_final;
CREATE TABLE IF NOT EXISTS vfap_retail.tnf_adobe_prodview_xref_final(
visitor_id VARCHAR(41) ,
customer_id VARCHAR(11) ,
sas_brand_id INTEGER ,
process_dtm TIMESTAMP default null
)
DISTSTYLE EVEN;
INSERT INTO vfap_retail.tnf_adobe_prodview_xref_final (select * from whousep.tnf_adobe_prodview_xref_final);

DROP TABLE IF EXISTS vfap_retail.tnf_email_click;
CREATE TABLE IF NOT EXISTS vfap_retail.tnf_email_click(
sas_brand_id INTEGER ,
customer_id INTEGER ,
event_type_id INTEGER ,
account_id INTEGER ,
list_id INTEGER ,
riid BIGINT ,
customer_no BIGINT ,
event_captured_dt TIMESTAMP WITHOUT TIME ZONE ,
event_stored_dt TIMESTAMP WITHOUT TIME ZONE ,
campaign_id BIGINT ,
launch_id INTEGER ,
email_format VARCHAR(1) ,
offer_name VARCHAR(24) ,
offer_number INTEGER ,
offer_category VARCHAR(28) ,
offer_url VARCHAR(216) ,
store_id VARCHAR(10) ,
operating_system VARCHAR(3) ,
browser VARCHAR(2) ,
browser_type VARCHAR(2) ,
user_agent_string VARCHAR(100) ,
fs_sk INTEGER ,
process_dtm TIMESTAMP default null,
file_name VARCHAR(200)
)
DISTSTYLE EVEN;

CREATE VIEW vfap_retail.tnf_email_click_view
AS (SELECT LIST_ID ,
    RIID ,
    CUSTOMER_ID,
    EVENT_CAPTURED_DT ,
    CAMPAIGN_ID ,
    LAUNCH_ID ,
    OFFER_NAME
  FROM vfap_retail.tnf_email_click
  UNION ALL
  SELECT LIST_ID ,
    RIID ,
    CUSTOMER_ID,
    EVENT_CAPTURED_DT ,
    CAMPAIGN_ID ,
    LAUNCH_ID ,
    OFFER_NAME
  FROM vfap_retail.tnf_email_click_hist
  );
  
CREATE VIEW vfap_retail.tnf_email_launch_view
AS (SELECT ACCOUNT_ID ,
    LIST_ID ,
    CAMPAIGN_ID ,
    LAUNCH_ID ,
    EXTERNAL_CAMPAIGN_ID ,
    SF_CAMPAIGN_ID ,
    CAMPAIGN_NAME ,
    LAUNCH_NAME ,
    LAUNCH_STATUS ,
    LAUNCH_TYPE ,
    LAUNCH_CHARSET ,
    PURPOSE ,
    SUBJECT ,
    DESCRIPTION ,
    PRODUCT_CATEGORY ,
    PRODUCT_TYPE ,
    MARKETING_STRATEGY ,
    MARKETING_PROGRAM ,
    LAUNCH_ERROR_CODE ,
    EVENT_CAPTURED_DT ,
    EVENT_STORED_DT ,
    LAUNCH_COMPLETED_DT ,
    LAUNCH_STARTED_DT
  FROM vfap_retail.tnf_email_launch
  UNION ALL
  SELECT ACCOUNT_ID ,
    LIST_ID ,
    CAMPAIGN_ID ,
    LAUNCH_ID ,
    EXTERNAL_CAMPAIGN_ID ,
    SF_CAMPAIGN_ID ,
    CAMPAIGN_NAME ,
    LAUNCH_NAME ,
    LAUNCH_STATUS ,
    LAUNCH_TYPE ,
    LAUNCH_CHARSET ,
    PURPOSE ,
    SUBJECT ,
    DESCRIPTION ,
    PRODUCT_CATEGORY ,
    PRODUCT_TYPE ,
    MARKETING_STRATEGY ,
    MARKETING_PROGRAM ,
    LAUNCH_ERROR_CODE ,
    EVENT_CAPTURED_DT ,
    EVENT_STORED_DT ,
    LAUNCH_COMPLETED_DT ,
    LAUNCH_STARTED_DT
  FROM vfap_retail.tnf_email_launch_hist
  );

CREATE VIEW vfap_retail.tnf_email_open_view
AS (SELECT LIST_ID ,
    RIID ,
    EVENT_CAPTURED_DT ,
    CAMPAIGN_ID ,
    LAUNCH_ID
  FROM vfap_retail.tnf_email_open
  UNION ALL
  SELECT LIST_ID ,
    RIID ,
    EVENT_CAPTURED_DT ,
    CAMPAIGN_ID ,
    LAUNCH_ID
  FROM vfap_retail.tnf_email_open_hist
  );

CREATE VIEW vfap_retail.tnf_email_sent_view
AS (SELECT ACCOUNT_ID ,
    LIST_ID ,
    RIID ,
    CAMPAIGN_ID ,
    LAUNCH_ID ,
    EMAIL ,
    EMAIL_ISP ,
    EVENT_CAPTURED_DT ,
    CUSTOMER_ID
  FROM vfap_retail.tnf_email_sent
  WHERE customer_id     IS NOT NULL
  AND event_captured_dt IS NOT NULL
  UNION ALL
  SELECT ACCOUNT_ID ,
    LIST_ID ,
    RIID ,
    CAMPAIGN_ID ,
    LAUNCH_ID ,
    EMAIL ,
    EMAIL_ISP ,
    EVENT_CAPTURED_DT ,
    CUSTOMER_ID
  FROM vfap_retail.tnf_email_sent_hist
  WHERE customer_id     IS NOT NULL
  AND event_captured_dt IS NOT NULL
  );